/*
 * Copyright (c) 2014 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#define NO_TEST_ASSERT_EQUAL_MEMORY_MESSAGE
#include "unity.h"
#include "cmock.h"
#include "Mockplatform.h"

typedef struct _CMOCK_qeo_platform_get_device_storage_path_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_util_retcode_t ReturnVal;
  char* Expected_file_name;
  char** Expected_full_storage_path;

} CMOCK_qeo_platform_get_device_storage_path_CALL_INSTANCE;

typedef struct _CMOCK_qeo_platform_set_key_value_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_util_retcode_t ReturnVal;
  char* Expected_key;
  char* Expected_value;

} CMOCK_qeo_platform_set_key_value_CALL_INSTANCE;

typedef struct _CMOCK_qeo_platform_get_key_value_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_util_retcode_t ReturnVal;
  char* Expected_key;
  char** Expected_value;

} CMOCK_qeo_platform_get_key_value_CALL_INSTANCE;

static struct MockplatformInstance
{
  int qeo_platform_get_device_storage_path_IgnoreBool;
  qeo_util_retcode_t qeo_platform_get_device_storage_path_FinalReturn;
  CMOCK_qeo_platform_get_device_storage_path_CALLBACK qeo_platform_get_device_storage_path_CallbackFunctionPointer;
  int qeo_platform_get_device_storage_path_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_platform_get_device_storage_path_CallInstance;
  int qeo_platform_set_key_value_IgnoreBool;
  qeo_util_retcode_t qeo_platform_set_key_value_FinalReturn;
  CMOCK_qeo_platform_set_key_value_CALLBACK qeo_platform_set_key_value_CallbackFunctionPointer;
  int qeo_platform_set_key_value_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_platform_set_key_value_CallInstance;
  int qeo_platform_get_key_value_IgnoreBool;
  qeo_util_retcode_t qeo_platform_get_key_value_FinalReturn;
  CMOCK_qeo_platform_get_key_value_CALLBACK qeo_platform_get_key_value_CallbackFunctionPointer;
  int qeo_platform_get_key_value_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_platform_get_key_value_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockplatform_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.qeo_platform_get_device_storage_path_IgnoreBool)
    Mock.qeo_platform_get_device_storage_path_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_platform_get_device_storage_path_CallInstance, cmock_line, "Function 'qeo_platform_get_device_storage_path' called less times than expected.");
  if (Mock.qeo_platform_get_device_storage_path_CallbackFunctionPointer != NULL)
    Mock.qeo_platform_get_device_storage_path_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_platform_set_key_value_IgnoreBool)
    Mock.qeo_platform_set_key_value_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_platform_set_key_value_CallInstance, cmock_line, "Function 'qeo_platform_set_key_value' called less times than expected.");
  if (Mock.qeo_platform_set_key_value_CallbackFunctionPointer != NULL)
    Mock.qeo_platform_set_key_value_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_platform_get_key_value_IgnoreBool)
    Mock.qeo_platform_get_key_value_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_platform_get_key_value_CallInstance, cmock_line, "Function 'qeo_platform_get_key_value' called less times than expected.");
  if (Mock.qeo_platform_get_key_value_CallbackFunctionPointer != NULL)
    Mock.qeo_platform_get_key_value_CallInstance = CMOCK_GUTS_NONE;
}

void Mockplatform_Init(void)
{
  Mockplatform_Destroy();
}

void Mockplatform_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.qeo_platform_get_device_storage_path_CallbackFunctionPointer = NULL;
  Mock.qeo_platform_get_device_storage_path_CallbackCalls = 0;
  Mock.qeo_platform_set_key_value_CallbackFunctionPointer = NULL;
  Mock.qeo_platform_set_key_value_CallbackCalls = 0;
  Mock.qeo_platform_get_key_value_CallbackFunctionPointer = NULL;
  Mock.qeo_platform_get_key_value_CallbackCalls = 0;
}

qeo_util_retcode_t qeo_platform_get_device_storage_path(const char* file_name, char** full_storage_path)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_platform_get_device_storage_path_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_platform_get_device_storage_path_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_platform_get_device_storage_path_CallInstance);
  Mock.qeo_platform_get_device_storage_path_CallInstance = CMock_Guts_MemNext(Mock.qeo_platform_get_device_storage_path_CallInstance);
  if (Mock.qeo_platform_get_device_storage_path_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_platform_get_device_storage_path_FinalReturn;
    memcpy(&Mock.qeo_platform_get_device_storage_path_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_util_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_platform_get_device_storage_path_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_platform_get_device_storage_path_CallbackFunctionPointer(file_name, full_storage_path, Mock.qeo_platform_get_device_storage_path_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_platform_get_device_storage_path' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_file_name, file_name, cmock_line, "Function 'qeo_platform_get_device_storage_path' called with unexpected value for argument 'file_name'.");
  if (cmock_call_instance->Expected_full_storage_path == NULL)
    { UNITY_TEST_ASSERT_NULL(full_storage_path, cmock_line, "Expected NULL. Function 'qeo_platform_get_device_storage_path' called with unexpected value for argument 'full_storage_path'."); }
  else
    { UNITY_TEST_ASSERT_EQUAL_STRING_ARRAY(cmock_call_instance->Expected_full_storage_path, full_storage_path, 1, cmock_line, "Function 'qeo_platform_get_device_storage_path' called with unexpected value for argument 'full_storage_path'."); }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_platform_get_device_storage_path(CMOCK_qeo_platform_get_device_storage_path_CALL_INSTANCE* cmock_call_instance, const char* file_name, char** full_storage_path)
{
  cmock_call_instance->Expected_file_name = (char*)file_name;
  memcpy(&cmock_call_instance->Expected_full_storage_path, &full_storage_path, sizeof(char**));
}

void qeo_platform_get_device_storage_path_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_util_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_platform_get_device_storage_path_CALL_INSTANCE));
  CMOCK_qeo_platform_get_device_storage_path_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_platform_get_device_storage_path_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_platform_get_device_storage_path_CallInstance = CMock_Guts_MemChain(Mock.qeo_platform_get_device_storage_path_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_platform_get_device_storage_path_IgnoreBool = (int)1;
}

void qeo_platform_get_device_storage_path_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* file_name, char** full_storage_path, qeo_util_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_platform_get_device_storage_path_CALL_INSTANCE));
  CMOCK_qeo_platform_get_device_storage_path_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_platform_get_device_storage_path_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_platform_get_device_storage_path_CallInstance = CMock_Guts_MemChain(Mock.qeo_platform_get_device_storage_path_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_platform_get_device_storage_path(cmock_call_instance, file_name, full_storage_path);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_util_retcode_t));
}

void qeo_platform_get_device_storage_path_StubWithCallback(CMOCK_qeo_platform_get_device_storage_path_CALLBACK Callback)
{
  Mock.qeo_platform_get_device_storage_path_CallbackFunctionPointer = Callback;
}

qeo_util_retcode_t qeo_platform_set_key_value(const char* key, char* value)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_platform_set_key_value_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_platform_set_key_value_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_platform_set_key_value_CallInstance);
  Mock.qeo_platform_set_key_value_CallInstance = CMock_Guts_MemNext(Mock.qeo_platform_set_key_value_CallInstance);
  if (Mock.qeo_platform_set_key_value_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_platform_set_key_value_FinalReturn;
    memcpy(&Mock.qeo_platform_set_key_value_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_util_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_platform_set_key_value_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_platform_set_key_value_CallbackFunctionPointer(key, value, Mock.qeo_platform_set_key_value_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_platform_set_key_value' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_key, key, cmock_line, "Function 'qeo_platform_set_key_value' called with unexpected value for argument 'key'.");
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_value, value, cmock_line, "Function 'qeo_platform_set_key_value' called with unexpected value for argument 'value'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_platform_set_key_value(CMOCK_qeo_platform_set_key_value_CALL_INSTANCE* cmock_call_instance, const char* key, char* value)
{
  cmock_call_instance->Expected_key = (char*)key;
  cmock_call_instance->Expected_value = value;
}

void qeo_platform_set_key_value_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_util_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_platform_set_key_value_CALL_INSTANCE));
  CMOCK_qeo_platform_set_key_value_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_platform_set_key_value_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_platform_set_key_value_CallInstance = CMock_Guts_MemChain(Mock.qeo_platform_set_key_value_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_platform_set_key_value_IgnoreBool = (int)1;
}

void qeo_platform_set_key_value_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* key, char* value, qeo_util_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_platform_set_key_value_CALL_INSTANCE));
  CMOCK_qeo_platform_set_key_value_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_platform_set_key_value_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_platform_set_key_value_CallInstance = CMock_Guts_MemChain(Mock.qeo_platform_set_key_value_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_platform_set_key_value(cmock_call_instance, key, value);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_util_retcode_t));
}

void qeo_platform_set_key_value_StubWithCallback(CMOCK_qeo_platform_set_key_value_CALLBACK Callback)
{
  Mock.qeo_platform_set_key_value_CallbackFunctionPointer = Callback;
}

qeo_util_retcode_t qeo_platform_get_key_value(const char* key, char** value)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_platform_get_key_value_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_platform_get_key_value_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_platform_get_key_value_CallInstance);
  Mock.qeo_platform_get_key_value_CallInstance = CMock_Guts_MemNext(Mock.qeo_platform_get_key_value_CallInstance);
  if (Mock.qeo_platform_get_key_value_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_platform_get_key_value_FinalReturn;
    memcpy(&Mock.qeo_platform_get_key_value_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_util_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_platform_get_key_value_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_platform_get_key_value_CallbackFunctionPointer(key, value, Mock.qeo_platform_get_key_value_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_platform_get_key_value' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_key, key, cmock_line, "Function 'qeo_platform_get_key_value' called with unexpected value for argument 'key'.");
  if (cmock_call_instance->Expected_value == NULL)
    { UNITY_TEST_ASSERT_NULL(value, cmock_line, "Expected NULL. Function 'qeo_platform_get_key_value' called with unexpected value for argument 'value'."); }
  else
    { UNITY_TEST_ASSERT_EQUAL_STRING_ARRAY(cmock_call_instance->Expected_value, value, 1, cmock_line, "Function 'qeo_platform_get_key_value' called with unexpected value for argument 'value'."); }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_platform_get_key_value(CMOCK_qeo_platform_get_key_value_CALL_INSTANCE* cmock_call_instance, const char* key, char** value)
{
  cmock_call_instance->Expected_key = (char*)key;
  memcpy(&cmock_call_instance->Expected_value, &value, sizeof(char**));
}

void qeo_platform_get_key_value_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_util_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_platform_get_key_value_CALL_INSTANCE));
  CMOCK_qeo_platform_get_key_value_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_platform_get_key_value_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_platform_get_key_value_CallInstance = CMock_Guts_MemChain(Mock.qeo_platform_get_key_value_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_platform_get_key_value_IgnoreBool = (int)1;
}

void qeo_platform_get_key_value_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* key, char** value, qeo_util_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_platform_get_key_value_CALL_INSTANCE));
  CMOCK_qeo_platform_get_key_value_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_platform_get_key_value_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_platform_get_key_value_CallInstance = CMock_Guts_MemChain(Mock.qeo_platform_get_key_value_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_platform_get_key_value(cmock_call_instance, key, value);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_util_retcode_t));
}

void qeo_platform_get_key_value_StubWithCallback(CMOCK_qeo_platform_get_key_value_CALLBACK Callback)
{
  Mock.qeo_platform_get_key_value_CallbackFunctionPointer = Callback;
}

