/*
 * Copyright (c) 2014 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#define NO_TEST_ASSERT_EQUAL_MEMORY_MESSAGE
#include "unity.h"
#include "cmock.h"
#include "Mockplatform_security.h"

typedef struct _CMOCK_qeo_platform_security_registration_credentials_needed_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_util_retcode_t ReturnVal;
  qeo_platform_security_context_t Expected_context;
  qeo_platform_security_set_registration_credentials_cb Expected_set_reg_cred_cb;
  qeo_platform_security_registration_credentials_cancelled_cb Expected_set_cancelled_cb;

} CMOCK_qeo_platform_security_registration_credentials_needed_CALL_INSTANCE;

typedef struct _CMOCK_qeo_platform_security_update_state_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_platform_security_context_t Expected_context;
  qeo_platform_security_state Expected_state;
  qeo_platform_security_state_reason Expected_state_reason;

} CMOCK_qeo_platform_security_update_state_CALL_INSTANCE;

typedef struct _CMOCK_qeo_platform_security_remote_registration_confirmation_needed_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_util_retcode_t ReturnVal;
  qeo_platform_security_context_t Expected_context;
  qeo_platform_security_remote_registration_credentials_t* Expected_rrcred;
  qeo_platform_security_remote_registration_credentials_feedback_cb Expected_cb;

} CMOCK_qeo_platform_security_remote_registration_confirmation_needed_CALL_INSTANCE;

static struct Mockplatform_securityInstance
{
  int qeo_platform_security_registration_credentials_needed_IgnoreBool;
  qeo_util_retcode_t qeo_platform_security_registration_credentials_needed_FinalReturn;
  CMOCK_qeo_platform_security_registration_credentials_needed_CALLBACK qeo_platform_security_registration_credentials_needed_CallbackFunctionPointer;
  int qeo_platform_security_registration_credentials_needed_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_platform_security_registration_credentials_needed_CallInstance;
  int qeo_platform_security_update_state_IgnoreBool;
  CMOCK_qeo_platform_security_update_state_CALLBACK qeo_platform_security_update_state_CallbackFunctionPointer;
  int qeo_platform_security_update_state_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_platform_security_update_state_CallInstance;
  int qeo_platform_security_remote_registration_confirmation_needed_IgnoreBool;
  qeo_util_retcode_t qeo_platform_security_remote_registration_confirmation_needed_FinalReturn;
  CMOCK_qeo_platform_security_remote_registration_confirmation_needed_CALLBACK qeo_platform_security_remote_registration_confirmation_needed_CallbackFunctionPointer;
  int qeo_platform_security_remote_registration_confirmation_needed_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_platform_security_remote_registration_confirmation_needed_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockplatform_security_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.qeo_platform_security_registration_credentials_needed_IgnoreBool)
    Mock.qeo_platform_security_registration_credentials_needed_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_platform_security_registration_credentials_needed_CallInstance, cmock_line, "Function 'qeo_platform_security_registration_credentials_needed' called less times than expected.");
  if (Mock.qeo_platform_security_registration_credentials_needed_CallbackFunctionPointer != NULL)
    Mock.qeo_platform_security_registration_credentials_needed_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_platform_security_update_state_IgnoreBool)
    Mock.qeo_platform_security_update_state_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_platform_security_update_state_CallInstance, cmock_line, "Function 'qeo_platform_security_update_state' called less times than expected.");
  if (Mock.qeo_platform_security_update_state_CallbackFunctionPointer != NULL)
    Mock.qeo_platform_security_update_state_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_platform_security_remote_registration_confirmation_needed_IgnoreBool)
    Mock.qeo_platform_security_remote_registration_confirmation_needed_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_platform_security_remote_registration_confirmation_needed_CallInstance, cmock_line, "Function 'qeo_platform_security_remote_registration_confirmation_needed' called less times than expected.");
  if (Mock.qeo_platform_security_remote_registration_confirmation_needed_CallbackFunctionPointer != NULL)
    Mock.qeo_platform_security_remote_registration_confirmation_needed_CallInstance = CMOCK_GUTS_NONE;
}

void Mockplatform_security_Init(void)
{
  Mockplatform_security_Destroy();
}

void Mockplatform_security_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.qeo_platform_security_registration_credentials_needed_CallbackFunctionPointer = NULL;
  Mock.qeo_platform_security_registration_credentials_needed_CallbackCalls = 0;
  Mock.qeo_platform_security_update_state_CallbackFunctionPointer = NULL;
  Mock.qeo_platform_security_update_state_CallbackCalls = 0;
  Mock.qeo_platform_security_remote_registration_confirmation_needed_CallbackFunctionPointer = NULL;
  Mock.qeo_platform_security_remote_registration_confirmation_needed_CallbackCalls = 0;
}

qeo_util_retcode_t qeo_platform_security_registration_credentials_needed(qeo_platform_security_context_t context, qeo_platform_security_set_registration_credentials_cb set_reg_cred_cb, qeo_platform_security_registration_credentials_cancelled_cb set_cancelled_cb)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_platform_security_registration_credentials_needed_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_platform_security_registration_credentials_needed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_platform_security_registration_credentials_needed_CallInstance);
  Mock.qeo_platform_security_registration_credentials_needed_CallInstance = CMock_Guts_MemNext(Mock.qeo_platform_security_registration_credentials_needed_CallInstance);
  if (Mock.qeo_platform_security_registration_credentials_needed_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_platform_security_registration_credentials_needed_FinalReturn;
    memcpy(&Mock.qeo_platform_security_registration_credentials_needed_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_util_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_platform_security_registration_credentials_needed_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_platform_security_registration_credentials_needed_CallbackFunctionPointer(context, set_reg_cred_cb, set_cancelled_cb, Mock.qeo_platform_security_registration_credentials_needed_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_platform_security_registration_credentials_needed' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_context), (void*)(&context), sizeof(qeo_platform_security_context_t), cmock_line, "Function 'qeo_platform_security_registration_credentials_needed' called with unexpected value for argument 'context'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_set_reg_cred_cb), (void*)(&set_reg_cred_cb), sizeof(qeo_platform_security_set_registration_credentials_cb), cmock_line, "Function 'qeo_platform_security_registration_credentials_needed' called with unexpected value for argument 'set_reg_cred_cb'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_set_cancelled_cb), (void*)(&set_cancelled_cb), sizeof(qeo_platform_security_registration_credentials_cancelled_cb), cmock_line, "Function 'qeo_platform_security_registration_credentials_needed' called with unexpected value for argument 'set_cancelled_cb'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_platform_security_registration_credentials_needed(CMOCK_qeo_platform_security_registration_credentials_needed_CALL_INSTANCE* cmock_call_instance, qeo_platform_security_context_t context, qeo_platform_security_set_registration_credentials_cb set_reg_cred_cb, qeo_platform_security_registration_credentials_cancelled_cb set_cancelled_cb)
{
  memcpy(&cmock_call_instance->Expected_context, &context, sizeof(qeo_platform_security_context_t));
  memcpy(&cmock_call_instance->Expected_set_reg_cred_cb, &set_reg_cred_cb, sizeof(qeo_platform_security_set_registration_credentials_cb));
  memcpy(&cmock_call_instance->Expected_set_cancelled_cb, &set_cancelled_cb, sizeof(qeo_platform_security_registration_credentials_cancelled_cb));
}

void qeo_platform_security_registration_credentials_needed_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_util_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_platform_security_registration_credentials_needed_CALL_INSTANCE));
  CMOCK_qeo_platform_security_registration_credentials_needed_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_platform_security_registration_credentials_needed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_platform_security_registration_credentials_needed_CallInstance = CMock_Guts_MemChain(Mock.qeo_platform_security_registration_credentials_needed_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_platform_security_registration_credentials_needed_IgnoreBool = (int)1;
}

void qeo_platform_security_registration_credentials_needed_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_platform_security_context_t context, qeo_platform_security_set_registration_credentials_cb set_reg_cred_cb, qeo_platform_security_registration_credentials_cancelled_cb set_cancelled_cb, qeo_util_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_platform_security_registration_credentials_needed_CALL_INSTANCE));
  CMOCK_qeo_platform_security_registration_credentials_needed_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_platform_security_registration_credentials_needed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_platform_security_registration_credentials_needed_CallInstance = CMock_Guts_MemChain(Mock.qeo_platform_security_registration_credentials_needed_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_platform_security_registration_credentials_needed(cmock_call_instance, context, set_reg_cred_cb, set_cancelled_cb);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_util_retcode_t));
}

void qeo_platform_security_registration_credentials_needed_StubWithCallback(CMOCK_qeo_platform_security_registration_credentials_needed_CALLBACK Callback)
{
  Mock.qeo_platform_security_registration_credentials_needed_CallbackFunctionPointer = Callback;
}

void qeo_platform_security_update_state(qeo_platform_security_context_t context, qeo_platform_security_state state, qeo_platform_security_state_reason state_reason)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_platform_security_update_state_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_platform_security_update_state_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_platform_security_update_state_CallInstance);
  Mock.qeo_platform_security_update_state_CallInstance = CMock_Guts_MemNext(Mock.qeo_platform_security_update_state_CallInstance);
  if (Mock.qeo_platform_security_update_state_IgnoreBool)
  {
    return;
  }
  if (Mock.qeo_platform_security_update_state_CallbackFunctionPointer != NULL)
  {
    Mock.qeo_platform_security_update_state_CallbackFunctionPointer(context, state, state_reason, Mock.qeo_platform_security_update_state_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_platform_security_update_state' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_context), (void*)(&context), sizeof(qeo_platform_security_context_t), cmock_line, "Function 'qeo_platform_security_update_state' called with unexpected value for argument 'context'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(qeo_platform_security_state), cmock_line, "Function 'qeo_platform_security_update_state' called with unexpected value for argument 'state'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state_reason), (void*)(&state_reason), sizeof(qeo_platform_security_state_reason), cmock_line, "Function 'qeo_platform_security_update_state' called with unexpected value for argument 'state_reason'.");
}

void CMockExpectParameters_qeo_platform_security_update_state(CMOCK_qeo_platform_security_update_state_CALL_INSTANCE* cmock_call_instance, qeo_platform_security_context_t context, qeo_platform_security_state state, qeo_platform_security_state_reason state_reason)
{
  memcpy(&cmock_call_instance->Expected_context, &context, sizeof(qeo_platform_security_context_t));
  memcpy(&cmock_call_instance->Expected_state, &state, sizeof(qeo_platform_security_state));
  memcpy(&cmock_call_instance->Expected_state_reason, &state_reason, sizeof(qeo_platform_security_state_reason));
}

void qeo_platform_security_update_state_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  Mock.qeo_platform_security_update_state_IgnoreBool = (int)1;
}

void qeo_platform_security_update_state_CMockExpect(UNITY_LINE_TYPE cmock_line, qeo_platform_security_context_t context, qeo_platform_security_state state, qeo_platform_security_state_reason state_reason)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_platform_security_update_state_CALL_INSTANCE));
  CMOCK_qeo_platform_security_update_state_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_platform_security_update_state_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_platform_security_update_state_CallInstance = CMock_Guts_MemChain(Mock.qeo_platform_security_update_state_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_platform_security_update_state(cmock_call_instance, context, state, state_reason);
}

void qeo_platform_security_update_state_StubWithCallback(CMOCK_qeo_platform_security_update_state_CALLBACK Callback)
{
  Mock.qeo_platform_security_update_state_CallbackFunctionPointer = Callback;
}

qeo_util_retcode_t qeo_platform_security_remote_registration_confirmation_needed(qeo_platform_security_context_t context, const qeo_platform_security_remote_registration_credentials_t* rrcred, qeo_platform_security_remote_registration_credentials_feedback_cb cb)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_platform_security_remote_registration_confirmation_needed_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_platform_security_remote_registration_confirmation_needed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_platform_security_remote_registration_confirmation_needed_CallInstance);
  Mock.qeo_platform_security_remote_registration_confirmation_needed_CallInstance = CMock_Guts_MemNext(Mock.qeo_platform_security_remote_registration_confirmation_needed_CallInstance);
  if (Mock.qeo_platform_security_remote_registration_confirmation_needed_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_platform_security_remote_registration_confirmation_needed_FinalReturn;
    memcpy(&Mock.qeo_platform_security_remote_registration_confirmation_needed_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_util_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_platform_security_remote_registration_confirmation_needed_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_platform_security_remote_registration_confirmation_needed_CallbackFunctionPointer(context, rrcred, cb, Mock.qeo_platform_security_remote_registration_confirmation_needed_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_platform_security_remote_registration_confirmation_needed' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_context), (void*)(&context), sizeof(qeo_platform_security_context_t), cmock_line, "Function 'qeo_platform_security_remote_registration_confirmation_needed' called with unexpected value for argument 'context'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_rrcred), (void*)(rrcred), sizeof(qeo_platform_security_remote_registration_credentials_t), cmock_line, "Function 'qeo_platform_security_remote_registration_confirmation_needed' called with unexpected value for argument 'rrcred'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb), sizeof(qeo_platform_security_remote_registration_credentials_feedback_cb), cmock_line, "Function 'qeo_platform_security_remote_registration_confirmation_needed' called with unexpected value for argument 'cb'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_platform_security_remote_registration_confirmation_needed(CMOCK_qeo_platform_security_remote_registration_confirmation_needed_CALL_INSTANCE* cmock_call_instance, qeo_platform_security_context_t context, const qeo_platform_security_remote_registration_credentials_t* rrcred, qeo_platform_security_remote_registration_credentials_feedback_cb cb)
{
  memcpy(&cmock_call_instance->Expected_context, &context, sizeof(qeo_platform_security_context_t));
  cmock_call_instance->Expected_rrcred = (qeo_platform_security_remote_registration_credentials_t*)rrcred;
  memcpy(&cmock_call_instance->Expected_cb, &cb, sizeof(qeo_platform_security_remote_registration_credentials_feedback_cb));
}

void qeo_platform_security_remote_registration_confirmation_needed_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_util_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_platform_security_remote_registration_confirmation_needed_CALL_INSTANCE));
  CMOCK_qeo_platform_security_remote_registration_confirmation_needed_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_platform_security_remote_registration_confirmation_needed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_platform_security_remote_registration_confirmation_needed_CallInstance = CMock_Guts_MemChain(Mock.qeo_platform_security_remote_registration_confirmation_needed_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_platform_security_remote_registration_confirmation_needed_IgnoreBool = (int)1;
}

void qeo_platform_security_remote_registration_confirmation_needed_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_platform_security_context_t context, const qeo_platform_security_remote_registration_credentials_t* rrcred, qeo_platform_security_remote_registration_credentials_feedback_cb cb, qeo_util_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_platform_security_remote_registration_confirmation_needed_CALL_INSTANCE));
  CMOCK_qeo_platform_security_remote_registration_confirmation_needed_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_platform_security_remote_registration_confirmation_needed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_platform_security_remote_registration_confirmation_needed_CallInstance = CMock_Guts_MemChain(Mock.qeo_platform_security_remote_registration_confirmation_needed_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_platform_security_remote_registration_confirmation_needed(cmock_call_instance, context, rrcred, cb);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_util_retcode_t));
}

void qeo_platform_security_remote_registration_confirmation_needed_StubWithCallback(CMOCK_qeo_platform_security_remote_registration_confirmation_needed_CALLBACK Callback)
{
  Mock.qeo_platform_security_remote_registration_confirmation_needed_CallbackFunctionPointer = Callback;
}

