/*
 * Copyright (c) 2014 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#define NO_TEST_ASSERT_EQUAL_MEMORY_MESSAGE
#include "unity.h"
#include "cmock.h"
#include "Mockmgmt_client_forwarder.h"

typedef struct _CMOCK_qeo_mgmt_client_register_forwarder_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_mgmt_client_retcode_t ReturnVal;
  qeo_mgmt_client_ctx_t* Expected_ctx;
  char* Expected_url;
  qeo_mgmt_client_locator_t* Expected_locators;
  u_int32_t Expected_nrOfLocators;
  qeo_mgmt_client_ssl_ctx_cb Expected_ssl_cb;
  void* Expected_cookie;

} CMOCK_qeo_mgmt_client_register_forwarder_CALL_INSTANCE;

typedef struct _CMOCK_qeo_mgmt_client_get_forwarders_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_mgmt_client_retcode_t ReturnVal;
  qeo_mgmt_client_ctx_t* Expected_ctx;
  char* Expected_url;
  qeo_mgmt_client_forwarder_cb Expected_fwd_cb;
  qeo_mgmt_client_forwarder_result_cb Expected_result_cb;
  void* Expected_fwd_cookie;
  qeo_mgmt_client_ssl_ctx_cb Expected_ssl_cb;
  void* Expected_ssl_cookie;

} CMOCK_qeo_mgmt_client_get_forwarders_CALL_INSTANCE;

typedef struct _CMOCK_qeo_mgmt_client_get_forwarders_sync_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_mgmt_client_retcode_t ReturnVal;
  qeo_mgmt_client_ctx_t* Expected_ctx;
  char* Expected_url;
  qeo_mgmt_client_forwarder_cb Expected_fwd_cb;
  void* Expected_fwd_cookie;
  qeo_mgmt_client_ssl_ctx_cb Expected_ssl_cb;
  void* Expected_ssl_cookie;

} CMOCK_qeo_mgmt_client_get_forwarders_sync_CALL_INSTANCE;

typedef struct _CMOCK_qeo_mgmt_client_free_forwarder_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_mgmt_client_retcode_t ReturnVal;
  qeo_mgmt_client_forwarder_t* Expected_forwarder;

} CMOCK_qeo_mgmt_client_free_forwarder_CALL_INSTANCE;

static struct Mockmgmt_client_forwarderInstance
{
  int qeo_mgmt_client_register_forwarder_IgnoreBool;
  qeo_mgmt_client_retcode_t qeo_mgmt_client_register_forwarder_FinalReturn;
  CMOCK_qeo_mgmt_client_register_forwarder_CALLBACK qeo_mgmt_client_register_forwarder_CallbackFunctionPointer;
  int qeo_mgmt_client_register_forwarder_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_mgmt_client_register_forwarder_CallInstance;
  int qeo_mgmt_client_get_forwarders_IgnoreBool;
  qeo_mgmt_client_retcode_t qeo_mgmt_client_get_forwarders_FinalReturn;
  CMOCK_qeo_mgmt_client_get_forwarders_CALLBACK qeo_mgmt_client_get_forwarders_CallbackFunctionPointer;
  int qeo_mgmt_client_get_forwarders_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_mgmt_client_get_forwarders_CallInstance;
  int qeo_mgmt_client_get_forwarders_sync_IgnoreBool;
  qeo_mgmt_client_retcode_t qeo_mgmt_client_get_forwarders_sync_FinalReturn;
  CMOCK_qeo_mgmt_client_get_forwarders_sync_CALLBACK qeo_mgmt_client_get_forwarders_sync_CallbackFunctionPointer;
  int qeo_mgmt_client_get_forwarders_sync_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_mgmt_client_get_forwarders_sync_CallInstance;
  int qeo_mgmt_client_free_forwarder_IgnoreBool;
  qeo_mgmt_client_retcode_t qeo_mgmt_client_free_forwarder_FinalReturn;
  CMOCK_qeo_mgmt_client_free_forwarder_CALLBACK qeo_mgmt_client_free_forwarder_CallbackFunctionPointer;
  int qeo_mgmt_client_free_forwarder_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_mgmt_client_free_forwarder_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmgmt_client_forwarder_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.qeo_mgmt_client_register_forwarder_IgnoreBool)
    Mock.qeo_mgmt_client_register_forwarder_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_mgmt_client_register_forwarder_CallInstance, cmock_line, "Function 'qeo_mgmt_client_register_forwarder' called less times than expected.");
  if (Mock.qeo_mgmt_client_register_forwarder_CallbackFunctionPointer != NULL)
    Mock.qeo_mgmt_client_register_forwarder_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_mgmt_client_get_forwarders_IgnoreBool)
    Mock.qeo_mgmt_client_get_forwarders_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_mgmt_client_get_forwarders_CallInstance, cmock_line, "Function 'qeo_mgmt_client_get_forwarders' called less times than expected.");
  if (Mock.qeo_mgmt_client_get_forwarders_CallbackFunctionPointer != NULL)
    Mock.qeo_mgmt_client_get_forwarders_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_mgmt_client_get_forwarders_sync_IgnoreBool)
    Mock.qeo_mgmt_client_get_forwarders_sync_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_mgmt_client_get_forwarders_sync_CallInstance, cmock_line, "Function 'qeo_mgmt_client_get_forwarders_sync' called less times than expected.");
  if (Mock.qeo_mgmt_client_get_forwarders_sync_CallbackFunctionPointer != NULL)
    Mock.qeo_mgmt_client_get_forwarders_sync_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_mgmt_client_free_forwarder_IgnoreBool)
    Mock.qeo_mgmt_client_free_forwarder_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_mgmt_client_free_forwarder_CallInstance, cmock_line, "Function 'qeo_mgmt_client_free_forwarder' called less times than expected.");
  if (Mock.qeo_mgmt_client_free_forwarder_CallbackFunctionPointer != NULL)
    Mock.qeo_mgmt_client_free_forwarder_CallInstance = CMOCK_GUTS_NONE;
}

void Mockmgmt_client_forwarder_Init(void)
{
  Mockmgmt_client_forwarder_Destroy();
}

void Mockmgmt_client_forwarder_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.qeo_mgmt_client_register_forwarder_CallbackFunctionPointer = NULL;
  Mock.qeo_mgmt_client_register_forwarder_CallbackCalls = 0;
  Mock.qeo_mgmt_client_get_forwarders_CallbackFunctionPointer = NULL;
  Mock.qeo_mgmt_client_get_forwarders_CallbackCalls = 0;
  Mock.qeo_mgmt_client_get_forwarders_sync_CallbackFunctionPointer = NULL;
  Mock.qeo_mgmt_client_get_forwarders_sync_CallbackCalls = 0;
  Mock.qeo_mgmt_client_free_forwarder_CallbackFunctionPointer = NULL;
  Mock.qeo_mgmt_client_free_forwarder_CallbackCalls = 0;
}

qeo_mgmt_client_retcode_t qeo_mgmt_client_register_forwarder(qeo_mgmt_client_ctx_t* ctx, const char* url, qeo_mgmt_client_locator_t* locators, u_int32_t nrOfLocators, qeo_mgmt_client_ssl_ctx_cb ssl_cb, void* cookie)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_mgmt_client_register_forwarder_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_register_forwarder_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_mgmt_client_register_forwarder_CallInstance);
  Mock.qeo_mgmt_client_register_forwarder_CallInstance = CMock_Guts_MemNext(Mock.qeo_mgmt_client_register_forwarder_CallInstance);
  if (Mock.qeo_mgmt_client_register_forwarder_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_mgmt_client_register_forwarder_FinalReturn;
    memcpy(&Mock.qeo_mgmt_client_register_forwarder_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_mgmt_client_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_mgmt_client_register_forwarder_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_mgmt_client_register_forwarder_CallbackFunctionPointer(ctx, url, locators, nrOfLocators, ssl_cb, cookie, Mock.qeo_mgmt_client_register_forwarder_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_mgmt_client_register_forwarder' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ctx), (void*)(ctx), sizeof(qeo_mgmt_client_ctx_t), cmock_line, "Function 'qeo_mgmt_client_register_forwarder' called with unexpected value for argument 'ctx'.");
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_url, url, cmock_line, "Function 'qeo_mgmt_client_register_forwarder' called with unexpected value for argument 'url'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_locators), (void*)(locators), sizeof(qeo_mgmt_client_locator_t), cmock_line, "Function 'qeo_mgmt_client_register_forwarder' called with unexpected value for argument 'locators'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_nrOfLocators), (void*)(&nrOfLocators), sizeof(u_int32_t), cmock_line, "Function 'qeo_mgmt_client_register_forwarder' called with unexpected value for argument 'nrOfLocators'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_ssl_cb), (void*)(&ssl_cb), sizeof(qeo_mgmt_client_ssl_ctx_cb), cmock_line, "Function 'qeo_mgmt_client_register_forwarder' called with unexpected value for argument 'ssl_cb'.");
  UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_cookie, cookie, cmock_line, "Function 'qeo_mgmt_client_register_forwarder' called with unexpected value for argument 'cookie'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_mgmt_client_register_forwarder(CMOCK_qeo_mgmt_client_register_forwarder_CALL_INSTANCE* cmock_call_instance, qeo_mgmt_client_ctx_t* ctx, const char* url, qeo_mgmt_client_locator_t* locators, u_int32_t nrOfLocators, qeo_mgmt_client_ssl_ctx_cb ssl_cb, void* cookie)
{
  cmock_call_instance->Expected_ctx = ctx;
  cmock_call_instance->Expected_url = (char*)url;
  cmock_call_instance->Expected_locators = locators;
  memcpy(&cmock_call_instance->Expected_nrOfLocators, &nrOfLocators, sizeof(u_int32_t));
  memcpy(&cmock_call_instance->Expected_ssl_cb, &ssl_cb, sizeof(qeo_mgmt_client_ssl_ctx_cb));
  cmock_call_instance->Expected_cookie = cookie;
}

void qeo_mgmt_client_register_forwarder_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_mgmt_client_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_mgmt_client_register_forwarder_CALL_INSTANCE));
  CMOCK_qeo_mgmt_client_register_forwarder_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_register_forwarder_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_mgmt_client_register_forwarder_CallInstance = CMock_Guts_MemChain(Mock.qeo_mgmt_client_register_forwarder_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_mgmt_client_register_forwarder_IgnoreBool = (int)1;
}

void qeo_mgmt_client_register_forwarder_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_mgmt_client_ctx_t* ctx, const char* url, qeo_mgmt_client_locator_t* locators, u_int32_t nrOfLocators, qeo_mgmt_client_ssl_ctx_cb ssl_cb, void* cookie, qeo_mgmt_client_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_mgmt_client_register_forwarder_CALL_INSTANCE));
  CMOCK_qeo_mgmt_client_register_forwarder_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_register_forwarder_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_mgmt_client_register_forwarder_CallInstance = CMock_Guts_MemChain(Mock.qeo_mgmt_client_register_forwarder_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_mgmt_client_register_forwarder(cmock_call_instance, ctx, url, locators, nrOfLocators, ssl_cb, cookie);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_mgmt_client_retcode_t));
}

void qeo_mgmt_client_register_forwarder_StubWithCallback(CMOCK_qeo_mgmt_client_register_forwarder_CALLBACK Callback)
{
  Mock.qeo_mgmt_client_register_forwarder_CallbackFunctionPointer = Callback;
}

qeo_mgmt_client_retcode_t qeo_mgmt_client_get_forwarders(qeo_mgmt_client_ctx_t* ctx, const char* url, qeo_mgmt_client_forwarder_cb fwd_cb, qeo_mgmt_client_forwarder_result_cb result_cb, void* fwd_cookie, qeo_mgmt_client_ssl_ctx_cb ssl_cb, void* ssl_cookie)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_mgmt_client_get_forwarders_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_get_forwarders_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_mgmt_client_get_forwarders_CallInstance);
  Mock.qeo_mgmt_client_get_forwarders_CallInstance = CMock_Guts_MemNext(Mock.qeo_mgmt_client_get_forwarders_CallInstance);
  if (Mock.qeo_mgmt_client_get_forwarders_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_mgmt_client_get_forwarders_FinalReturn;
    memcpy(&Mock.qeo_mgmt_client_get_forwarders_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_mgmt_client_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_mgmt_client_get_forwarders_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_mgmt_client_get_forwarders_CallbackFunctionPointer(ctx, url, fwd_cb, result_cb, fwd_cookie, ssl_cb, ssl_cookie, Mock.qeo_mgmt_client_get_forwarders_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_mgmt_client_get_forwarders' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ctx), (void*)(ctx), sizeof(qeo_mgmt_client_ctx_t), cmock_line, "Function 'qeo_mgmt_client_get_forwarders' called with unexpected value for argument 'ctx'.");
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_url, url, cmock_line, "Function 'qeo_mgmt_client_get_forwarders' called with unexpected value for argument 'url'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_fwd_cb), (void*)(&fwd_cb), sizeof(qeo_mgmt_client_forwarder_cb), cmock_line, "Function 'qeo_mgmt_client_get_forwarders' called with unexpected value for argument 'fwd_cb'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_result_cb), (void*)(&result_cb), sizeof(qeo_mgmt_client_forwarder_result_cb), cmock_line, "Function 'qeo_mgmt_client_get_forwarders' called with unexpected value for argument 'result_cb'.");
  UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_fwd_cookie, fwd_cookie, cmock_line, "Function 'qeo_mgmt_client_get_forwarders' called with unexpected value for argument 'fwd_cookie'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_ssl_cb), (void*)(&ssl_cb), sizeof(qeo_mgmt_client_ssl_ctx_cb), cmock_line, "Function 'qeo_mgmt_client_get_forwarders' called with unexpected value for argument 'ssl_cb'.");
  UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_ssl_cookie, ssl_cookie, cmock_line, "Function 'qeo_mgmt_client_get_forwarders' called with unexpected value for argument 'ssl_cookie'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_mgmt_client_get_forwarders(CMOCK_qeo_mgmt_client_get_forwarders_CALL_INSTANCE* cmock_call_instance, qeo_mgmt_client_ctx_t* ctx, const char* url, qeo_mgmt_client_forwarder_cb fwd_cb, qeo_mgmt_client_forwarder_result_cb result_cb, void* fwd_cookie, qeo_mgmt_client_ssl_ctx_cb ssl_cb, void* ssl_cookie)
{
  cmock_call_instance->Expected_ctx = ctx;
  cmock_call_instance->Expected_url = (char*)url;
  memcpy(&cmock_call_instance->Expected_fwd_cb, &fwd_cb, sizeof(qeo_mgmt_client_forwarder_cb));
  memcpy(&cmock_call_instance->Expected_result_cb, &result_cb, sizeof(qeo_mgmt_client_forwarder_result_cb));
  cmock_call_instance->Expected_fwd_cookie = fwd_cookie;
  memcpy(&cmock_call_instance->Expected_ssl_cb, &ssl_cb, sizeof(qeo_mgmt_client_ssl_ctx_cb));
  cmock_call_instance->Expected_ssl_cookie = ssl_cookie;
}

void qeo_mgmt_client_get_forwarders_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_mgmt_client_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_mgmt_client_get_forwarders_CALL_INSTANCE));
  CMOCK_qeo_mgmt_client_get_forwarders_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_get_forwarders_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_mgmt_client_get_forwarders_CallInstance = CMock_Guts_MemChain(Mock.qeo_mgmt_client_get_forwarders_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_mgmt_client_get_forwarders_IgnoreBool = (int)1;
}

void qeo_mgmt_client_get_forwarders_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_mgmt_client_ctx_t* ctx, const char* url, qeo_mgmt_client_forwarder_cb fwd_cb, qeo_mgmt_client_forwarder_result_cb result_cb, void* fwd_cookie, qeo_mgmt_client_ssl_ctx_cb ssl_cb, void* ssl_cookie, qeo_mgmt_client_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_mgmt_client_get_forwarders_CALL_INSTANCE));
  CMOCK_qeo_mgmt_client_get_forwarders_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_get_forwarders_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_mgmt_client_get_forwarders_CallInstance = CMock_Guts_MemChain(Mock.qeo_mgmt_client_get_forwarders_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_mgmt_client_get_forwarders(cmock_call_instance, ctx, url, fwd_cb, result_cb, fwd_cookie, ssl_cb, ssl_cookie);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_mgmt_client_retcode_t));
}

void qeo_mgmt_client_get_forwarders_StubWithCallback(CMOCK_qeo_mgmt_client_get_forwarders_CALLBACK Callback)
{
  Mock.qeo_mgmt_client_get_forwarders_CallbackFunctionPointer = Callback;
}

qeo_mgmt_client_retcode_t qeo_mgmt_client_get_forwarders_sync(qeo_mgmt_client_ctx_t* ctx, const char* url, qeo_mgmt_client_forwarder_cb fwd_cb, void* fwd_cookie, qeo_mgmt_client_ssl_ctx_cb ssl_cb, void* ssl_cookie)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_mgmt_client_get_forwarders_sync_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_get_forwarders_sync_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_mgmt_client_get_forwarders_sync_CallInstance);
  Mock.qeo_mgmt_client_get_forwarders_sync_CallInstance = CMock_Guts_MemNext(Mock.qeo_mgmt_client_get_forwarders_sync_CallInstance);
  if (Mock.qeo_mgmt_client_get_forwarders_sync_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_mgmt_client_get_forwarders_sync_FinalReturn;
    memcpy(&Mock.qeo_mgmt_client_get_forwarders_sync_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_mgmt_client_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_mgmt_client_get_forwarders_sync_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_mgmt_client_get_forwarders_sync_CallbackFunctionPointer(ctx, url, fwd_cb, fwd_cookie, ssl_cb, ssl_cookie, Mock.qeo_mgmt_client_get_forwarders_sync_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_mgmt_client_get_forwarders_sync' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ctx), (void*)(ctx), sizeof(qeo_mgmt_client_ctx_t), cmock_line, "Function 'qeo_mgmt_client_get_forwarders_sync' called with unexpected value for argument 'ctx'.");
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_url, url, cmock_line, "Function 'qeo_mgmt_client_get_forwarders_sync' called with unexpected value for argument 'url'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_fwd_cb), (void*)(&fwd_cb), sizeof(qeo_mgmt_client_forwarder_cb), cmock_line, "Function 'qeo_mgmt_client_get_forwarders_sync' called with unexpected value for argument 'fwd_cb'.");
  UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_fwd_cookie, fwd_cookie, cmock_line, "Function 'qeo_mgmt_client_get_forwarders_sync' called with unexpected value for argument 'fwd_cookie'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_ssl_cb), (void*)(&ssl_cb), sizeof(qeo_mgmt_client_ssl_ctx_cb), cmock_line, "Function 'qeo_mgmt_client_get_forwarders_sync' called with unexpected value for argument 'ssl_cb'.");
  UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_ssl_cookie, ssl_cookie, cmock_line, "Function 'qeo_mgmt_client_get_forwarders_sync' called with unexpected value for argument 'ssl_cookie'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_mgmt_client_get_forwarders_sync(CMOCK_qeo_mgmt_client_get_forwarders_sync_CALL_INSTANCE* cmock_call_instance, qeo_mgmt_client_ctx_t* ctx, const char* url, qeo_mgmt_client_forwarder_cb fwd_cb, void* fwd_cookie, qeo_mgmt_client_ssl_ctx_cb ssl_cb, void* ssl_cookie)
{
  cmock_call_instance->Expected_ctx = ctx;
  cmock_call_instance->Expected_url = (char*)url;
  memcpy(&cmock_call_instance->Expected_fwd_cb, &fwd_cb, sizeof(qeo_mgmt_client_forwarder_cb));
  cmock_call_instance->Expected_fwd_cookie = fwd_cookie;
  memcpy(&cmock_call_instance->Expected_ssl_cb, &ssl_cb, sizeof(qeo_mgmt_client_ssl_ctx_cb));
  cmock_call_instance->Expected_ssl_cookie = ssl_cookie;
}

void qeo_mgmt_client_get_forwarders_sync_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_mgmt_client_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_mgmt_client_get_forwarders_sync_CALL_INSTANCE));
  CMOCK_qeo_mgmt_client_get_forwarders_sync_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_get_forwarders_sync_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_mgmt_client_get_forwarders_sync_CallInstance = CMock_Guts_MemChain(Mock.qeo_mgmt_client_get_forwarders_sync_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_mgmt_client_get_forwarders_sync_IgnoreBool = (int)1;
}

void qeo_mgmt_client_get_forwarders_sync_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_mgmt_client_ctx_t* ctx, const char* url, qeo_mgmt_client_forwarder_cb fwd_cb, void* fwd_cookie, qeo_mgmt_client_ssl_ctx_cb ssl_cb, void* ssl_cookie, qeo_mgmt_client_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_mgmt_client_get_forwarders_sync_CALL_INSTANCE));
  CMOCK_qeo_mgmt_client_get_forwarders_sync_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_get_forwarders_sync_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_mgmt_client_get_forwarders_sync_CallInstance = CMock_Guts_MemChain(Mock.qeo_mgmt_client_get_forwarders_sync_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_mgmt_client_get_forwarders_sync(cmock_call_instance, ctx, url, fwd_cb, fwd_cookie, ssl_cb, ssl_cookie);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_mgmt_client_retcode_t));
}

void qeo_mgmt_client_get_forwarders_sync_StubWithCallback(CMOCK_qeo_mgmt_client_get_forwarders_sync_CALLBACK Callback)
{
  Mock.qeo_mgmt_client_get_forwarders_sync_CallbackFunctionPointer = Callback;
}

qeo_mgmt_client_retcode_t qeo_mgmt_client_free_forwarder(qeo_mgmt_client_forwarder_t* forwarder)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_mgmt_client_free_forwarder_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_free_forwarder_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_mgmt_client_free_forwarder_CallInstance);
  Mock.qeo_mgmt_client_free_forwarder_CallInstance = CMock_Guts_MemNext(Mock.qeo_mgmt_client_free_forwarder_CallInstance);
  if (Mock.qeo_mgmt_client_free_forwarder_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_mgmt_client_free_forwarder_FinalReturn;
    memcpy(&Mock.qeo_mgmt_client_free_forwarder_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_mgmt_client_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_mgmt_client_free_forwarder_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_mgmt_client_free_forwarder_CallbackFunctionPointer(forwarder, Mock.qeo_mgmt_client_free_forwarder_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_mgmt_client_free_forwarder' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_forwarder), (void*)(forwarder), sizeof(qeo_mgmt_client_forwarder_t), cmock_line, "Function 'qeo_mgmt_client_free_forwarder' called with unexpected value for argument 'forwarder'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_mgmt_client_free_forwarder(CMOCK_qeo_mgmt_client_free_forwarder_CALL_INSTANCE* cmock_call_instance, qeo_mgmt_client_forwarder_t* forwarder)
{
  cmock_call_instance->Expected_forwarder = forwarder;
}

void qeo_mgmt_client_free_forwarder_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_mgmt_client_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_mgmt_client_free_forwarder_CALL_INSTANCE));
  CMOCK_qeo_mgmt_client_free_forwarder_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_free_forwarder_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_mgmt_client_free_forwarder_CallInstance = CMock_Guts_MemChain(Mock.qeo_mgmt_client_free_forwarder_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_mgmt_client_free_forwarder_IgnoreBool = (int)1;
}

void qeo_mgmt_client_free_forwarder_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_mgmt_client_forwarder_t* forwarder, qeo_mgmt_client_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_mgmt_client_free_forwarder_CALL_INSTANCE));
  CMOCK_qeo_mgmt_client_free_forwarder_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_free_forwarder_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_mgmt_client_free_forwarder_CallInstance = CMock_Guts_MemChain(Mock.qeo_mgmt_client_free_forwarder_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_mgmt_client_free_forwarder(cmock_call_instance, forwarder);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_mgmt_client_retcode_t));
}

void qeo_mgmt_client_free_forwarder_StubWithCallback(CMOCK_qeo_mgmt_client_free_forwarder_CALLBACK Callback)
{
  Mock.qeo_mgmt_client_free_forwarder_CallbackFunctionPointer = Callback;
}

