/*
 * Copyright (c) 2014 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKDDS_DCPS_H
#define _MOCKDDS_DCPS_H

#include "unity.h"
#include "dds/dds_dcps.h"

void Mockdds_dcps_Init(void);
void Mockdds_dcps_Destroy(void);
void Mockdds_dcps_Verify(void);





#endif
