/*
 * Copyright (c) 2014 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#define NO_TEST_ASSERT_EQUAL_MEMORY_MESSAGE
#include "unity.h"
#include "cmock.h"
#include "Mockremote_registration.h"

typedef struct _CMOCK_qeo_remote_registration_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_remote_registration_init_cfg_t* Expected_cfg;

} CMOCK_qeo_remote_registration_init_CALL_INSTANCE;

typedef struct _CMOCK_qeo_remote_registration_destroy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_qeo_remote_registration_destroy_CALL_INSTANCE;

typedef struct _CMOCK_qeo_remote_registration_construct_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_remote_registration_cfg_t* Expected_cfg;
  qeo_remote_registration_hndl_t* Expected_remote_reg;

} CMOCK_qeo_remote_registration_construct_CALL_INSTANCE;

typedef struct _CMOCK_qeo_remote_registration_get_user_data_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_remote_registration_hndl_t Expected_remote_reg;
  uintptr_t* Expected_user_data;

} CMOCK_qeo_remote_registration_get_user_data_CALL_INSTANCE;

typedef struct _CMOCK_qeo_remote_registration_destruct_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_remote_registration_hndl_t* Expected_remote_reg;

} CMOCK_qeo_remote_registration_destruct_CALL_INSTANCE;

typedef struct _CMOCK_qeo_remote_registration_start_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_remote_registration_hndl_t Expected_remote_reg;

} CMOCK_qeo_remote_registration_start_CALL_INSTANCE;

typedef struct _CMOCK_qeo_remote_registration_update_registration_status_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_remote_registration_hndl_t Expected_remote_reg;
  qeo_remote_registration_status_t Expected_status;
  qeo_remote_registration_failure_reason_t Expected_reason;

} CMOCK_qeo_remote_registration_update_registration_status_CALL_INSTANCE;

typedef struct _CMOCK_qeo_remote_registration_enable_using_new_registration_credentials_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_remote_registration_hndl_t Expected_remote_reg;

} CMOCK_qeo_remote_registration_enable_using_new_registration_credentials_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_remote_registration_init_cond_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_qeocore_remote_registration_init_cond_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_remote_registration_set_key_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  EVP_PKEY* Expected_key;

} CMOCK_qeocore_remote_registration_set_key_CALL_INSTANCE;

static struct Mockremote_registrationInstance
{
  int qeo_remote_registration_init_IgnoreBool;
  qeo_retcode_t qeo_remote_registration_init_FinalReturn;
  CMOCK_qeo_remote_registration_init_CALLBACK qeo_remote_registration_init_CallbackFunctionPointer;
  int qeo_remote_registration_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_remote_registration_init_CallInstance;
  int qeo_remote_registration_destroy_IgnoreBool;
  CMOCK_qeo_remote_registration_destroy_CALLBACK qeo_remote_registration_destroy_CallbackFunctionPointer;
  int qeo_remote_registration_destroy_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_remote_registration_destroy_CallInstance;
  int qeo_remote_registration_construct_IgnoreBool;
  qeo_retcode_t qeo_remote_registration_construct_FinalReturn;
  CMOCK_qeo_remote_registration_construct_CALLBACK qeo_remote_registration_construct_CallbackFunctionPointer;
  int qeo_remote_registration_construct_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_remote_registration_construct_CallInstance;
  int qeo_remote_registration_get_user_data_IgnoreBool;
  qeo_retcode_t qeo_remote_registration_get_user_data_FinalReturn;
  CMOCK_qeo_remote_registration_get_user_data_CALLBACK qeo_remote_registration_get_user_data_CallbackFunctionPointer;
  int qeo_remote_registration_get_user_data_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_remote_registration_get_user_data_CallInstance;
  int qeo_remote_registration_destruct_IgnoreBool;
  qeo_retcode_t qeo_remote_registration_destruct_FinalReturn;
  CMOCK_qeo_remote_registration_destruct_CALLBACK qeo_remote_registration_destruct_CallbackFunctionPointer;
  int qeo_remote_registration_destruct_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_remote_registration_destruct_CallInstance;
  int qeo_remote_registration_start_IgnoreBool;
  qeo_retcode_t qeo_remote_registration_start_FinalReturn;
  CMOCK_qeo_remote_registration_start_CALLBACK qeo_remote_registration_start_CallbackFunctionPointer;
  int qeo_remote_registration_start_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_remote_registration_start_CallInstance;
  int qeo_remote_registration_update_registration_status_IgnoreBool;
  qeo_retcode_t qeo_remote_registration_update_registration_status_FinalReturn;
  CMOCK_qeo_remote_registration_update_registration_status_CALLBACK qeo_remote_registration_update_registration_status_CallbackFunctionPointer;
  int qeo_remote_registration_update_registration_status_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_remote_registration_update_registration_status_CallInstance;
  int qeo_remote_registration_enable_using_new_registration_credentials_IgnoreBool;
  qeo_retcode_t qeo_remote_registration_enable_using_new_registration_credentials_FinalReturn;
  CMOCK_qeo_remote_registration_enable_using_new_registration_credentials_CALLBACK qeo_remote_registration_enable_using_new_registration_credentials_CallbackFunctionPointer;
  int qeo_remote_registration_enable_using_new_registration_credentials_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_remote_registration_enable_using_new_registration_credentials_CallInstance;
  int qeocore_remote_registration_init_cond_IgnoreBool;
  CMOCK_qeocore_remote_registration_init_cond_CALLBACK qeocore_remote_registration_init_cond_CallbackFunctionPointer;
  int qeocore_remote_registration_init_cond_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_remote_registration_init_cond_CallInstance;
  int qeocore_remote_registration_set_key_IgnoreBool;
  CMOCK_qeocore_remote_registration_set_key_CALLBACK qeocore_remote_registration_set_key_CallbackFunctionPointer;
  int qeocore_remote_registration_set_key_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_remote_registration_set_key_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockremote_registration_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.qeo_remote_registration_init_IgnoreBool)
    Mock.qeo_remote_registration_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_remote_registration_init_CallInstance, cmock_line, "Function 'qeo_remote_registration_init' called less times than expected.");
  if (Mock.qeo_remote_registration_init_CallbackFunctionPointer != NULL)
    Mock.qeo_remote_registration_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_remote_registration_destroy_IgnoreBool)
    Mock.qeo_remote_registration_destroy_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_remote_registration_destroy_CallInstance, cmock_line, "Function 'qeo_remote_registration_destroy' called less times than expected.");
  if (Mock.qeo_remote_registration_destroy_CallbackFunctionPointer != NULL)
    Mock.qeo_remote_registration_destroy_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_remote_registration_construct_IgnoreBool)
    Mock.qeo_remote_registration_construct_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_remote_registration_construct_CallInstance, cmock_line, "Function 'qeo_remote_registration_construct' called less times than expected.");
  if (Mock.qeo_remote_registration_construct_CallbackFunctionPointer != NULL)
    Mock.qeo_remote_registration_construct_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_remote_registration_get_user_data_IgnoreBool)
    Mock.qeo_remote_registration_get_user_data_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_remote_registration_get_user_data_CallInstance, cmock_line, "Function 'qeo_remote_registration_get_user_data' called less times than expected.");
  if (Mock.qeo_remote_registration_get_user_data_CallbackFunctionPointer != NULL)
    Mock.qeo_remote_registration_get_user_data_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_remote_registration_destruct_IgnoreBool)
    Mock.qeo_remote_registration_destruct_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_remote_registration_destruct_CallInstance, cmock_line, "Function 'qeo_remote_registration_destruct' called less times than expected.");
  if (Mock.qeo_remote_registration_destruct_CallbackFunctionPointer != NULL)
    Mock.qeo_remote_registration_destruct_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_remote_registration_start_IgnoreBool)
    Mock.qeo_remote_registration_start_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_remote_registration_start_CallInstance, cmock_line, "Function 'qeo_remote_registration_start' called less times than expected.");
  if (Mock.qeo_remote_registration_start_CallbackFunctionPointer != NULL)
    Mock.qeo_remote_registration_start_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_remote_registration_update_registration_status_IgnoreBool)
    Mock.qeo_remote_registration_update_registration_status_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_remote_registration_update_registration_status_CallInstance, cmock_line, "Function 'qeo_remote_registration_update_registration_status' called less times than expected.");
  if (Mock.qeo_remote_registration_update_registration_status_CallbackFunctionPointer != NULL)
    Mock.qeo_remote_registration_update_registration_status_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_remote_registration_enable_using_new_registration_credentials_IgnoreBool)
    Mock.qeo_remote_registration_enable_using_new_registration_credentials_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_remote_registration_enable_using_new_registration_credentials_CallInstance, cmock_line, "Function 'qeo_remote_registration_enable_using_new_registration_credentials' called less times than expected.");
  if (Mock.qeo_remote_registration_enable_using_new_registration_credentials_CallbackFunctionPointer != NULL)
    Mock.qeo_remote_registration_enable_using_new_registration_credentials_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_remote_registration_init_cond_IgnoreBool)
    Mock.qeocore_remote_registration_init_cond_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_remote_registration_init_cond_CallInstance, cmock_line, "Function 'qeocore_remote_registration_init_cond' called less times than expected.");
  if (Mock.qeocore_remote_registration_init_cond_CallbackFunctionPointer != NULL)
    Mock.qeocore_remote_registration_init_cond_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_remote_registration_set_key_IgnoreBool)
    Mock.qeocore_remote_registration_set_key_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_remote_registration_set_key_CallInstance, cmock_line, "Function 'qeocore_remote_registration_set_key' called less times than expected.");
  if (Mock.qeocore_remote_registration_set_key_CallbackFunctionPointer != NULL)
    Mock.qeocore_remote_registration_set_key_CallInstance = CMOCK_GUTS_NONE;
}

void Mockremote_registration_Init(void)
{
  Mockremote_registration_Destroy();
}

void Mockremote_registration_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.qeo_remote_registration_init_CallbackFunctionPointer = NULL;
  Mock.qeo_remote_registration_init_CallbackCalls = 0;
  Mock.qeo_remote_registration_destroy_CallbackFunctionPointer = NULL;
  Mock.qeo_remote_registration_destroy_CallbackCalls = 0;
  Mock.qeo_remote_registration_construct_CallbackFunctionPointer = NULL;
  Mock.qeo_remote_registration_construct_CallbackCalls = 0;
  Mock.qeo_remote_registration_get_user_data_CallbackFunctionPointer = NULL;
  Mock.qeo_remote_registration_get_user_data_CallbackCalls = 0;
  Mock.qeo_remote_registration_destruct_CallbackFunctionPointer = NULL;
  Mock.qeo_remote_registration_destruct_CallbackCalls = 0;
  Mock.qeo_remote_registration_start_CallbackFunctionPointer = NULL;
  Mock.qeo_remote_registration_start_CallbackCalls = 0;
  Mock.qeo_remote_registration_update_registration_status_CallbackFunctionPointer = NULL;
  Mock.qeo_remote_registration_update_registration_status_CallbackCalls = 0;
  Mock.qeo_remote_registration_enable_using_new_registration_credentials_CallbackFunctionPointer = NULL;
  Mock.qeo_remote_registration_enable_using_new_registration_credentials_CallbackCalls = 0;
  Mock.qeocore_remote_registration_init_cond_CallbackFunctionPointer = NULL;
  Mock.qeocore_remote_registration_init_cond_CallbackCalls = 0;
  Mock.qeocore_remote_registration_set_key_CallbackFunctionPointer = NULL;
  Mock.qeocore_remote_registration_set_key_CallbackCalls = 0;
}

qeo_retcode_t qeo_remote_registration_init(const qeo_remote_registration_init_cfg_t* cfg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_remote_registration_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_remote_registration_init_CallInstance);
  Mock.qeo_remote_registration_init_CallInstance = CMock_Guts_MemNext(Mock.qeo_remote_registration_init_CallInstance);
  if (Mock.qeo_remote_registration_init_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_remote_registration_init_FinalReturn;
    memcpy(&Mock.qeo_remote_registration_init_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_remote_registration_init_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_remote_registration_init_CallbackFunctionPointer(cfg, Mock.qeo_remote_registration_init_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_remote_registration_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cfg), (void*)(cfg), sizeof(qeo_remote_registration_init_cfg_t), cmock_line, "Function 'qeo_remote_registration_init' called with unexpected value for argument 'cfg'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_remote_registration_init(CMOCK_qeo_remote_registration_init_CALL_INSTANCE* cmock_call_instance, const qeo_remote_registration_init_cfg_t* cfg)
{
  cmock_call_instance->Expected_cfg = (qeo_remote_registration_init_cfg_t*)cfg;
}

void qeo_remote_registration_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_remote_registration_init_CALL_INSTANCE));
  CMOCK_qeo_remote_registration_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_remote_registration_init_CallInstance = CMock_Guts_MemChain(Mock.qeo_remote_registration_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_remote_registration_init_IgnoreBool = (int)1;
}

void qeo_remote_registration_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const qeo_remote_registration_init_cfg_t* cfg, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_remote_registration_init_CALL_INSTANCE));
  CMOCK_qeo_remote_registration_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_remote_registration_init_CallInstance = CMock_Guts_MemChain(Mock.qeo_remote_registration_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_remote_registration_init(cmock_call_instance, cfg);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeo_remote_registration_init_StubWithCallback(CMOCK_qeo_remote_registration_init_CALLBACK Callback)
{
  Mock.qeo_remote_registration_init_CallbackFunctionPointer = Callback;
}

void qeo_remote_registration_destroy(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_remote_registration_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_remote_registration_destroy_CallInstance);
  Mock.qeo_remote_registration_destroy_CallInstance = CMock_Guts_MemNext(Mock.qeo_remote_registration_destroy_CallInstance);
  if (Mock.qeo_remote_registration_destroy_IgnoreBool)
  {
    return;
  }
  if (Mock.qeo_remote_registration_destroy_CallbackFunctionPointer != NULL)
  {
    Mock.qeo_remote_registration_destroy_CallbackFunctionPointer(Mock.qeo_remote_registration_destroy_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_remote_registration_destroy' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void qeo_remote_registration_destroy_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  Mock.qeo_remote_registration_destroy_IgnoreBool = (int)1;
}

void qeo_remote_registration_destroy_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_remote_registration_destroy_CALL_INSTANCE));
  CMOCK_qeo_remote_registration_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_remote_registration_destroy_CallInstance = CMock_Guts_MemChain(Mock.qeo_remote_registration_destroy_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void qeo_remote_registration_destroy_StubWithCallback(CMOCK_qeo_remote_registration_destroy_CALLBACK Callback)
{
  Mock.qeo_remote_registration_destroy_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeo_remote_registration_construct(const qeo_remote_registration_cfg_t* cfg, qeo_remote_registration_hndl_t* remote_reg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_remote_registration_construct_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_construct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_remote_registration_construct_CallInstance);
  Mock.qeo_remote_registration_construct_CallInstance = CMock_Guts_MemNext(Mock.qeo_remote_registration_construct_CallInstance);
  if (Mock.qeo_remote_registration_construct_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_remote_registration_construct_FinalReturn;
    memcpy(&Mock.qeo_remote_registration_construct_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_remote_registration_construct_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_remote_registration_construct_CallbackFunctionPointer(cfg, remote_reg, Mock.qeo_remote_registration_construct_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_remote_registration_construct' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cfg), (void*)(cfg), sizeof(qeo_remote_registration_cfg_t), cmock_line, "Function 'qeo_remote_registration_construct' called with unexpected value for argument 'cfg'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_remote_reg), (void*)(remote_reg), sizeof(qeo_remote_registration_hndl_t), cmock_line, "Function 'qeo_remote_registration_construct' called with unexpected value for argument 'remote_reg'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_remote_registration_construct(CMOCK_qeo_remote_registration_construct_CALL_INSTANCE* cmock_call_instance, const qeo_remote_registration_cfg_t* cfg, qeo_remote_registration_hndl_t* remote_reg)
{
  cmock_call_instance->Expected_cfg = (qeo_remote_registration_cfg_t*)cfg;
  cmock_call_instance->Expected_remote_reg = remote_reg;
}

void qeo_remote_registration_construct_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_remote_registration_construct_CALL_INSTANCE));
  CMOCK_qeo_remote_registration_construct_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_construct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_remote_registration_construct_CallInstance = CMock_Guts_MemChain(Mock.qeo_remote_registration_construct_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_remote_registration_construct_IgnoreBool = (int)1;
}

void qeo_remote_registration_construct_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const qeo_remote_registration_cfg_t* cfg, qeo_remote_registration_hndl_t* remote_reg, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_remote_registration_construct_CALL_INSTANCE));
  CMOCK_qeo_remote_registration_construct_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_construct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_remote_registration_construct_CallInstance = CMock_Guts_MemChain(Mock.qeo_remote_registration_construct_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_remote_registration_construct(cmock_call_instance, cfg, remote_reg);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeo_remote_registration_construct_StubWithCallback(CMOCK_qeo_remote_registration_construct_CALLBACK Callback)
{
  Mock.qeo_remote_registration_construct_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeo_remote_registration_get_user_data(qeo_remote_registration_hndl_t remote_reg, uintptr_t* user_data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_remote_registration_get_user_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_get_user_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_remote_registration_get_user_data_CallInstance);
  Mock.qeo_remote_registration_get_user_data_CallInstance = CMock_Guts_MemNext(Mock.qeo_remote_registration_get_user_data_CallInstance);
  if (Mock.qeo_remote_registration_get_user_data_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_remote_registration_get_user_data_FinalReturn;
    memcpy(&Mock.qeo_remote_registration_get_user_data_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_remote_registration_get_user_data_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_remote_registration_get_user_data_CallbackFunctionPointer(remote_reg, user_data, Mock.qeo_remote_registration_get_user_data_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_remote_registration_get_user_data' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_remote_reg), (void*)(&remote_reg), sizeof(qeo_remote_registration_hndl_t), cmock_line, "Function 'qeo_remote_registration_get_user_data' called with unexpected value for argument 'remote_reg'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_user_data), (void*)(user_data), sizeof(uintptr_t), cmock_line, "Function 'qeo_remote_registration_get_user_data' called with unexpected value for argument 'user_data'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_remote_registration_get_user_data(CMOCK_qeo_remote_registration_get_user_data_CALL_INSTANCE* cmock_call_instance, qeo_remote_registration_hndl_t remote_reg, uintptr_t* user_data)
{
  memcpy(&cmock_call_instance->Expected_remote_reg, &remote_reg, sizeof(qeo_remote_registration_hndl_t));
  cmock_call_instance->Expected_user_data = user_data;
}

void qeo_remote_registration_get_user_data_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_remote_registration_get_user_data_CALL_INSTANCE));
  CMOCK_qeo_remote_registration_get_user_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_get_user_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_remote_registration_get_user_data_CallInstance = CMock_Guts_MemChain(Mock.qeo_remote_registration_get_user_data_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_remote_registration_get_user_data_IgnoreBool = (int)1;
}

void qeo_remote_registration_get_user_data_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_remote_registration_hndl_t remote_reg, uintptr_t* user_data, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_remote_registration_get_user_data_CALL_INSTANCE));
  CMOCK_qeo_remote_registration_get_user_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_get_user_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_remote_registration_get_user_data_CallInstance = CMock_Guts_MemChain(Mock.qeo_remote_registration_get_user_data_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_remote_registration_get_user_data(cmock_call_instance, remote_reg, user_data);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeo_remote_registration_get_user_data_StubWithCallback(CMOCK_qeo_remote_registration_get_user_data_CALLBACK Callback)
{
  Mock.qeo_remote_registration_get_user_data_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeo_remote_registration_destruct(qeo_remote_registration_hndl_t* remote_reg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_remote_registration_destruct_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_destruct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_remote_registration_destruct_CallInstance);
  Mock.qeo_remote_registration_destruct_CallInstance = CMock_Guts_MemNext(Mock.qeo_remote_registration_destruct_CallInstance);
  if (Mock.qeo_remote_registration_destruct_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_remote_registration_destruct_FinalReturn;
    memcpy(&Mock.qeo_remote_registration_destruct_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_remote_registration_destruct_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_remote_registration_destruct_CallbackFunctionPointer(remote_reg, Mock.qeo_remote_registration_destruct_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_remote_registration_destruct' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_remote_reg), (void*)(remote_reg), sizeof(qeo_remote_registration_hndl_t), cmock_line, "Function 'qeo_remote_registration_destruct' called with unexpected value for argument 'remote_reg'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_remote_registration_destruct(CMOCK_qeo_remote_registration_destruct_CALL_INSTANCE* cmock_call_instance, qeo_remote_registration_hndl_t* remote_reg)
{
  cmock_call_instance->Expected_remote_reg = remote_reg;
}

void qeo_remote_registration_destruct_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_remote_registration_destruct_CALL_INSTANCE));
  CMOCK_qeo_remote_registration_destruct_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_destruct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_remote_registration_destruct_CallInstance = CMock_Guts_MemChain(Mock.qeo_remote_registration_destruct_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_remote_registration_destruct_IgnoreBool = (int)1;
}

void qeo_remote_registration_destruct_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_remote_registration_hndl_t* remote_reg, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_remote_registration_destruct_CALL_INSTANCE));
  CMOCK_qeo_remote_registration_destruct_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_destruct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_remote_registration_destruct_CallInstance = CMock_Guts_MemChain(Mock.qeo_remote_registration_destruct_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_remote_registration_destruct(cmock_call_instance, remote_reg);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeo_remote_registration_destruct_StubWithCallback(CMOCK_qeo_remote_registration_destruct_CALLBACK Callback)
{
  Mock.qeo_remote_registration_destruct_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeo_remote_registration_start(qeo_remote_registration_hndl_t remote_reg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_remote_registration_start_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_remote_registration_start_CallInstance);
  Mock.qeo_remote_registration_start_CallInstance = CMock_Guts_MemNext(Mock.qeo_remote_registration_start_CallInstance);
  if (Mock.qeo_remote_registration_start_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_remote_registration_start_FinalReturn;
    memcpy(&Mock.qeo_remote_registration_start_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_remote_registration_start_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_remote_registration_start_CallbackFunctionPointer(remote_reg, Mock.qeo_remote_registration_start_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_remote_registration_start' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_remote_reg), (void*)(&remote_reg), sizeof(qeo_remote_registration_hndl_t), cmock_line, "Function 'qeo_remote_registration_start' called with unexpected value for argument 'remote_reg'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_remote_registration_start(CMOCK_qeo_remote_registration_start_CALL_INSTANCE* cmock_call_instance, qeo_remote_registration_hndl_t remote_reg)
{
  memcpy(&cmock_call_instance->Expected_remote_reg, &remote_reg, sizeof(qeo_remote_registration_hndl_t));
}

void qeo_remote_registration_start_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_remote_registration_start_CALL_INSTANCE));
  CMOCK_qeo_remote_registration_start_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_remote_registration_start_CallInstance = CMock_Guts_MemChain(Mock.qeo_remote_registration_start_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_remote_registration_start_IgnoreBool = (int)1;
}

void qeo_remote_registration_start_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_remote_registration_hndl_t remote_reg, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_remote_registration_start_CALL_INSTANCE));
  CMOCK_qeo_remote_registration_start_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_remote_registration_start_CallInstance = CMock_Guts_MemChain(Mock.qeo_remote_registration_start_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_remote_registration_start(cmock_call_instance, remote_reg);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeo_remote_registration_start_StubWithCallback(CMOCK_qeo_remote_registration_start_CALLBACK Callback)
{
  Mock.qeo_remote_registration_start_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeo_remote_registration_update_registration_status(qeo_remote_registration_hndl_t remote_reg, qeo_remote_registration_status_t status, qeo_remote_registration_failure_reason_t reason)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_remote_registration_update_registration_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_update_registration_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_remote_registration_update_registration_status_CallInstance);
  Mock.qeo_remote_registration_update_registration_status_CallInstance = CMock_Guts_MemNext(Mock.qeo_remote_registration_update_registration_status_CallInstance);
  if (Mock.qeo_remote_registration_update_registration_status_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_remote_registration_update_registration_status_FinalReturn;
    memcpy(&Mock.qeo_remote_registration_update_registration_status_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_remote_registration_update_registration_status_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_remote_registration_update_registration_status_CallbackFunctionPointer(remote_reg, status, reason, Mock.qeo_remote_registration_update_registration_status_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_remote_registration_update_registration_status' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_remote_reg), (void*)(&remote_reg), sizeof(qeo_remote_registration_hndl_t), cmock_line, "Function 'qeo_remote_registration_update_registration_status' called with unexpected value for argument 'remote_reg'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_status), (void*)(&status), sizeof(qeo_remote_registration_status_t), cmock_line, "Function 'qeo_remote_registration_update_registration_status' called with unexpected value for argument 'status'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_reason), (void*)(&reason), sizeof(qeo_remote_registration_failure_reason_t), cmock_line, "Function 'qeo_remote_registration_update_registration_status' called with unexpected value for argument 'reason'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_remote_registration_update_registration_status(CMOCK_qeo_remote_registration_update_registration_status_CALL_INSTANCE* cmock_call_instance, qeo_remote_registration_hndl_t remote_reg, qeo_remote_registration_status_t status, qeo_remote_registration_failure_reason_t reason)
{
  memcpy(&cmock_call_instance->Expected_remote_reg, &remote_reg, sizeof(qeo_remote_registration_hndl_t));
  memcpy(&cmock_call_instance->Expected_status, &status, sizeof(qeo_remote_registration_status_t));
  memcpy(&cmock_call_instance->Expected_reason, &reason, sizeof(qeo_remote_registration_failure_reason_t));
}

void qeo_remote_registration_update_registration_status_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_remote_registration_update_registration_status_CALL_INSTANCE));
  CMOCK_qeo_remote_registration_update_registration_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_update_registration_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_remote_registration_update_registration_status_CallInstance = CMock_Guts_MemChain(Mock.qeo_remote_registration_update_registration_status_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_remote_registration_update_registration_status_IgnoreBool = (int)1;
}

void qeo_remote_registration_update_registration_status_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_remote_registration_hndl_t remote_reg, qeo_remote_registration_status_t status, qeo_remote_registration_failure_reason_t reason, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_remote_registration_update_registration_status_CALL_INSTANCE));
  CMOCK_qeo_remote_registration_update_registration_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_update_registration_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_remote_registration_update_registration_status_CallInstance = CMock_Guts_MemChain(Mock.qeo_remote_registration_update_registration_status_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_remote_registration_update_registration_status(cmock_call_instance, remote_reg, status, reason);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeo_remote_registration_update_registration_status_StubWithCallback(CMOCK_qeo_remote_registration_update_registration_status_CALLBACK Callback)
{
  Mock.qeo_remote_registration_update_registration_status_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeo_remote_registration_enable_using_new_registration_credentials(qeo_remote_registration_hndl_t remote_reg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_remote_registration_enable_using_new_registration_credentials_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_enable_using_new_registration_credentials_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_remote_registration_enable_using_new_registration_credentials_CallInstance);
  Mock.qeo_remote_registration_enable_using_new_registration_credentials_CallInstance = CMock_Guts_MemNext(Mock.qeo_remote_registration_enable_using_new_registration_credentials_CallInstance);
  if (Mock.qeo_remote_registration_enable_using_new_registration_credentials_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_remote_registration_enable_using_new_registration_credentials_FinalReturn;
    memcpy(&Mock.qeo_remote_registration_enable_using_new_registration_credentials_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_remote_registration_enable_using_new_registration_credentials_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_remote_registration_enable_using_new_registration_credentials_CallbackFunctionPointer(remote_reg, Mock.qeo_remote_registration_enable_using_new_registration_credentials_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_remote_registration_enable_using_new_registration_credentials' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_remote_reg), (void*)(&remote_reg), sizeof(qeo_remote_registration_hndl_t), cmock_line, "Function 'qeo_remote_registration_enable_using_new_registration_credentials' called with unexpected value for argument 'remote_reg'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_remote_registration_enable_using_new_registration_credentials(CMOCK_qeo_remote_registration_enable_using_new_registration_credentials_CALL_INSTANCE* cmock_call_instance, qeo_remote_registration_hndl_t remote_reg)
{
  memcpy(&cmock_call_instance->Expected_remote_reg, &remote_reg, sizeof(qeo_remote_registration_hndl_t));
}

void qeo_remote_registration_enable_using_new_registration_credentials_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_remote_registration_enable_using_new_registration_credentials_CALL_INSTANCE));
  CMOCK_qeo_remote_registration_enable_using_new_registration_credentials_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_enable_using_new_registration_credentials_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_remote_registration_enable_using_new_registration_credentials_CallInstance = CMock_Guts_MemChain(Mock.qeo_remote_registration_enable_using_new_registration_credentials_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_remote_registration_enable_using_new_registration_credentials_IgnoreBool = (int)1;
}

void qeo_remote_registration_enable_using_new_registration_credentials_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_remote_registration_hndl_t remote_reg, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_remote_registration_enable_using_new_registration_credentials_CALL_INSTANCE));
  CMOCK_qeo_remote_registration_enable_using_new_registration_credentials_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_remote_registration_enable_using_new_registration_credentials_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_remote_registration_enable_using_new_registration_credentials_CallInstance = CMock_Guts_MemChain(Mock.qeo_remote_registration_enable_using_new_registration_credentials_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_remote_registration_enable_using_new_registration_credentials(cmock_call_instance, remote_reg);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeo_remote_registration_enable_using_new_registration_credentials_StubWithCallback(CMOCK_qeo_remote_registration_enable_using_new_registration_credentials_CALLBACK Callback)
{
  Mock.qeo_remote_registration_enable_using_new_registration_credentials_CallbackFunctionPointer = Callback;
}

void qeocore_remote_registration_init_cond(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_remote_registration_init_cond_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_remote_registration_init_cond_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_remote_registration_init_cond_CallInstance);
  Mock.qeocore_remote_registration_init_cond_CallInstance = CMock_Guts_MemNext(Mock.qeocore_remote_registration_init_cond_CallInstance);
  if (Mock.qeocore_remote_registration_init_cond_IgnoreBool)
  {
    return;
  }
  if (Mock.qeocore_remote_registration_init_cond_CallbackFunctionPointer != NULL)
  {
    Mock.qeocore_remote_registration_init_cond_CallbackFunctionPointer(Mock.qeocore_remote_registration_init_cond_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_remote_registration_init_cond' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void qeocore_remote_registration_init_cond_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  Mock.qeocore_remote_registration_init_cond_IgnoreBool = (int)1;
}

void qeocore_remote_registration_init_cond_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_remote_registration_init_cond_CALL_INSTANCE));
  CMOCK_qeocore_remote_registration_init_cond_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_remote_registration_init_cond_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_remote_registration_init_cond_CallInstance = CMock_Guts_MemChain(Mock.qeocore_remote_registration_init_cond_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void qeocore_remote_registration_init_cond_StubWithCallback(CMOCK_qeocore_remote_registration_init_cond_CALLBACK Callback)
{
  Mock.qeocore_remote_registration_init_cond_CallbackFunctionPointer = Callback;
}

void qeocore_remote_registration_set_key(EVP_PKEY* key)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_remote_registration_set_key_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_remote_registration_set_key_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_remote_registration_set_key_CallInstance);
  Mock.qeocore_remote_registration_set_key_CallInstance = CMock_Guts_MemNext(Mock.qeocore_remote_registration_set_key_CallInstance);
  if (Mock.qeocore_remote_registration_set_key_IgnoreBool)
  {
    return;
  }
  if (Mock.qeocore_remote_registration_set_key_CallbackFunctionPointer != NULL)
  {
    Mock.qeocore_remote_registration_set_key_CallbackFunctionPointer(key, Mock.qeocore_remote_registration_set_key_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_remote_registration_set_key' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_key), (void*)(key), sizeof(EVP_PKEY), cmock_line, "Function 'qeocore_remote_registration_set_key' called with unexpected value for argument 'key'.");
}

void CMockExpectParameters_qeocore_remote_registration_set_key(CMOCK_qeocore_remote_registration_set_key_CALL_INSTANCE* cmock_call_instance, EVP_PKEY* key)
{
  cmock_call_instance->Expected_key = key;
}

void qeocore_remote_registration_set_key_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  Mock.qeocore_remote_registration_set_key_IgnoreBool = (int)1;
}

void qeocore_remote_registration_set_key_CMockExpect(UNITY_LINE_TYPE cmock_line, EVP_PKEY* key)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_remote_registration_set_key_CALL_INSTANCE));
  CMOCK_qeocore_remote_registration_set_key_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_remote_registration_set_key_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_remote_registration_set_key_CallInstance = CMock_Guts_MemChain(Mock.qeocore_remote_registration_set_key_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_remote_registration_set_key(cmock_call_instance, key);
}

void qeocore_remote_registration_set_key_StubWithCallback(CMOCK_qeocore_remote_registration_set_key_CALLBACK Callback)
{
  Mock.qeocore_remote_registration_set_key_CallbackFunctionPointer = Callback;
}

