/*
 * Copyright (c) 2014 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#define NO_TEST_ASSERT_EQUAL_MEMORY_MESSAGE
#include "unity.h"
#include "cmock.h"
#include "Mockmgmt_cert_parser.h"

typedef struct _CMOCK_qeo_mgmt_cert_parse_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_mgmt_cert_retcode_t ReturnVal;
  STACK_OF(X509)* Expected_chain;
  qeo_mgmt_cert_contents* Expected_contents;

} CMOCK_qeo_mgmt_cert_parse_CALL_INSTANCE;

static struct Mockmgmt_cert_parserInstance
{
  int qeo_mgmt_cert_parse_IgnoreBool;
  qeo_mgmt_cert_retcode_t qeo_mgmt_cert_parse_FinalReturn;
  CMOCK_qeo_mgmt_cert_parse_CALLBACK qeo_mgmt_cert_parse_CallbackFunctionPointer;
  int qeo_mgmt_cert_parse_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_mgmt_cert_parse_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmgmt_cert_parser_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.qeo_mgmt_cert_parse_IgnoreBool)
    Mock.qeo_mgmt_cert_parse_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_mgmt_cert_parse_CallInstance, cmock_line, "Function 'qeo_mgmt_cert_parse' called less times than expected.");
  if (Mock.qeo_mgmt_cert_parse_CallbackFunctionPointer != NULL)
    Mock.qeo_mgmt_cert_parse_CallInstance = CMOCK_GUTS_NONE;
}

void Mockmgmt_cert_parser_Init(void)
{
  Mockmgmt_cert_parser_Destroy();
}

void Mockmgmt_cert_parser_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.qeo_mgmt_cert_parse_CallbackFunctionPointer = NULL;
  Mock.qeo_mgmt_cert_parse_CallbackCalls = 0;
}

qeo_mgmt_cert_retcode_t qeo_mgmt_cert_parse(STACK_OF(X509)* chain, qeo_mgmt_cert_contents* contents)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_mgmt_cert_parse_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_cert_parse_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_mgmt_cert_parse_CallInstance);
  Mock.qeo_mgmt_cert_parse_CallInstance = CMock_Guts_MemNext(Mock.qeo_mgmt_cert_parse_CallInstance);
  if (Mock.qeo_mgmt_cert_parse_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_mgmt_cert_parse_FinalReturn;
    memcpy(&Mock.qeo_mgmt_cert_parse_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_mgmt_cert_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_mgmt_cert_parse_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_mgmt_cert_parse_CallbackFunctionPointer(chain, contents, Mock.qeo_mgmt_cert_parse_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_mgmt_cert_parse' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_chain), (void*)(chain), sizeof(STACK_OF(X509)), cmock_line, "Function 'qeo_mgmt_cert_parse' called with unexpected value for argument 'chain'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_contents), (void*)(contents), sizeof(qeo_mgmt_cert_contents), cmock_line, "Function 'qeo_mgmt_cert_parse' called with unexpected value for argument 'contents'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_mgmt_cert_parse(CMOCK_qeo_mgmt_cert_parse_CALL_INSTANCE* cmock_call_instance, STACK_OF(X509)* chain, qeo_mgmt_cert_contents* contents)
{
  cmock_call_instance->Expected_chain = chain;
  cmock_call_instance->Expected_contents = contents;
}

void qeo_mgmt_cert_parse_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_mgmt_cert_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_mgmt_cert_parse_CALL_INSTANCE));
  CMOCK_qeo_mgmt_cert_parse_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_cert_parse_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_mgmt_cert_parse_CallInstance = CMock_Guts_MemChain(Mock.qeo_mgmt_cert_parse_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_mgmt_cert_parse_IgnoreBool = (int)1;
}

void qeo_mgmt_cert_parse_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, STACK_OF(X509)* chain, qeo_mgmt_cert_contents* contents, qeo_mgmt_cert_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_mgmt_cert_parse_CALL_INSTANCE));
  CMOCK_qeo_mgmt_cert_parse_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_cert_parse_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_mgmt_cert_parse_CallInstance = CMock_Guts_MemChain(Mock.qeo_mgmt_cert_parse_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_mgmt_cert_parse(cmock_call_instance, chain, contents);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_mgmt_cert_retcode_t));
}

void qeo_mgmt_cert_parse_StubWithCallback(CMOCK_qeo_mgmt_cert_parse_CALLBACK Callback)
{
  Mock.qeo_mgmt_cert_parse_CallbackFunctionPointer = Callback;
}

