/*
 * Copyright (c) 2014 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#define NO_TEST_ASSERT_EQUAL_MEMORY_MESSAGE
#include "unity.h"
#include "cmock.h"
#include "Mockdyntype.h"

typedef struct _CMOCK_qeocore_enum_value_to_string_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  DDS_TypeSupport_meta* Expected_enum_tsm;
  qeocore_type_t* Expected_enum_type;
  qeo_enum_value_t Expected_value;
  char* Expected_name;
  size_t Expected_sz;

} CMOCK_qeocore_enum_value_to_string_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_enum_string_to_value_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  DDS_TypeSupport_meta* Expected_enum_tsm;
  qeocore_type_t* Expected_enum_type;
  char* Expected_name;
  qeo_enum_value_t* Expected_value;

} CMOCK_qeocore_enum_string_to_value_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_type_register_tsm_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeocore_type_t* ReturnVal;
  qeo_factory_t* Expected_factory;
  DDS_TypeSupport_meta* Expected_tsm;
  char* Expected_name;

} CMOCK_qeocore_type_register_tsm_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_type_register_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_factory_t* Expected_factory;
  qeocore_type_t* Expected_type;
  char* Expected_name;

} CMOCK_qeocore_type_register_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_type_get_member_id_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeocore_type_t* Expected_type;
  char* Expected_name;
  qeocore_member_id_t* Expected_id;

} CMOCK_qeocore_type_get_member_id_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_type_free_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeocore_type_t* Expected_type;

} CMOCK_qeocore_type_free_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_type_string_new_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeocore_type_t* ReturnVal;
  size_t Expected_sz;

} CMOCK_qeocore_type_string_new_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_type_primitive_new_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeocore_type_t* ReturnVal;
  qeocore_typecode_t Expected_tc;

} CMOCK_qeocore_type_primitive_new_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_type_sequence_new_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeocore_type_t* ReturnVal;
  qeocore_type_t* Expected_elem_type;

} CMOCK_qeocore_type_sequence_new_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_type_enum_new_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeocore_type_t* ReturnVal;
  char* Expected_name;
  qeocore_enum_constants_t* Expected_values;

} CMOCK_qeocore_type_enum_new_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_type_struct_new_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeocore_type_t* ReturnVal;
  char* Expected_name;

} CMOCK_qeocore_type_struct_new_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_type_struct_add_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeocore_type_t* Expected_container;
  qeocore_type_t* Expected_member;
  char* Expected_name;
  qeocore_member_id_t* Expected_id;
  unsigned int Expected_flags;

} CMOCK_qeocore_type_struct_add_CALL_INSTANCE;

static struct MockdyntypeInstance
{
  int qeocore_enum_value_to_string_IgnoreBool;
  qeo_retcode_t qeocore_enum_value_to_string_FinalReturn;
  CMOCK_qeocore_enum_value_to_string_CALLBACK qeocore_enum_value_to_string_CallbackFunctionPointer;
  int qeocore_enum_value_to_string_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_enum_value_to_string_CallInstance;
  int qeocore_enum_string_to_value_IgnoreBool;
  qeo_retcode_t qeocore_enum_string_to_value_FinalReturn;
  CMOCK_qeocore_enum_string_to_value_CALLBACK qeocore_enum_string_to_value_CallbackFunctionPointer;
  int qeocore_enum_string_to_value_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_enum_string_to_value_CallInstance;
  int qeocore_type_register_tsm_IgnoreBool;
  qeocore_type_t* qeocore_type_register_tsm_FinalReturn;
  CMOCK_qeocore_type_register_tsm_CALLBACK qeocore_type_register_tsm_CallbackFunctionPointer;
  int qeocore_type_register_tsm_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_type_register_tsm_CallInstance;
  int qeocore_type_register_IgnoreBool;
  qeo_retcode_t qeocore_type_register_FinalReturn;
  CMOCK_qeocore_type_register_CALLBACK qeocore_type_register_CallbackFunctionPointer;
  int qeocore_type_register_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_type_register_CallInstance;
  int qeocore_type_get_member_id_IgnoreBool;
  qeo_retcode_t qeocore_type_get_member_id_FinalReturn;
  CMOCK_qeocore_type_get_member_id_CALLBACK qeocore_type_get_member_id_CallbackFunctionPointer;
  int qeocore_type_get_member_id_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_type_get_member_id_CallInstance;
  int qeocore_type_free_IgnoreBool;
  CMOCK_qeocore_type_free_CALLBACK qeocore_type_free_CallbackFunctionPointer;
  int qeocore_type_free_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_type_free_CallInstance;
  int qeocore_type_string_new_IgnoreBool;
  qeocore_type_t* qeocore_type_string_new_FinalReturn;
  CMOCK_qeocore_type_string_new_CALLBACK qeocore_type_string_new_CallbackFunctionPointer;
  int qeocore_type_string_new_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_type_string_new_CallInstance;
  int qeocore_type_primitive_new_IgnoreBool;
  qeocore_type_t* qeocore_type_primitive_new_FinalReturn;
  CMOCK_qeocore_type_primitive_new_CALLBACK qeocore_type_primitive_new_CallbackFunctionPointer;
  int qeocore_type_primitive_new_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_type_primitive_new_CallInstance;
  int qeocore_type_sequence_new_IgnoreBool;
  qeocore_type_t* qeocore_type_sequence_new_FinalReturn;
  CMOCK_qeocore_type_sequence_new_CALLBACK qeocore_type_sequence_new_CallbackFunctionPointer;
  int qeocore_type_sequence_new_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_type_sequence_new_CallInstance;
  int qeocore_type_enum_new_IgnoreBool;
  qeocore_type_t* qeocore_type_enum_new_FinalReturn;
  CMOCK_qeocore_type_enum_new_CALLBACK qeocore_type_enum_new_CallbackFunctionPointer;
  int qeocore_type_enum_new_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_type_enum_new_CallInstance;
  int qeocore_type_struct_new_IgnoreBool;
  qeocore_type_t* qeocore_type_struct_new_FinalReturn;
  CMOCK_qeocore_type_struct_new_CALLBACK qeocore_type_struct_new_CallbackFunctionPointer;
  int qeocore_type_struct_new_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_type_struct_new_CallInstance;
  int qeocore_type_struct_add_IgnoreBool;
  qeo_retcode_t qeocore_type_struct_add_FinalReturn;
  CMOCK_qeocore_type_struct_add_CALLBACK qeocore_type_struct_add_CallbackFunctionPointer;
  int qeocore_type_struct_add_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_type_struct_add_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockdyntype_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.qeocore_enum_value_to_string_IgnoreBool)
    Mock.qeocore_enum_value_to_string_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_enum_value_to_string_CallInstance, cmock_line, "Function 'qeocore_enum_value_to_string' called less times than expected.");
  if (Mock.qeocore_enum_value_to_string_CallbackFunctionPointer != NULL)
    Mock.qeocore_enum_value_to_string_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_enum_string_to_value_IgnoreBool)
    Mock.qeocore_enum_string_to_value_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_enum_string_to_value_CallInstance, cmock_line, "Function 'qeocore_enum_string_to_value' called less times than expected.");
  if (Mock.qeocore_enum_string_to_value_CallbackFunctionPointer != NULL)
    Mock.qeocore_enum_string_to_value_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_type_register_tsm_IgnoreBool)
    Mock.qeocore_type_register_tsm_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_type_register_tsm_CallInstance, cmock_line, "Function 'qeocore_type_register_tsm' called less times than expected.");
  if (Mock.qeocore_type_register_tsm_CallbackFunctionPointer != NULL)
    Mock.qeocore_type_register_tsm_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_type_register_IgnoreBool)
    Mock.qeocore_type_register_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_type_register_CallInstance, cmock_line, "Function 'qeocore_type_register' called less times than expected.");
  if (Mock.qeocore_type_register_CallbackFunctionPointer != NULL)
    Mock.qeocore_type_register_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_type_get_member_id_IgnoreBool)
    Mock.qeocore_type_get_member_id_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_type_get_member_id_CallInstance, cmock_line, "Function 'qeocore_type_get_member_id' called less times than expected.");
  if (Mock.qeocore_type_get_member_id_CallbackFunctionPointer != NULL)
    Mock.qeocore_type_get_member_id_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_type_free_IgnoreBool)
    Mock.qeocore_type_free_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_type_free_CallInstance, cmock_line, "Function 'qeocore_type_free' called less times than expected.");
  if (Mock.qeocore_type_free_CallbackFunctionPointer != NULL)
    Mock.qeocore_type_free_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_type_string_new_IgnoreBool)
    Mock.qeocore_type_string_new_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_type_string_new_CallInstance, cmock_line, "Function 'qeocore_type_string_new' called less times than expected.");
  if (Mock.qeocore_type_string_new_CallbackFunctionPointer != NULL)
    Mock.qeocore_type_string_new_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_type_primitive_new_IgnoreBool)
    Mock.qeocore_type_primitive_new_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_type_primitive_new_CallInstance, cmock_line, "Function 'qeocore_type_primitive_new' called less times than expected.");
  if (Mock.qeocore_type_primitive_new_CallbackFunctionPointer != NULL)
    Mock.qeocore_type_primitive_new_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_type_sequence_new_IgnoreBool)
    Mock.qeocore_type_sequence_new_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_type_sequence_new_CallInstance, cmock_line, "Function 'qeocore_type_sequence_new' called less times than expected.");
  if (Mock.qeocore_type_sequence_new_CallbackFunctionPointer != NULL)
    Mock.qeocore_type_sequence_new_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_type_enum_new_IgnoreBool)
    Mock.qeocore_type_enum_new_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_type_enum_new_CallInstance, cmock_line, "Function 'qeocore_type_enum_new' called less times than expected.");
  if (Mock.qeocore_type_enum_new_CallbackFunctionPointer != NULL)
    Mock.qeocore_type_enum_new_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_type_struct_new_IgnoreBool)
    Mock.qeocore_type_struct_new_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_type_struct_new_CallInstance, cmock_line, "Function 'qeocore_type_struct_new' called less times than expected.");
  if (Mock.qeocore_type_struct_new_CallbackFunctionPointer != NULL)
    Mock.qeocore_type_struct_new_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_type_struct_add_IgnoreBool)
    Mock.qeocore_type_struct_add_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_type_struct_add_CallInstance, cmock_line, "Function 'qeocore_type_struct_add' called less times than expected.");
  if (Mock.qeocore_type_struct_add_CallbackFunctionPointer != NULL)
    Mock.qeocore_type_struct_add_CallInstance = CMOCK_GUTS_NONE;
}

void Mockdyntype_Init(void)
{
  Mockdyntype_Destroy();
}

void Mockdyntype_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.qeocore_enum_value_to_string_CallbackFunctionPointer = NULL;
  Mock.qeocore_enum_value_to_string_CallbackCalls = 0;
  Mock.qeocore_enum_string_to_value_CallbackFunctionPointer = NULL;
  Mock.qeocore_enum_string_to_value_CallbackCalls = 0;
  Mock.qeocore_type_register_tsm_CallbackFunctionPointer = NULL;
  Mock.qeocore_type_register_tsm_CallbackCalls = 0;
  Mock.qeocore_type_register_CallbackFunctionPointer = NULL;
  Mock.qeocore_type_register_CallbackCalls = 0;
  Mock.qeocore_type_get_member_id_CallbackFunctionPointer = NULL;
  Mock.qeocore_type_get_member_id_CallbackCalls = 0;
  Mock.qeocore_type_free_CallbackFunctionPointer = NULL;
  Mock.qeocore_type_free_CallbackCalls = 0;
  Mock.qeocore_type_string_new_CallbackFunctionPointer = NULL;
  Mock.qeocore_type_string_new_CallbackCalls = 0;
  Mock.qeocore_type_primitive_new_CallbackFunctionPointer = NULL;
  Mock.qeocore_type_primitive_new_CallbackCalls = 0;
  Mock.qeocore_type_sequence_new_CallbackFunctionPointer = NULL;
  Mock.qeocore_type_sequence_new_CallbackCalls = 0;
  Mock.qeocore_type_enum_new_CallbackFunctionPointer = NULL;
  Mock.qeocore_type_enum_new_CallbackCalls = 0;
  Mock.qeocore_type_struct_new_CallbackFunctionPointer = NULL;
  Mock.qeocore_type_struct_new_CallbackCalls = 0;
  Mock.qeocore_type_struct_add_CallbackFunctionPointer = NULL;
  Mock.qeocore_type_struct_add_CallbackCalls = 0;
}

qeo_retcode_t qeocore_enum_value_to_string(const DDS_TypeSupport_meta* enum_tsm, const qeocore_type_t* enum_type, qeo_enum_value_t value, char* name, size_t sz)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_enum_value_to_string_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_enum_value_to_string_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_enum_value_to_string_CallInstance);
  Mock.qeocore_enum_value_to_string_CallInstance = CMock_Guts_MemNext(Mock.qeocore_enum_value_to_string_CallInstance);
  if (Mock.qeocore_enum_value_to_string_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_enum_value_to_string_FinalReturn;
    memcpy(&Mock.qeocore_enum_value_to_string_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_enum_value_to_string_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_enum_value_to_string_CallbackFunctionPointer(enum_tsm, enum_type, value, name, sz, Mock.qeocore_enum_value_to_string_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_enum_value_to_string' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_enum_tsm), (void*)(enum_tsm), sizeof(DDS_TypeSupport_meta), cmock_line, "Function 'qeocore_enum_value_to_string' called with unexpected value for argument 'enum_tsm'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_enum_type), (void*)(enum_type), sizeof(qeocore_type_t), cmock_line, "Function 'qeocore_enum_value_to_string' called with unexpected value for argument 'enum_type'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_value), (void*)(&value), sizeof(qeo_enum_value_t), cmock_line, "Function 'qeocore_enum_value_to_string' called with unexpected value for argument 'value'.");
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_name, name, cmock_line, "Function 'qeocore_enum_value_to_string' called with unexpected value for argument 'name'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_sz), (void*)(&sz), sizeof(size_t), cmock_line, "Function 'qeocore_enum_value_to_string' called with unexpected value for argument 'sz'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_enum_value_to_string(CMOCK_qeocore_enum_value_to_string_CALL_INSTANCE* cmock_call_instance, const DDS_TypeSupport_meta* enum_tsm, const qeocore_type_t* enum_type, qeo_enum_value_t value, char* name, size_t sz)
{
  cmock_call_instance->Expected_enum_tsm = (DDS_TypeSupport_meta*)enum_tsm;
  cmock_call_instance->Expected_enum_type = (qeocore_type_t*)enum_type;
  memcpy(&cmock_call_instance->Expected_value, &value, sizeof(qeo_enum_value_t));
  cmock_call_instance->Expected_name = name;
  memcpy(&cmock_call_instance->Expected_sz, &sz, sizeof(size_t));
}

void qeocore_enum_value_to_string_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_enum_value_to_string_CALL_INSTANCE));
  CMOCK_qeocore_enum_value_to_string_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_enum_value_to_string_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_enum_value_to_string_CallInstance = CMock_Guts_MemChain(Mock.qeocore_enum_value_to_string_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_enum_value_to_string_IgnoreBool = (int)1;
}

void qeocore_enum_value_to_string_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const DDS_TypeSupport_meta* enum_tsm, const qeocore_type_t* enum_type, qeo_enum_value_t value, char* name, size_t sz, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_enum_value_to_string_CALL_INSTANCE));
  CMOCK_qeocore_enum_value_to_string_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_enum_value_to_string_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_enum_value_to_string_CallInstance = CMock_Guts_MemChain(Mock.qeocore_enum_value_to_string_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_enum_value_to_string(cmock_call_instance, enum_tsm, enum_type, value, name, sz);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeocore_enum_value_to_string_StubWithCallback(CMOCK_qeocore_enum_value_to_string_CALLBACK Callback)
{
  Mock.qeocore_enum_value_to_string_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeocore_enum_string_to_value(const DDS_TypeSupport_meta* enum_tsm, const qeocore_type_t* enum_type, const char* name, qeo_enum_value_t* value)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_enum_string_to_value_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_enum_string_to_value_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_enum_string_to_value_CallInstance);
  Mock.qeocore_enum_string_to_value_CallInstance = CMock_Guts_MemNext(Mock.qeocore_enum_string_to_value_CallInstance);
  if (Mock.qeocore_enum_string_to_value_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_enum_string_to_value_FinalReturn;
    memcpy(&Mock.qeocore_enum_string_to_value_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_enum_string_to_value_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_enum_string_to_value_CallbackFunctionPointer(enum_tsm, enum_type, name, value, Mock.qeocore_enum_string_to_value_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_enum_string_to_value' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_enum_tsm), (void*)(enum_tsm), sizeof(DDS_TypeSupport_meta), cmock_line, "Function 'qeocore_enum_string_to_value' called with unexpected value for argument 'enum_tsm'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_enum_type), (void*)(enum_type), sizeof(qeocore_type_t), cmock_line, "Function 'qeocore_enum_string_to_value' called with unexpected value for argument 'enum_type'.");
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_name, name, cmock_line, "Function 'qeocore_enum_string_to_value' called with unexpected value for argument 'name'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_value), (void*)(value), sizeof(qeo_enum_value_t), cmock_line, "Function 'qeocore_enum_string_to_value' called with unexpected value for argument 'value'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_enum_string_to_value(CMOCK_qeocore_enum_string_to_value_CALL_INSTANCE* cmock_call_instance, const DDS_TypeSupport_meta* enum_tsm, const qeocore_type_t* enum_type, const char* name, qeo_enum_value_t* value)
{
  cmock_call_instance->Expected_enum_tsm = (DDS_TypeSupport_meta*)enum_tsm;
  cmock_call_instance->Expected_enum_type = (qeocore_type_t*)enum_type;
  cmock_call_instance->Expected_name = (char*)name;
  cmock_call_instance->Expected_value = value;
}

void qeocore_enum_string_to_value_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_enum_string_to_value_CALL_INSTANCE));
  CMOCK_qeocore_enum_string_to_value_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_enum_string_to_value_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_enum_string_to_value_CallInstance = CMock_Guts_MemChain(Mock.qeocore_enum_string_to_value_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_enum_string_to_value_IgnoreBool = (int)1;
}

void qeocore_enum_string_to_value_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const DDS_TypeSupport_meta* enum_tsm, const qeocore_type_t* enum_type, const char* name, qeo_enum_value_t* value, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_enum_string_to_value_CALL_INSTANCE));
  CMOCK_qeocore_enum_string_to_value_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_enum_string_to_value_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_enum_string_to_value_CallInstance = CMock_Guts_MemChain(Mock.qeocore_enum_string_to_value_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_enum_string_to_value(cmock_call_instance, enum_tsm, enum_type, name, value);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeocore_enum_string_to_value_StubWithCallback(CMOCK_qeocore_enum_string_to_value_CALLBACK Callback)
{
  Mock.qeocore_enum_string_to_value_CallbackFunctionPointer = Callback;
}

qeocore_type_t* qeocore_type_register_tsm(const qeo_factory_t* factory, const DDS_TypeSupport_meta* tsm, const char* name)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_type_register_tsm_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_register_tsm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_type_register_tsm_CallInstance);
  Mock.qeocore_type_register_tsm_CallInstance = CMock_Guts_MemNext(Mock.qeocore_type_register_tsm_CallInstance);
  if (Mock.qeocore_type_register_tsm_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_type_register_tsm_FinalReturn;
    Mock.qeocore_type_register_tsm_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_type_register_tsm_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_type_register_tsm_CallbackFunctionPointer(factory, tsm, name, Mock.qeocore_type_register_tsm_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_type_register_tsm' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_factory), (void*)(factory), sizeof(qeo_factory_t), cmock_line, "Function 'qeocore_type_register_tsm' called with unexpected value for argument 'factory'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_tsm), (void*)(tsm), sizeof(DDS_TypeSupport_meta), cmock_line, "Function 'qeocore_type_register_tsm' called with unexpected value for argument 'tsm'.");
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_name, name, cmock_line, "Function 'qeocore_type_register_tsm' called with unexpected value for argument 'name'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_type_register_tsm(CMOCK_qeocore_type_register_tsm_CALL_INSTANCE* cmock_call_instance, const qeo_factory_t* factory, const DDS_TypeSupport_meta* tsm, const char* name)
{
  cmock_call_instance->Expected_factory = (qeo_factory_t*)factory;
  cmock_call_instance->Expected_tsm = (DDS_TypeSupport_meta*)tsm;
  cmock_call_instance->Expected_name = (char*)name;
}

void qeocore_type_register_tsm_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeocore_type_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_type_register_tsm_CALL_INSTANCE));
  CMOCK_qeocore_type_register_tsm_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_register_tsm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_type_register_tsm_CallInstance = CMock_Guts_MemChain(Mock.qeocore_type_register_tsm_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_type_register_tsm_IgnoreBool = (int)1;
}

void qeocore_type_register_tsm_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const qeo_factory_t* factory, const DDS_TypeSupport_meta* tsm, const char* name, qeocore_type_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_type_register_tsm_CALL_INSTANCE));
  CMOCK_qeocore_type_register_tsm_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_register_tsm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_type_register_tsm_CallInstance = CMock_Guts_MemChain(Mock.qeocore_type_register_tsm_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_type_register_tsm(cmock_call_instance, factory, tsm, name);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void qeocore_type_register_tsm_StubWithCallback(CMOCK_qeocore_type_register_tsm_CALLBACK Callback)
{
  Mock.qeocore_type_register_tsm_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeocore_type_register(const qeo_factory_t* factory, qeocore_type_t* type, const char* name)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_type_register_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_type_register_CallInstance);
  Mock.qeocore_type_register_CallInstance = CMock_Guts_MemNext(Mock.qeocore_type_register_CallInstance);
  if (Mock.qeocore_type_register_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_type_register_FinalReturn;
    memcpy(&Mock.qeocore_type_register_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_type_register_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_type_register_CallbackFunctionPointer(factory, type, name, Mock.qeocore_type_register_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_type_register' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_factory), (void*)(factory), sizeof(qeo_factory_t), cmock_line, "Function 'qeocore_type_register' called with unexpected value for argument 'factory'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_type), (void*)(type), sizeof(qeocore_type_t), cmock_line, "Function 'qeocore_type_register' called with unexpected value for argument 'type'.");
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_name, name, cmock_line, "Function 'qeocore_type_register' called with unexpected value for argument 'name'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_type_register(CMOCK_qeocore_type_register_CALL_INSTANCE* cmock_call_instance, const qeo_factory_t* factory, qeocore_type_t* type, const char* name)
{
  cmock_call_instance->Expected_factory = (qeo_factory_t*)factory;
  cmock_call_instance->Expected_type = type;
  cmock_call_instance->Expected_name = (char*)name;
}

void qeocore_type_register_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_type_register_CALL_INSTANCE));
  CMOCK_qeocore_type_register_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_type_register_CallInstance = CMock_Guts_MemChain(Mock.qeocore_type_register_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_type_register_IgnoreBool = (int)1;
}

void qeocore_type_register_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const qeo_factory_t* factory, qeocore_type_t* type, const char* name, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_type_register_CALL_INSTANCE));
  CMOCK_qeocore_type_register_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_type_register_CallInstance = CMock_Guts_MemChain(Mock.qeocore_type_register_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_type_register(cmock_call_instance, factory, type, name);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeocore_type_register_StubWithCallback(CMOCK_qeocore_type_register_CALLBACK Callback)
{
  Mock.qeocore_type_register_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeocore_type_get_member_id(const qeocore_type_t* type, const char* name, qeocore_member_id_t* id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_type_get_member_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_get_member_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_type_get_member_id_CallInstance);
  Mock.qeocore_type_get_member_id_CallInstance = CMock_Guts_MemNext(Mock.qeocore_type_get_member_id_CallInstance);
  if (Mock.qeocore_type_get_member_id_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_type_get_member_id_FinalReturn;
    memcpy(&Mock.qeocore_type_get_member_id_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_type_get_member_id_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_type_get_member_id_CallbackFunctionPointer(type, name, id, Mock.qeocore_type_get_member_id_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_type_get_member_id' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_type), (void*)(type), sizeof(qeocore_type_t), cmock_line, "Function 'qeocore_type_get_member_id' called with unexpected value for argument 'type'.");
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_name, name, cmock_line, "Function 'qeocore_type_get_member_id' called with unexpected value for argument 'name'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_id), (void*)(id), sizeof(qeocore_member_id_t), cmock_line, "Function 'qeocore_type_get_member_id' called with unexpected value for argument 'id'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_type_get_member_id(CMOCK_qeocore_type_get_member_id_CALL_INSTANCE* cmock_call_instance, const qeocore_type_t* type, const char* name, qeocore_member_id_t* id)
{
  cmock_call_instance->Expected_type = (qeocore_type_t*)type;
  cmock_call_instance->Expected_name = (char*)name;
  cmock_call_instance->Expected_id = id;
}

void qeocore_type_get_member_id_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_type_get_member_id_CALL_INSTANCE));
  CMOCK_qeocore_type_get_member_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_get_member_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_type_get_member_id_CallInstance = CMock_Guts_MemChain(Mock.qeocore_type_get_member_id_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_type_get_member_id_IgnoreBool = (int)1;
}

void qeocore_type_get_member_id_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const qeocore_type_t* type, const char* name, qeocore_member_id_t* id, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_type_get_member_id_CALL_INSTANCE));
  CMOCK_qeocore_type_get_member_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_get_member_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_type_get_member_id_CallInstance = CMock_Guts_MemChain(Mock.qeocore_type_get_member_id_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_type_get_member_id(cmock_call_instance, type, name, id);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeocore_type_get_member_id_StubWithCallback(CMOCK_qeocore_type_get_member_id_CALLBACK Callback)
{
  Mock.qeocore_type_get_member_id_CallbackFunctionPointer = Callback;
}

void qeocore_type_free(qeocore_type_t* type)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_type_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_type_free_CallInstance);
  Mock.qeocore_type_free_CallInstance = CMock_Guts_MemNext(Mock.qeocore_type_free_CallInstance);
  if (Mock.qeocore_type_free_IgnoreBool)
  {
    return;
  }
  if (Mock.qeocore_type_free_CallbackFunctionPointer != NULL)
  {
    Mock.qeocore_type_free_CallbackFunctionPointer(type, Mock.qeocore_type_free_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_type_free' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_type), (void*)(type), sizeof(qeocore_type_t), cmock_line, "Function 'qeocore_type_free' called with unexpected value for argument 'type'.");
}

void CMockExpectParameters_qeocore_type_free(CMOCK_qeocore_type_free_CALL_INSTANCE* cmock_call_instance, qeocore_type_t* type)
{
  cmock_call_instance->Expected_type = type;
}

void qeocore_type_free_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  Mock.qeocore_type_free_IgnoreBool = (int)1;
}

void qeocore_type_free_CMockExpect(UNITY_LINE_TYPE cmock_line, qeocore_type_t* type)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_type_free_CALL_INSTANCE));
  CMOCK_qeocore_type_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_type_free_CallInstance = CMock_Guts_MemChain(Mock.qeocore_type_free_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_type_free(cmock_call_instance, type);
}

void qeocore_type_free_StubWithCallback(CMOCK_qeocore_type_free_CALLBACK Callback)
{
  Mock.qeocore_type_free_CallbackFunctionPointer = Callback;
}

qeocore_type_t* qeocore_type_string_new(size_t sz)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_type_string_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_string_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_type_string_new_CallInstance);
  Mock.qeocore_type_string_new_CallInstance = CMock_Guts_MemNext(Mock.qeocore_type_string_new_CallInstance);
  if (Mock.qeocore_type_string_new_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_type_string_new_FinalReturn;
    Mock.qeocore_type_string_new_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_type_string_new_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_type_string_new_CallbackFunctionPointer(sz, Mock.qeocore_type_string_new_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_type_string_new' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_sz), (void*)(&sz), sizeof(size_t), cmock_line, "Function 'qeocore_type_string_new' called with unexpected value for argument 'sz'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_type_string_new(CMOCK_qeocore_type_string_new_CALL_INSTANCE* cmock_call_instance, size_t sz)
{
  memcpy(&cmock_call_instance->Expected_sz, &sz, sizeof(size_t));
}

void qeocore_type_string_new_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeocore_type_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_type_string_new_CALL_INSTANCE));
  CMOCK_qeocore_type_string_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_string_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_type_string_new_CallInstance = CMock_Guts_MemChain(Mock.qeocore_type_string_new_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_type_string_new_IgnoreBool = (int)1;
}

void qeocore_type_string_new_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, size_t sz, qeocore_type_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_type_string_new_CALL_INSTANCE));
  CMOCK_qeocore_type_string_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_string_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_type_string_new_CallInstance = CMock_Guts_MemChain(Mock.qeocore_type_string_new_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_type_string_new(cmock_call_instance, sz);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void qeocore_type_string_new_StubWithCallback(CMOCK_qeocore_type_string_new_CALLBACK Callback)
{
  Mock.qeocore_type_string_new_CallbackFunctionPointer = Callback;
}

qeocore_type_t* qeocore_type_primitive_new(qeocore_typecode_t tc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_type_primitive_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_primitive_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_type_primitive_new_CallInstance);
  Mock.qeocore_type_primitive_new_CallInstance = CMock_Guts_MemNext(Mock.qeocore_type_primitive_new_CallInstance);
  if (Mock.qeocore_type_primitive_new_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_type_primitive_new_FinalReturn;
    Mock.qeocore_type_primitive_new_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_type_primitive_new_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_type_primitive_new_CallbackFunctionPointer(tc, Mock.qeocore_type_primitive_new_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_type_primitive_new' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_tc), (void*)(&tc), sizeof(qeocore_typecode_t), cmock_line, "Function 'qeocore_type_primitive_new' called with unexpected value for argument 'tc'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_type_primitive_new(CMOCK_qeocore_type_primitive_new_CALL_INSTANCE* cmock_call_instance, qeocore_typecode_t tc)
{
  memcpy(&cmock_call_instance->Expected_tc, &tc, sizeof(qeocore_typecode_t));
}

void qeocore_type_primitive_new_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeocore_type_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_type_primitive_new_CALL_INSTANCE));
  CMOCK_qeocore_type_primitive_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_primitive_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_type_primitive_new_CallInstance = CMock_Guts_MemChain(Mock.qeocore_type_primitive_new_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_type_primitive_new_IgnoreBool = (int)1;
}

void qeocore_type_primitive_new_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeocore_typecode_t tc, qeocore_type_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_type_primitive_new_CALL_INSTANCE));
  CMOCK_qeocore_type_primitive_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_primitive_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_type_primitive_new_CallInstance = CMock_Guts_MemChain(Mock.qeocore_type_primitive_new_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_type_primitive_new(cmock_call_instance, tc);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void qeocore_type_primitive_new_StubWithCallback(CMOCK_qeocore_type_primitive_new_CALLBACK Callback)
{
  Mock.qeocore_type_primitive_new_CallbackFunctionPointer = Callback;
}

qeocore_type_t* qeocore_type_sequence_new(qeocore_type_t* elem_type)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_type_sequence_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_sequence_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_type_sequence_new_CallInstance);
  Mock.qeocore_type_sequence_new_CallInstance = CMock_Guts_MemNext(Mock.qeocore_type_sequence_new_CallInstance);
  if (Mock.qeocore_type_sequence_new_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_type_sequence_new_FinalReturn;
    Mock.qeocore_type_sequence_new_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_type_sequence_new_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_type_sequence_new_CallbackFunctionPointer(elem_type, Mock.qeocore_type_sequence_new_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_type_sequence_new' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_elem_type), (void*)(elem_type), sizeof(qeocore_type_t), cmock_line, "Function 'qeocore_type_sequence_new' called with unexpected value for argument 'elem_type'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_type_sequence_new(CMOCK_qeocore_type_sequence_new_CALL_INSTANCE* cmock_call_instance, qeocore_type_t* elem_type)
{
  cmock_call_instance->Expected_elem_type = elem_type;
}

void qeocore_type_sequence_new_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeocore_type_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_type_sequence_new_CALL_INSTANCE));
  CMOCK_qeocore_type_sequence_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_sequence_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_type_sequence_new_CallInstance = CMock_Guts_MemChain(Mock.qeocore_type_sequence_new_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_type_sequence_new_IgnoreBool = (int)1;
}

void qeocore_type_sequence_new_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeocore_type_t* elem_type, qeocore_type_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_type_sequence_new_CALL_INSTANCE));
  CMOCK_qeocore_type_sequence_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_sequence_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_type_sequence_new_CallInstance = CMock_Guts_MemChain(Mock.qeocore_type_sequence_new_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_type_sequence_new(cmock_call_instance, elem_type);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void qeocore_type_sequence_new_StubWithCallback(CMOCK_qeocore_type_sequence_new_CALLBACK Callback)
{
  Mock.qeocore_type_sequence_new_CallbackFunctionPointer = Callback;
}

qeocore_type_t* qeocore_type_enum_new(const char* name, const qeocore_enum_constants_t* values)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_type_enum_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_enum_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_type_enum_new_CallInstance);
  Mock.qeocore_type_enum_new_CallInstance = CMock_Guts_MemNext(Mock.qeocore_type_enum_new_CallInstance);
  if (Mock.qeocore_type_enum_new_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_type_enum_new_FinalReturn;
    Mock.qeocore_type_enum_new_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_type_enum_new_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_type_enum_new_CallbackFunctionPointer(name, values, Mock.qeocore_type_enum_new_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_type_enum_new' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_name, name, cmock_line, "Function 'qeocore_type_enum_new' called with unexpected value for argument 'name'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_values), (void*)(values), sizeof(qeocore_enum_constants_t), cmock_line, "Function 'qeocore_type_enum_new' called with unexpected value for argument 'values'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_type_enum_new(CMOCK_qeocore_type_enum_new_CALL_INSTANCE* cmock_call_instance, const char* name, const qeocore_enum_constants_t* values)
{
  cmock_call_instance->Expected_name = (char*)name;
  cmock_call_instance->Expected_values = (qeocore_enum_constants_t*)values;
}

void qeocore_type_enum_new_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeocore_type_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_type_enum_new_CALL_INSTANCE));
  CMOCK_qeocore_type_enum_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_enum_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_type_enum_new_CallInstance = CMock_Guts_MemChain(Mock.qeocore_type_enum_new_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_type_enum_new_IgnoreBool = (int)1;
}

void qeocore_type_enum_new_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* name, const qeocore_enum_constants_t* values, qeocore_type_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_type_enum_new_CALL_INSTANCE));
  CMOCK_qeocore_type_enum_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_enum_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_type_enum_new_CallInstance = CMock_Guts_MemChain(Mock.qeocore_type_enum_new_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_type_enum_new(cmock_call_instance, name, values);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void qeocore_type_enum_new_StubWithCallback(CMOCK_qeocore_type_enum_new_CALLBACK Callback)
{
  Mock.qeocore_type_enum_new_CallbackFunctionPointer = Callback;
}

qeocore_type_t* qeocore_type_struct_new(const char* name)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_type_struct_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_struct_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_type_struct_new_CallInstance);
  Mock.qeocore_type_struct_new_CallInstance = CMock_Guts_MemNext(Mock.qeocore_type_struct_new_CallInstance);
  if (Mock.qeocore_type_struct_new_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_type_struct_new_FinalReturn;
    Mock.qeocore_type_struct_new_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_type_struct_new_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_type_struct_new_CallbackFunctionPointer(name, Mock.qeocore_type_struct_new_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_type_struct_new' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_name, name, cmock_line, "Function 'qeocore_type_struct_new' called with unexpected value for argument 'name'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_type_struct_new(CMOCK_qeocore_type_struct_new_CALL_INSTANCE* cmock_call_instance, const char* name)
{
  cmock_call_instance->Expected_name = (char*)name;
}

void qeocore_type_struct_new_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeocore_type_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_type_struct_new_CALL_INSTANCE));
  CMOCK_qeocore_type_struct_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_struct_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_type_struct_new_CallInstance = CMock_Guts_MemChain(Mock.qeocore_type_struct_new_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_type_struct_new_IgnoreBool = (int)1;
}

void qeocore_type_struct_new_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* name, qeocore_type_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_type_struct_new_CALL_INSTANCE));
  CMOCK_qeocore_type_struct_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_struct_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_type_struct_new_CallInstance = CMock_Guts_MemChain(Mock.qeocore_type_struct_new_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_type_struct_new(cmock_call_instance, name);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void qeocore_type_struct_new_StubWithCallback(CMOCK_qeocore_type_struct_new_CALLBACK Callback)
{
  Mock.qeocore_type_struct_new_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeocore_type_struct_add(qeocore_type_t* container, qeocore_type_t* member, const char* name, qeocore_member_id_t* id, unsigned int flags)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_type_struct_add_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_struct_add_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_type_struct_add_CallInstance);
  Mock.qeocore_type_struct_add_CallInstance = CMock_Guts_MemNext(Mock.qeocore_type_struct_add_CallInstance);
  if (Mock.qeocore_type_struct_add_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_type_struct_add_FinalReturn;
    memcpy(&Mock.qeocore_type_struct_add_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_type_struct_add_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_type_struct_add_CallbackFunctionPointer(container, member, name, id, flags, Mock.qeocore_type_struct_add_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_type_struct_add' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_container), (void*)(container), sizeof(qeocore_type_t), cmock_line, "Function 'qeocore_type_struct_add' called with unexpected value for argument 'container'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_member), (void*)(member), sizeof(qeocore_type_t), cmock_line, "Function 'qeocore_type_struct_add' called with unexpected value for argument 'member'.");
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_name, name, cmock_line, "Function 'qeocore_type_struct_add' called with unexpected value for argument 'name'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_id), (void*)(id), sizeof(qeocore_member_id_t), cmock_line, "Function 'qeocore_type_struct_add' called with unexpected value for argument 'id'.");
  UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_flags, flags, cmock_line, "Function 'qeocore_type_struct_add' called with unexpected value for argument 'flags'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_type_struct_add(CMOCK_qeocore_type_struct_add_CALL_INSTANCE* cmock_call_instance, qeocore_type_t* container, qeocore_type_t* member, const char* name, qeocore_member_id_t* id, unsigned int flags)
{
  cmock_call_instance->Expected_container = container;
  cmock_call_instance->Expected_member = member;
  cmock_call_instance->Expected_name = (char*)name;
  cmock_call_instance->Expected_id = id;
  cmock_call_instance->Expected_flags = flags;
}

void qeocore_type_struct_add_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_type_struct_add_CALL_INSTANCE));
  CMOCK_qeocore_type_struct_add_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_struct_add_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_type_struct_add_CallInstance = CMock_Guts_MemChain(Mock.qeocore_type_struct_add_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_type_struct_add_IgnoreBool = (int)1;
}

void qeocore_type_struct_add_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeocore_type_t* container, qeocore_type_t* member, const char* name, qeocore_member_id_t* id, unsigned int flags, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_type_struct_add_CALL_INSTANCE));
  CMOCK_qeocore_type_struct_add_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_type_struct_add_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_type_struct_add_CallInstance = CMock_Guts_MemChain(Mock.qeocore_type_struct_add_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_type_struct_add(cmock_call_instance, container, member, name, id, flags);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeocore_type_struct_add_StubWithCallback(CMOCK_qeocore_type_struct_add_CALLBACK Callback)
{
  Mock.qeocore_type_struct_add_CallbackFunctionPointer = Callback;
}

