/*
 * Copyright (c) 2014 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#define NO_TEST_ASSERT_EQUAL_MEMORY_MESSAGE
#include "unity.h"
#include "cmock.h"
#include "Mockfactory.h"

typedef struct _CMOCK_qeocore_factory_new_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_factory_t* ReturnVal;
  qeo_identity_t* Expected_id;

} CMOCK_qeocore_factory_new_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_factory_close_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_factory_t* Expected_factory;

} CMOCK_qeocore_factory_close_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_factory_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_factory_t* Expected_factory;
  qeocore_factory_listener_t* Expected_listener;

} CMOCK_qeocore_factory_init_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_factory_refresh_policy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_factory_t* Expected_factory;

} CMOCK_qeocore_factory_refresh_policy_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_factory_set_domainid_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_factory_t* Expected_factory;
  qeocore_domain_id_t Expected_id;

} CMOCK_qeocore_factory_set_domainid_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_factory_get_domainid_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_factory_t* Expected_factory;
  qeocore_domain_id_t* Expected_id;

} CMOCK_qeocore_factory_get_domainid_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_factory_get_realm_id_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int64_t ReturnVal;
  qeo_factory_t* Expected_factory;

} CMOCK_qeocore_factory_get_realm_id_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_factory_get_user_id_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int64_t ReturnVal;
  qeo_factory_t* Expected_factory;

} CMOCK_qeocore_factory_get_user_id_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_factory_get_realm_url_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char* ReturnVal;
  qeo_factory_t* Expected_factory;

} CMOCK_qeocore_factory_get_realm_url_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_factory_set_intf_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_factory_t* Expected_factory;
  char* Expected_interfaces;

} CMOCK_qeocore_factory_set_intf_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_factory_set_tcp_server_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_factory_t* Expected_factory;
  char* Expected_tcp_server;

} CMOCK_qeocore_factory_set_tcp_server_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_factory_set_local_tcp_port_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_factory_t* Expected_factory;
  char* Expected_local_port;

} CMOCK_qeocore_factory_set_local_tcp_port_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_factory_set_user_data_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_factory_t* Expected_factory;
  uintptr_t Expected_userdata;

} CMOCK_qeocore_factory_set_user_data_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_factory_get_user_data_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_factory_t* Expected_factory;
  uintptr_t* Expected_userdata;

} CMOCK_qeocore_factory_get_user_data_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_fwdfactory_new_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_factory_t* ReturnVal;
  qeocore_on_fwdfactory_get_public_locator Expected_cb;
  char* Expected_local_port;

} CMOCK_qeocore_fwdfactory_new_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_fwdfactory_close_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_factory_t* Expected_factory;

} CMOCK_qeocore_fwdfactory_close_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_fwdfactory_set_public_locator_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_factory_t* Expected_factory;
  char* Expected_ip_address;
  int Expected_port;

} CMOCK_qeocore_fwdfactory_set_public_locator_CALL_INSTANCE;

typedef struct _CMOCK_qeocore_atexit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeocore_exit_cb Expected_cb;

} CMOCK_qeocore_atexit_CALL_INSTANCE;

static struct MockfactoryInstance
{
  int qeocore_factory_new_IgnoreBool;
  qeo_factory_t* qeocore_factory_new_FinalReturn;
  CMOCK_qeocore_factory_new_CALLBACK qeocore_factory_new_CallbackFunctionPointer;
  int qeocore_factory_new_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_factory_new_CallInstance;
  int qeocore_factory_close_IgnoreBool;
  CMOCK_qeocore_factory_close_CALLBACK qeocore_factory_close_CallbackFunctionPointer;
  int qeocore_factory_close_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_factory_close_CallInstance;
  int qeocore_factory_init_IgnoreBool;
  qeo_retcode_t qeocore_factory_init_FinalReturn;
  CMOCK_qeocore_factory_init_CALLBACK qeocore_factory_init_CallbackFunctionPointer;
  int qeocore_factory_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_factory_init_CallInstance;
  int qeocore_factory_refresh_policy_IgnoreBool;
  qeo_retcode_t qeocore_factory_refresh_policy_FinalReturn;
  CMOCK_qeocore_factory_refresh_policy_CALLBACK qeocore_factory_refresh_policy_CallbackFunctionPointer;
  int qeocore_factory_refresh_policy_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_factory_refresh_policy_CallInstance;
  int qeocore_factory_set_domainid_IgnoreBool;
  qeo_retcode_t qeocore_factory_set_domainid_FinalReturn;
  CMOCK_qeocore_factory_set_domainid_CALLBACK qeocore_factory_set_domainid_CallbackFunctionPointer;
  int qeocore_factory_set_domainid_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_factory_set_domainid_CallInstance;
  int qeocore_factory_get_domainid_IgnoreBool;
  qeo_retcode_t qeocore_factory_get_domainid_FinalReturn;
  CMOCK_qeocore_factory_get_domainid_CALLBACK qeocore_factory_get_domainid_CallbackFunctionPointer;
  int qeocore_factory_get_domainid_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_factory_get_domainid_CallInstance;
  int qeocore_factory_get_realm_id_IgnoreBool;
  int64_t qeocore_factory_get_realm_id_FinalReturn;
  CMOCK_qeocore_factory_get_realm_id_CALLBACK qeocore_factory_get_realm_id_CallbackFunctionPointer;
  int qeocore_factory_get_realm_id_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_factory_get_realm_id_CallInstance;
  int qeocore_factory_get_user_id_IgnoreBool;
  int64_t qeocore_factory_get_user_id_FinalReturn;
  CMOCK_qeocore_factory_get_user_id_CALLBACK qeocore_factory_get_user_id_CallbackFunctionPointer;
  int qeocore_factory_get_user_id_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_factory_get_user_id_CallInstance;
  int qeocore_factory_get_realm_url_IgnoreBool;
  char* qeocore_factory_get_realm_url_FinalReturn;
  CMOCK_qeocore_factory_get_realm_url_CALLBACK qeocore_factory_get_realm_url_CallbackFunctionPointer;
  int qeocore_factory_get_realm_url_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_factory_get_realm_url_CallInstance;
  int qeocore_factory_set_intf_IgnoreBool;
  qeo_retcode_t qeocore_factory_set_intf_FinalReturn;
  CMOCK_qeocore_factory_set_intf_CALLBACK qeocore_factory_set_intf_CallbackFunctionPointer;
  int qeocore_factory_set_intf_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_factory_set_intf_CallInstance;
  int qeocore_factory_set_tcp_server_IgnoreBool;
  qeo_retcode_t qeocore_factory_set_tcp_server_FinalReturn;
  CMOCK_qeocore_factory_set_tcp_server_CALLBACK qeocore_factory_set_tcp_server_CallbackFunctionPointer;
  int qeocore_factory_set_tcp_server_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_factory_set_tcp_server_CallInstance;
  int qeocore_factory_set_local_tcp_port_IgnoreBool;
  qeo_retcode_t qeocore_factory_set_local_tcp_port_FinalReturn;
  CMOCK_qeocore_factory_set_local_tcp_port_CALLBACK qeocore_factory_set_local_tcp_port_CallbackFunctionPointer;
  int qeocore_factory_set_local_tcp_port_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_factory_set_local_tcp_port_CallInstance;
  int qeocore_factory_set_user_data_IgnoreBool;
  qeo_retcode_t qeocore_factory_set_user_data_FinalReturn;
  CMOCK_qeocore_factory_set_user_data_CALLBACK qeocore_factory_set_user_data_CallbackFunctionPointer;
  int qeocore_factory_set_user_data_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_factory_set_user_data_CallInstance;
  int qeocore_factory_get_user_data_IgnoreBool;
  qeo_retcode_t qeocore_factory_get_user_data_FinalReturn;
  CMOCK_qeocore_factory_get_user_data_CALLBACK qeocore_factory_get_user_data_CallbackFunctionPointer;
  int qeocore_factory_get_user_data_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_factory_get_user_data_CallInstance;
  int qeocore_fwdfactory_new_IgnoreBool;
  qeo_factory_t* qeocore_fwdfactory_new_FinalReturn;
  CMOCK_qeocore_fwdfactory_new_CALLBACK qeocore_fwdfactory_new_CallbackFunctionPointer;
  int qeocore_fwdfactory_new_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_fwdfactory_new_CallInstance;
  int qeocore_fwdfactory_close_IgnoreBool;
  CMOCK_qeocore_fwdfactory_close_CALLBACK qeocore_fwdfactory_close_CallbackFunctionPointer;
  int qeocore_fwdfactory_close_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_fwdfactory_close_CallInstance;
  int qeocore_fwdfactory_set_public_locator_IgnoreBool;
  qeo_retcode_t qeocore_fwdfactory_set_public_locator_FinalReturn;
  CMOCK_qeocore_fwdfactory_set_public_locator_CALLBACK qeocore_fwdfactory_set_public_locator_CallbackFunctionPointer;
  int qeocore_fwdfactory_set_public_locator_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_fwdfactory_set_public_locator_CallInstance;
  int qeocore_atexit_IgnoreBool;
  CMOCK_qeocore_atexit_CALLBACK qeocore_atexit_CallbackFunctionPointer;
  int qeocore_atexit_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeocore_atexit_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockfactory_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.qeocore_factory_new_IgnoreBool)
    Mock.qeocore_factory_new_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_factory_new_CallInstance, cmock_line, "Function 'qeocore_factory_new' called less times than expected.");
  if (Mock.qeocore_factory_new_CallbackFunctionPointer != NULL)
    Mock.qeocore_factory_new_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_factory_close_IgnoreBool)
    Mock.qeocore_factory_close_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_factory_close_CallInstance, cmock_line, "Function 'qeocore_factory_close' called less times than expected.");
  if (Mock.qeocore_factory_close_CallbackFunctionPointer != NULL)
    Mock.qeocore_factory_close_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_factory_init_IgnoreBool)
    Mock.qeocore_factory_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_factory_init_CallInstance, cmock_line, "Function 'qeocore_factory_init' called less times than expected.");
  if (Mock.qeocore_factory_init_CallbackFunctionPointer != NULL)
    Mock.qeocore_factory_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_factory_refresh_policy_IgnoreBool)
    Mock.qeocore_factory_refresh_policy_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_factory_refresh_policy_CallInstance, cmock_line, "Function 'qeocore_factory_refresh_policy' called less times than expected.");
  if (Mock.qeocore_factory_refresh_policy_CallbackFunctionPointer != NULL)
    Mock.qeocore_factory_refresh_policy_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_factory_set_domainid_IgnoreBool)
    Mock.qeocore_factory_set_domainid_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_factory_set_domainid_CallInstance, cmock_line, "Function 'qeocore_factory_set_domainid' called less times than expected.");
  if (Mock.qeocore_factory_set_domainid_CallbackFunctionPointer != NULL)
    Mock.qeocore_factory_set_domainid_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_factory_get_domainid_IgnoreBool)
    Mock.qeocore_factory_get_domainid_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_factory_get_domainid_CallInstance, cmock_line, "Function 'qeocore_factory_get_domainid' called less times than expected.");
  if (Mock.qeocore_factory_get_domainid_CallbackFunctionPointer != NULL)
    Mock.qeocore_factory_get_domainid_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_factory_get_realm_id_IgnoreBool)
    Mock.qeocore_factory_get_realm_id_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_factory_get_realm_id_CallInstance, cmock_line, "Function 'qeocore_factory_get_realm_id' called less times than expected.");
  if (Mock.qeocore_factory_get_realm_id_CallbackFunctionPointer != NULL)
    Mock.qeocore_factory_get_realm_id_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_factory_get_user_id_IgnoreBool)
    Mock.qeocore_factory_get_user_id_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_factory_get_user_id_CallInstance, cmock_line, "Function 'qeocore_factory_get_user_id' called less times than expected.");
  if (Mock.qeocore_factory_get_user_id_CallbackFunctionPointer != NULL)
    Mock.qeocore_factory_get_user_id_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_factory_get_realm_url_IgnoreBool)
    Mock.qeocore_factory_get_realm_url_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_factory_get_realm_url_CallInstance, cmock_line, "Function 'qeocore_factory_get_realm_url' called less times than expected.");
  if (Mock.qeocore_factory_get_realm_url_CallbackFunctionPointer != NULL)
    Mock.qeocore_factory_get_realm_url_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_factory_set_intf_IgnoreBool)
    Mock.qeocore_factory_set_intf_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_factory_set_intf_CallInstance, cmock_line, "Function 'qeocore_factory_set_intf' called less times than expected.");
  if (Mock.qeocore_factory_set_intf_CallbackFunctionPointer != NULL)
    Mock.qeocore_factory_set_intf_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_factory_set_tcp_server_IgnoreBool)
    Mock.qeocore_factory_set_tcp_server_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_factory_set_tcp_server_CallInstance, cmock_line, "Function 'qeocore_factory_set_tcp_server' called less times than expected.");
  if (Mock.qeocore_factory_set_tcp_server_CallbackFunctionPointer != NULL)
    Mock.qeocore_factory_set_tcp_server_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_factory_set_local_tcp_port_IgnoreBool)
    Mock.qeocore_factory_set_local_tcp_port_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_factory_set_local_tcp_port_CallInstance, cmock_line, "Function 'qeocore_factory_set_local_tcp_port' called less times than expected.");
  if (Mock.qeocore_factory_set_local_tcp_port_CallbackFunctionPointer != NULL)
    Mock.qeocore_factory_set_local_tcp_port_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_factory_set_user_data_IgnoreBool)
    Mock.qeocore_factory_set_user_data_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_factory_set_user_data_CallInstance, cmock_line, "Function 'qeocore_factory_set_user_data' called less times than expected.");
  if (Mock.qeocore_factory_set_user_data_CallbackFunctionPointer != NULL)
    Mock.qeocore_factory_set_user_data_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_factory_get_user_data_IgnoreBool)
    Mock.qeocore_factory_get_user_data_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_factory_get_user_data_CallInstance, cmock_line, "Function 'qeocore_factory_get_user_data' called less times than expected.");
  if (Mock.qeocore_factory_get_user_data_CallbackFunctionPointer != NULL)
    Mock.qeocore_factory_get_user_data_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_fwdfactory_new_IgnoreBool)
    Mock.qeocore_fwdfactory_new_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_fwdfactory_new_CallInstance, cmock_line, "Function 'qeocore_fwdfactory_new' called less times than expected.");
  if (Mock.qeocore_fwdfactory_new_CallbackFunctionPointer != NULL)
    Mock.qeocore_fwdfactory_new_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_fwdfactory_close_IgnoreBool)
    Mock.qeocore_fwdfactory_close_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_fwdfactory_close_CallInstance, cmock_line, "Function 'qeocore_fwdfactory_close' called less times than expected.");
  if (Mock.qeocore_fwdfactory_close_CallbackFunctionPointer != NULL)
    Mock.qeocore_fwdfactory_close_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_fwdfactory_set_public_locator_IgnoreBool)
    Mock.qeocore_fwdfactory_set_public_locator_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_fwdfactory_set_public_locator_CallInstance, cmock_line, "Function 'qeocore_fwdfactory_set_public_locator' called less times than expected.");
  if (Mock.qeocore_fwdfactory_set_public_locator_CallbackFunctionPointer != NULL)
    Mock.qeocore_fwdfactory_set_public_locator_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeocore_atexit_IgnoreBool)
    Mock.qeocore_atexit_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeocore_atexit_CallInstance, cmock_line, "Function 'qeocore_atexit' called less times than expected.");
  if (Mock.qeocore_atexit_CallbackFunctionPointer != NULL)
    Mock.qeocore_atexit_CallInstance = CMOCK_GUTS_NONE;
}

void Mockfactory_Init(void)
{
  Mockfactory_Destroy();
}

void Mockfactory_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.qeocore_factory_new_CallbackFunctionPointer = NULL;
  Mock.qeocore_factory_new_CallbackCalls = 0;
  Mock.qeocore_factory_close_CallbackFunctionPointer = NULL;
  Mock.qeocore_factory_close_CallbackCalls = 0;
  Mock.qeocore_factory_init_CallbackFunctionPointer = NULL;
  Mock.qeocore_factory_init_CallbackCalls = 0;
  Mock.qeocore_factory_refresh_policy_CallbackFunctionPointer = NULL;
  Mock.qeocore_factory_refresh_policy_CallbackCalls = 0;
  Mock.qeocore_factory_set_domainid_CallbackFunctionPointer = NULL;
  Mock.qeocore_factory_set_domainid_CallbackCalls = 0;
  Mock.qeocore_factory_get_domainid_CallbackFunctionPointer = NULL;
  Mock.qeocore_factory_get_domainid_CallbackCalls = 0;
  Mock.qeocore_factory_get_realm_id_CallbackFunctionPointer = NULL;
  Mock.qeocore_factory_get_realm_id_CallbackCalls = 0;
  Mock.qeocore_factory_get_user_id_CallbackFunctionPointer = NULL;
  Mock.qeocore_factory_get_user_id_CallbackCalls = 0;
  Mock.qeocore_factory_get_realm_url_CallbackFunctionPointer = NULL;
  Mock.qeocore_factory_get_realm_url_CallbackCalls = 0;
  Mock.qeocore_factory_set_intf_CallbackFunctionPointer = NULL;
  Mock.qeocore_factory_set_intf_CallbackCalls = 0;
  Mock.qeocore_factory_set_tcp_server_CallbackFunctionPointer = NULL;
  Mock.qeocore_factory_set_tcp_server_CallbackCalls = 0;
  Mock.qeocore_factory_set_local_tcp_port_CallbackFunctionPointer = NULL;
  Mock.qeocore_factory_set_local_tcp_port_CallbackCalls = 0;
  Mock.qeocore_factory_set_user_data_CallbackFunctionPointer = NULL;
  Mock.qeocore_factory_set_user_data_CallbackCalls = 0;
  Mock.qeocore_factory_get_user_data_CallbackFunctionPointer = NULL;
  Mock.qeocore_factory_get_user_data_CallbackCalls = 0;
  Mock.qeocore_fwdfactory_new_CallbackFunctionPointer = NULL;
  Mock.qeocore_fwdfactory_new_CallbackCalls = 0;
  Mock.qeocore_fwdfactory_close_CallbackFunctionPointer = NULL;
  Mock.qeocore_fwdfactory_close_CallbackCalls = 0;
  Mock.qeocore_fwdfactory_set_public_locator_CallbackFunctionPointer = NULL;
  Mock.qeocore_fwdfactory_set_public_locator_CallbackCalls = 0;
  Mock.qeocore_atexit_CallbackFunctionPointer = NULL;
  Mock.qeocore_atexit_CallbackCalls = 0;
}

qeo_factory_t* qeocore_factory_new(const qeo_identity_t* id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_factory_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_factory_new_CallInstance);
  Mock.qeocore_factory_new_CallInstance = CMock_Guts_MemNext(Mock.qeocore_factory_new_CallInstance);
  if (Mock.qeocore_factory_new_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_factory_new_FinalReturn;
    Mock.qeocore_factory_new_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_factory_new_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_factory_new_CallbackFunctionPointer(id, Mock.qeocore_factory_new_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_factory_new' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_id), (void*)(id), sizeof(qeo_identity_t), cmock_line, "Function 'qeocore_factory_new' called with unexpected value for argument 'id'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_factory_new(CMOCK_qeocore_factory_new_CALL_INSTANCE* cmock_call_instance, const qeo_identity_t* id)
{
  cmock_call_instance->Expected_id = (qeo_identity_t*)id;
}

void qeocore_factory_new_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_factory_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_new_CALL_INSTANCE));
  CMOCK_qeocore_factory_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_new_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_new_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_factory_new_IgnoreBool = (int)1;
}

void qeocore_factory_new_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const qeo_identity_t* id, qeo_factory_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_new_CALL_INSTANCE));
  CMOCK_qeocore_factory_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_new_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_new_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_factory_new(cmock_call_instance, id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void qeocore_factory_new_StubWithCallback(CMOCK_qeocore_factory_new_CALLBACK Callback)
{
  Mock.qeocore_factory_new_CallbackFunctionPointer = Callback;
}

void qeocore_factory_close(qeo_factory_t* factory)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_factory_close_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_factory_close_CallInstance);
  Mock.qeocore_factory_close_CallInstance = CMock_Guts_MemNext(Mock.qeocore_factory_close_CallInstance);
  if (Mock.qeocore_factory_close_IgnoreBool)
  {
    return;
  }
  if (Mock.qeocore_factory_close_CallbackFunctionPointer != NULL)
  {
    Mock.qeocore_factory_close_CallbackFunctionPointer(factory, Mock.qeocore_factory_close_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_factory_close' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_factory), (void*)(factory), sizeof(qeo_factory_t), cmock_line, "Function 'qeocore_factory_close' called with unexpected value for argument 'factory'.");
}

void CMockExpectParameters_qeocore_factory_close(CMOCK_qeocore_factory_close_CALL_INSTANCE* cmock_call_instance, qeo_factory_t* factory)
{
  cmock_call_instance->Expected_factory = factory;
}

void qeocore_factory_close_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  Mock.qeocore_factory_close_IgnoreBool = (int)1;
}

void qeocore_factory_close_CMockExpect(UNITY_LINE_TYPE cmock_line, qeo_factory_t* factory)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_close_CALL_INSTANCE));
  CMOCK_qeocore_factory_close_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_close_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_close_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_factory_close(cmock_call_instance, factory);
}

void qeocore_factory_close_StubWithCallback(CMOCK_qeocore_factory_close_CALLBACK Callback)
{
  Mock.qeocore_factory_close_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeocore_factory_init(qeo_factory_t* factory, const qeocore_factory_listener_t* listener)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_factory_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_factory_init_CallInstance);
  Mock.qeocore_factory_init_CallInstance = CMock_Guts_MemNext(Mock.qeocore_factory_init_CallInstance);
  if (Mock.qeocore_factory_init_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_factory_init_FinalReturn;
    memcpy(&Mock.qeocore_factory_init_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_factory_init_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_factory_init_CallbackFunctionPointer(factory, listener, Mock.qeocore_factory_init_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_factory_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_factory), (void*)(factory), sizeof(qeo_factory_t), cmock_line, "Function 'qeocore_factory_init' called with unexpected value for argument 'factory'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_listener), (void*)(listener), sizeof(qeocore_factory_listener_t), cmock_line, "Function 'qeocore_factory_init' called with unexpected value for argument 'listener'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_factory_init(CMOCK_qeocore_factory_init_CALL_INSTANCE* cmock_call_instance, qeo_factory_t* factory, const qeocore_factory_listener_t* listener)
{
  cmock_call_instance->Expected_factory = factory;
  cmock_call_instance->Expected_listener = (qeocore_factory_listener_t*)listener;
}

void qeocore_factory_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_init_CALL_INSTANCE));
  CMOCK_qeocore_factory_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_init_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_factory_init_IgnoreBool = (int)1;
}

void qeocore_factory_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_factory_t* factory, const qeocore_factory_listener_t* listener, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_init_CALL_INSTANCE));
  CMOCK_qeocore_factory_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_init_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_factory_init(cmock_call_instance, factory, listener);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeocore_factory_init_StubWithCallback(CMOCK_qeocore_factory_init_CALLBACK Callback)
{
  Mock.qeocore_factory_init_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeocore_factory_refresh_policy(const qeo_factory_t* factory)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_factory_refresh_policy_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_refresh_policy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_factory_refresh_policy_CallInstance);
  Mock.qeocore_factory_refresh_policy_CallInstance = CMock_Guts_MemNext(Mock.qeocore_factory_refresh_policy_CallInstance);
  if (Mock.qeocore_factory_refresh_policy_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_factory_refresh_policy_FinalReturn;
    memcpy(&Mock.qeocore_factory_refresh_policy_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_factory_refresh_policy_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_factory_refresh_policy_CallbackFunctionPointer(factory, Mock.qeocore_factory_refresh_policy_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_factory_refresh_policy' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_factory), (void*)(factory), sizeof(qeo_factory_t), cmock_line, "Function 'qeocore_factory_refresh_policy' called with unexpected value for argument 'factory'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_factory_refresh_policy(CMOCK_qeocore_factory_refresh_policy_CALL_INSTANCE* cmock_call_instance, const qeo_factory_t* factory)
{
  cmock_call_instance->Expected_factory = (qeo_factory_t*)factory;
}

void qeocore_factory_refresh_policy_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_refresh_policy_CALL_INSTANCE));
  CMOCK_qeocore_factory_refresh_policy_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_refresh_policy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_refresh_policy_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_refresh_policy_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_factory_refresh_policy_IgnoreBool = (int)1;
}

void qeocore_factory_refresh_policy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const qeo_factory_t* factory, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_refresh_policy_CALL_INSTANCE));
  CMOCK_qeocore_factory_refresh_policy_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_refresh_policy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_refresh_policy_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_refresh_policy_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_factory_refresh_policy(cmock_call_instance, factory);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeocore_factory_refresh_policy_StubWithCallback(CMOCK_qeocore_factory_refresh_policy_CALLBACK Callback)
{
  Mock.qeocore_factory_refresh_policy_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeocore_factory_set_domainid(qeo_factory_t* factory, qeocore_domain_id_t id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_factory_set_domainid_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_set_domainid_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_factory_set_domainid_CallInstance);
  Mock.qeocore_factory_set_domainid_CallInstance = CMock_Guts_MemNext(Mock.qeocore_factory_set_domainid_CallInstance);
  if (Mock.qeocore_factory_set_domainid_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_factory_set_domainid_FinalReturn;
    memcpy(&Mock.qeocore_factory_set_domainid_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_factory_set_domainid_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_factory_set_domainid_CallbackFunctionPointer(factory, id, Mock.qeocore_factory_set_domainid_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_factory_set_domainid' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_factory), (void*)(factory), sizeof(qeo_factory_t), cmock_line, "Function 'qeocore_factory_set_domainid' called with unexpected value for argument 'factory'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(qeocore_domain_id_t), cmock_line, "Function 'qeocore_factory_set_domainid' called with unexpected value for argument 'id'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_factory_set_domainid(CMOCK_qeocore_factory_set_domainid_CALL_INSTANCE* cmock_call_instance, qeo_factory_t* factory, qeocore_domain_id_t id)
{
  cmock_call_instance->Expected_factory = factory;
  memcpy(&cmock_call_instance->Expected_id, &id, sizeof(qeocore_domain_id_t));
}

void qeocore_factory_set_domainid_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_set_domainid_CALL_INSTANCE));
  CMOCK_qeocore_factory_set_domainid_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_set_domainid_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_set_domainid_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_set_domainid_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_factory_set_domainid_IgnoreBool = (int)1;
}

void qeocore_factory_set_domainid_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_factory_t* factory, qeocore_domain_id_t id, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_set_domainid_CALL_INSTANCE));
  CMOCK_qeocore_factory_set_domainid_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_set_domainid_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_set_domainid_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_set_domainid_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_factory_set_domainid(cmock_call_instance, factory, id);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeocore_factory_set_domainid_StubWithCallback(CMOCK_qeocore_factory_set_domainid_CALLBACK Callback)
{
  Mock.qeocore_factory_set_domainid_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeocore_factory_get_domainid(qeo_factory_t* factory, qeocore_domain_id_t* id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_factory_get_domainid_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_get_domainid_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_factory_get_domainid_CallInstance);
  Mock.qeocore_factory_get_domainid_CallInstance = CMock_Guts_MemNext(Mock.qeocore_factory_get_domainid_CallInstance);
  if (Mock.qeocore_factory_get_domainid_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_factory_get_domainid_FinalReturn;
    memcpy(&Mock.qeocore_factory_get_domainid_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_factory_get_domainid_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_factory_get_domainid_CallbackFunctionPointer(factory, id, Mock.qeocore_factory_get_domainid_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_factory_get_domainid' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_factory), (void*)(factory), sizeof(qeo_factory_t), cmock_line, "Function 'qeocore_factory_get_domainid' called with unexpected value for argument 'factory'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_id), (void*)(id), sizeof(qeocore_domain_id_t), cmock_line, "Function 'qeocore_factory_get_domainid' called with unexpected value for argument 'id'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_factory_get_domainid(CMOCK_qeocore_factory_get_domainid_CALL_INSTANCE* cmock_call_instance, qeo_factory_t* factory, qeocore_domain_id_t* id)
{
  cmock_call_instance->Expected_factory = factory;
  cmock_call_instance->Expected_id = id;
}

void qeocore_factory_get_domainid_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_get_domainid_CALL_INSTANCE));
  CMOCK_qeocore_factory_get_domainid_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_get_domainid_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_get_domainid_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_get_domainid_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_factory_get_domainid_IgnoreBool = (int)1;
}

void qeocore_factory_get_domainid_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_factory_t* factory, qeocore_domain_id_t* id, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_get_domainid_CALL_INSTANCE));
  CMOCK_qeocore_factory_get_domainid_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_get_domainid_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_get_domainid_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_get_domainid_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_factory_get_domainid(cmock_call_instance, factory, id);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeocore_factory_get_domainid_StubWithCallback(CMOCK_qeocore_factory_get_domainid_CALLBACK Callback)
{
  Mock.qeocore_factory_get_domainid_CallbackFunctionPointer = Callback;
}

int64_t qeocore_factory_get_realm_id(qeo_factory_t* factory)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_factory_get_realm_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_get_realm_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_factory_get_realm_id_CallInstance);
  Mock.qeocore_factory_get_realm_id_CallInstance = CMock_Guts_MemNext(Mock.qeocore_factory_get_realm_id_CallInstance);
  if (Mock.qeocore_factory_get_realm_id_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_factory_get_realm_id_FinalReturn;
    memcpy(&Mock.qeocore_factory_get_realm_id_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(int64_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_factory_get_realm_id_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_factory_get_realm_id_CallbackFunctionPointer(factory, Mock.qeocore_factory_get_realm_id_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_factory_get_realm_id' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_factory), (void*)(factory), sizeof(qeo_factory_t), cmock_line, "Function 'qeocore_factory_get_realm_id' called with unexpected value for argument 'factory'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_factory_get_realm_id(CMOCK_qeocore_factory_get_realm_id_CALL_INSTANCE* cmock_call_instance, qeo_factory_t* factory)
{
  cmock_call_instance->Expected_factory = factory;
}

void qeocore_factory_get_realm_id_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int64_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_get_realm_id_CALL_INSTANCE));
  CMOCK_qeocore_factory_get_realm_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_get_realm_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_get_realm_id_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_get_realm_id_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_factory_get_realm_id_IgnoreBool = (int)1;
}

void qeocore_factory_get_realm_id_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_factory_t* factory, int64_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_get_realm_id_CALL_INSTANCE));
  CMOCK_qeocore_factory_get_realm_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_get_realm_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_get_realm_id_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_get_realm_id_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_factory_get_realm_id(cmock_call_instance, factory);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(int64_t));
}

void qeocore_factory_get_realm_id_StubWithCallback(CMOCK_qeocore_factory_get_realm_id_CALLBACK Callback)
{
  Mock.qeocore_factory_get_realm_id_CallbackFunctionPointer = Callback;
}

int64_t qeocore_factory_get_user_id(qeo_factory_t* factory)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_factory_get_user_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_get_user_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_factory_get_user_id_CallInstance);
  Mock.qeocore_factory_get_user_id_CallInstance = CMock_Guts_MemNext(Mock.qeocore_factory_get_user_id_CallInstance);
  if (Mock.qeocore_factory_get_user_id_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_factory_get_user_id_FinalReturn;
    memcpy(&Mock.qeocore_factory_get_user_id_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(int64_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_factory_get_user_id_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_factory_get_user_id_CallbackFunctionPointer(factory, Mock.qeocore_factory_get_user_id_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_factory_get_user_id' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_factory), (void*)(factory), sizeof(qeo_factory_t), cmock_line, "Function 'qeocore_factory_get_user_id' called with unexpected value for argument 'factory'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_factory_get_user_id(CMOCK_qeocore_factory_get_user_id_CALL_INSTANCE* cmock_call_instance, qeo_factory_t* factory)
{
  cmock_call_instance->Expected_factory = factory;
}

void qeocore_factory_get_user_id_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int64_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_get_user_id_CALL_INSTANCE));
  CMOCK_qeocore_factory_get_user_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_get_user_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_get_user_id_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_get_user_id_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_factory_get_user_id_IgnoreBool = (int)1;
}

void qeocore_factory_get_user_id_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_factory_t* factory, int64_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_get_user_id_CALL_INSTANCE));
  CMOCK_qeocore_factory_get_user_id_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_get_user_id_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_get_user_id_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_get_user_id_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_factory_get_user_id(cmock_call_instance, factory);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(int64_t));
}

void qeocore_factory_get_user_id_StubWithCallback(CMOCK_qeocore_factory_get_user_id_CALLBACK Callback)
{
  Mock.qeocore_factory_get_user_id_CallbackFunctionPointer = Callback;
}

const char* qeocore_factory_get_realm_url(qeo_factory_t* factory)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_factory_get_realm_url_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_get_realm_url_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_factory_get_realm_url_CallInstance);
  Mock.qeocore_factory_get_realm_url_CallInstance = CMock_Guts_MemNext(Mock.qeocore_factory_get_realm_url_CallInstance);
  if (Mock.qeocore_factory_get_realm_url_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_factory_get_realm_url_FinalReturn;
    Mock.qeocore_factory_get_realm_url_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_factory_get_realm_url_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_factory_get_realm_url_CallbackFunctionPointer(factory, Mock.qeocore_factory_get_realm_url_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_factory_get_realm_url' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_factory), (void*)(factory), sizeof(qeo_factory_t), cmock_line, "Function 'qeocore_factory_get_realm_url' called with unexpected value for argument 'factory'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_factory_get_realm_url(CMOCK_qeocore_factory_get_realm_url_CALL_INSTANCE* cmock_call_instance, qeo_factory_t* factory)
{
  cmock_call_instance->Expected_factory = factory;
}

void qeocore_factory_get_realm_url_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, char* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_get_realm_url_CALL_INSTANCE));
  CMOCK_qeocore_factory_get_realm_url_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_get_realm_url_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_get_realm_url_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_get_realm_url_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_factory_get_realm_url_IgnoreBool = (int)1;
}

void qeocore_factory_get_realm_url_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_factory_t* factory, char* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_get_realm_url_CALL_INSTANCE));
  CMOCK_qeocore_factory_get_realm_url_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_get_realm_url_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_get_realm_url_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_get_realm_url_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_factory_get_realm_url(cmock_call_instance, factory);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void qeocore_factory_get_realm_url_StubWithCallback(CMOCK_qeocore_factory_get_realm_url_CALLBACK Callback)
{
  Mock.qeocore_factory_get_realm_url_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeocore_factory_set_intf(qeo_factory_t* factory, const char* interfaces)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_factory_set_intf_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_set_intf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_factory_set_intf_CallInstance);
  Mock.qeocore_factory_set_intf_CallInstance = CMock_Guts_MemNext(Mock.qeocore_factory_set_intf_CallInstance);
  if (Mock.qeocore_factory_set_intf_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_factory_set_intf_FinalReturn;
    memcpy(&Mock.qeocore_factory_set_intf_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_factory_set_intf_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_factory_set_intf_CallbackFunctionPointer(factory, interfaces, Mock.qeocore_factory_set_intf_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_factory_set_intf' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_factory), (void*)(factory), sizeof(qeo_factory_t), cmock_line, "Function 'qeocore_factory_set_intf' called with unexpected value for argument 'factory'.");
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_interfaces, interfaces, cmock_line, "Function 'qeocore_factory_set_intf' called with unexpected value for argument 'interfaces'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_factory_set_intf(CMOCK_qeocore_factory_set_intf_CALL_INSTANCE* cmock_call_instance, qeo_factory_t* factory, const char* interfaces)
{
  cmock_call_instance->Expected_factory = factory;
  cmock_call_instance->Expected_interfaces = (char*)interfaces;
}

void qeocore_factory_set_intf_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_set_intf_CALL_INSTANCE));
  CMOCK_qeocore_factory_set_intf_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_set_intf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_set_intf_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_set_intf_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_factory_set_intf_IgnoreBool = (int)1;
}

void qeocore_factory_set_intf_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_factory_t* factory, const char* interfaces, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_set_intf_CALL_INSTANCE));
  CMOCK_qeocore_factory_set_intf_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_set_intf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_set_intf_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_set_intf_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_factory_set_intf(cmock_call_instance, factory, interfaces);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeocore_factory_set_intf_StubWithCallback(CMOCK_qeocore_factory_set_intf_CALLBACK Callback)
{
  Mock.qeocore_factory_set_intf_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeocore_factory_set_tcp_server(qeo_factory_t* factory, const char* tcp_server)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_factory_set_tcp_server_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_set_tcp_server_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_factory_set_tcp_server_CallInstance);
  Mock.qeocore_factory_set_tcp_server_CallInstance = CMock_Guts_MemNext(Mock.qeocore_factory_set_tcp_server_CallInstance);
  if (Mock.qeocore_factory_set_tcp_server_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_factory_set_tcp_server_FinalReturn;
    memcpy(&Mock.qeocore_factory_set_tcp_server_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_factory_set_tcp_server_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_factory_set_tcp_server_CallbackFunctionPointer(factory, tcp_server, Mock.qeocore_factory_set_tcp_server_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_factory_set_tcp_server' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_factory), (void*)(factory), sizeof(qeo_factory_t), cmock_line, "Function 'qeocore_factory_set_tcp_server' called with unexpected value for argument 'factory'.");
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_tcp_server, tcp_server, cmock_line, "Function 'qeocore_factory_set_tcp_server' called with unexpected value for argument 'tcp_server'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_factory_set_tcp_server(CMOCK_qeocore_factory_set_tcp_server_CALL_INSTANCE* cmock_call_instance, qeo_factory_t* factory, const char* tcp_server)
{
  cmock_call_instance->Expected_factory = factory;
  cmock_call_instance->Expected_tcp_server = (char*)tcp_server;
}

void qeocore_factory_set_tcp_server_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_set_tcp_server_CALL_INSTANCE));
  CMOCK_qeocore_factory_set_tcp_server_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_set_tcp_server_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_set_tcp_server_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_set_tcp_server_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_factory_set_tcp_server_IgnoreBool = (int)1;
}

void qeocore_factory_set_tcp_server_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_factory_t* factory, const char* tcp_server, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_set_tcp_server_CALL_INSTANCE));
  CMOCK_qeocore_factory_set_tcp_server_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_set_tcp_server_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_set_tcp_server_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_set_tcp_server_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_factory_set_tcp_server(cmock_call_instance, factory, tcp_server);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeocore_factory_set_tcp_server_StubWithCallback(CMOCK_qeocore_factory_set_tcp_server_CALLBACK Callback)
{
  Mock.qeocore_factory_set_tcp_server_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeocore_factory_set_local_tcp_port(qeo_factory_t* factory, const char* local_port)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_factory_set_local_tcp_port_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_set_local_tcp_port_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_factory_set_local_tcp_port_CallInstance);
  Mock.qeocore_factory_set_local_tcp_port_CallInstance = CMock_Guts_MemNext(Mock.qeocore_factory_set_local_tcp_port_CallInstance);
  if (Mock.qeocore_factory_set_local_tcp_port_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_factory_set_local_tcp_port_FinalReturn;
    memcpy(&Mock.qeocore_factory_set_local_tcp_port_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_factory_set_local_tcp_port_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_factory_set_local_tcp_port_CallbackFunctionPointer(factory, local_port, Mock.qeocore_factory_set_local_tcp_port_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_factory_set_local_tcp_port' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_factory), (void*)(factory), sizeof(qeo_factory_t), cmock_line, "Function 'qeocore_factory_set_local_tcp_port' called with unexpected value for argument 'factory'.");
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_local_port, local_port, cmock_line, "Function 'qeocore_factory_set_local_tcp_port' called with unexpected value for argument 'local_port'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_factory_set_local_tcp_port(CMOCK_qeocore_factory_set_local_tcp_port_CALL_INSTANCE* cmock_call_instance, qeo_factory_t* factory, const char* local_port)
{
  cmock_call_instance->Expected_factory = factory;
  cmock_call_instance->Expected_local_port = (char*)local_port;
}

void qeocore_factory_set_local_tcp_port_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_set_local_tcp_port_CALL_INSTANCE));
  CMOCK_qeocore_factory_set_local_tcp_port_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_set_local_tcp_port_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_set_local_tcp_port_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_set_local_tcp_port_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_factory_set_local_tcp_port_IgnoreBool = (int)1;
}

void qeocore_factory_set_local_tcp_port_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_factory_t* factory, const char* local_port, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_set_local_tcp_port_CALL_INSTANCE));
  CMOCK_qeocore_factory_set_local_tcp_port_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_set_local_tcp_port_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_set_local_tcp_port_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_set_local_tcp_port_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_factory_set_local_tcp_port(cmock_call_instance, factory, local_port);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeocore_factory_set_local_tcp_port_StubWithCallback(CMOCK_qeocore_factory_set_local_tcp_port_CALLBACK Callback)
{
  Mock.qeocore_factory_set_local_tcp_port_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeocore_factory_set_user_data(qeo_factory_t* factory, uintptr_t userdata)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_factory_set_user_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_set_user_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_factory_set_user_data_CallInstance);
  Mock.qeocore_factory_set_user_data_CallInstance = CMock_Guts_MemNext(Mock.qeocore_factory_set_user_data_CallInstance);
  if (Mock.qeocore_factory_set_user_data_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_factory_set_user_data_FinalReturn;
    memcpy(&Mock.qeocore_factory_set_user_data_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_factory_set_user_data_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_factory_set_user_data_CallbackFunctionPointer(factory, userdata, Mock.qeocore_factory_set_user_data_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_factory_set_user_data' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_factory), (void*)(factory), sizeof(qeo_factory_t), cmock_line, "Function 'qeocore_factory_set_user_data' called with unexpected value for argument 'factory'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_userdata), (void*)(&userdata), sizeof(uintptr_t), cmock_line, "Function 'qeocore_factory_set_user_data' called with unexpected value for argument 'userdata'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_factory_set_user_data(CMOCK_qeocore_factory_set_user_data_CALL_INSTANCE* cmock_call_instance, qeo_factory_t* factory, uintptr_t userdata)
{
  cmock_call_instance->Expected_factory = factory;
  memcpy(&cmock_call_instance->Expected_userdata, &userdata, sizeof(uintptr_t));
}

void qeocore_factory_set_user_data_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_set_user_data_CALL_INSTANCE));
  CMOCK_qeocore_factory_set_user_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_set_user_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_set_user_data_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_set_user_data_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_factory_set_user_data_IgnoreBool = (int)1;
}

void qeocore_factory_set_user_data_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_factory_t* factory, uintptr_t userdata, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_set_user_data_CALL_INSTANCE));
  CMOCK_qeocore_factory_set_user_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_set_user_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_set_user_data_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_set_user_data_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_factory_set_user_data(cmock_call_instance, factory, userdata);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeocore_factory_set_user_data_StubWithCallback(CMOCK_qeocore_factory_set_user_data_CALLBACK Callback)
{
  Mock.qeocore_factory_set_user_data_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeocore_factory_get_user_data(qeo_factory_t* factory, uintptr_t* userdata)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_factory_get_user_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_get_user_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_factory_get_user_data_CallInstance);
  Mock.qeocore_factory_get_user_data_CallInstance = CMock_Guts_MemNext(Mock.qeocore_factory_get_user_data_CallInstance);
  if (Mock.qeocore_factory_get_user_data_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_factory_get_user_data_FinalReturn;
    memcpy(&Mock.qeocore_factory_get_user_data_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_factory_get_user_data_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_factory_get_user_data_CallbackFunctionPointer(factory, userdata, Mock.qeocore_factory_get_user_data_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_factory_get_user_data' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_factory), (void*)(factory), sizeof(qeo_factory_t), cmock_line, "Function 'qeocore_factory_get_user_data' called with unexpected value for argument 'factory'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_userdata), (void*)(userdata), sizeof(uintptr_t), cmock_line, "Function 'qeocore_factory_get_user_data' called with unexpected value for argument 'userdata'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_factory_get_user_data(CMOCK_qeocore_factory_get_user_data_CALL_INSTANCE* cmock_call_instance, qeo_factory_t* factory, uintptr_t* userdata)
{
  cmock_call_instance->Expected_factory = factory;
  cmock_call_instance->Expected_userdata = userdata;
}

void qeocore_factory_get_user_data_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_get_user_data_CALL_INSTANCE));
  CMOCK_qeocore_factory_get_user_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_get_user_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_get_user_data_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_get_user_data_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_factory_get_user_data_IgnoreBool = (int)1;
}

void qeocore_factory_get_user_data_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_factory_t* factory, uintptr_t* userdata, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_factory_get_user_data_CALL_INSTANCE));
  CMOCK_qeocore_factory_get_user_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_factory_get_user_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_factory_get_user_data_CallInstance = CMock_Guts_MemChain(Mock.qeocore_factory_get_user_data_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_factory_get_user_data(cmock_call_instance, factory, userdata);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeocore_factory_get_user_data_StubWithCallback(CMOCK_qeocore_factory_get_user_data_CALLBACK Callback)
{
  Mock.qeocore_factory_get_user_data_CallbackFunctionPointer = Callback;
}

qeo_factory_t* qeocore_fwdfactory_new(qeocore_on_fwdfactory_get_public_locator cb, const char* local_port)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_fwdfactory_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_fwdfactory_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_fwdfactory_new_CallInstance);
  Mock.qeocore_fwdfactory_new_CallInstance = CMock_Guts_MemNext(Mock.qeocore_fwdfactory_new_CallInstance);
  if (Mock.qeocore_fwdfactory_new_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_fwdfactory_new_FinalReturn;
    Mock.qeocore_fwdfactory_new_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_fwdfactory_new_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_fwdfactory_new_CallbackFunctionPointer(cb, local_port, Mock.qeocore_fwdfactory_new_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_fwdfactory_new' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb), sizeof(qeocore_on_fwdfactory_get_public_locator), cmock_line, "Function 'qeocore_fwdfactory_new' called with unexpected value for argument 'cb'.");
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_local_port, local_port, cmock_line, "Function 'qeocore_fwdfactory_new' called with unexpected value for argument 'local_port'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_fwdfactory_new(CMOCK_qeocore_fwdfactory_new_CALL_INSTANCE* cmock_call_instance, qeocore_on_fwdfactory_get_public_locator cb, const char* local_port)
{
  memcpy(&cmock_call_instance->Expected_cb, &cb, sizeof(qeocore_on_fwdfactory_get_public_locator));
  cmock_call_instance->Expected_local_port = (char*)local_port;
}

void qeocore_fwdfactory_new_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_factory_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_fwdfactory_new_CALL_INSTANCE));
  CMOCK_qeocore_fwdfactory_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_fwdfactory_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_fwdfactory_new_CallInstance = CMock_Guts_MemChain(Mock.qeocore_fwdfactory_new_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_fwdfactory_new_IgnoreBool = (int)1;
}

void qeocore_fwdfactory_new_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeocore_on_fwdfactory_get_public_locator cb, const char* local_port, qeo_factory_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_fwdfactory_new_CALL_INSTANCE));
  CMOCK_qeocore_fwdfactory_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_fwdfactory_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_fwdfactory_new_CallInstance = CMock_Guts_MemChain(Mock.qeocore_fwdfactory_new_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_fwdfactory_new(cmock_call_instance, cb, local_port);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void qeocore_fwdfactory_new_StubWithCallback(CMOCK_qeocore_fwdfactory_new_CALLBACK Callback)
{
  Mock.qeocore_fwdfactory_new_CallbackFunctionPointer = Callback;
}

void qeocore_fwdfactory_close(qeo_factory_t* factory)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_fwdfactory_close_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_fwdfactory_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_fwdfactory_close_CallInstance);
  Mock.qeocore_fwdfactory_close_CallInstance = CMock_Guts_MemNext(Mock.qeocore_fwdfactory_close_CallInstance);
  if (Mock.qeocore_fwdfactory_close_IgnoreBool)
  {
    return;
  }
  if (Mock.qeocore_fwdfactory_close_CallbackFunctionPointer != NULL)
  {
    Mock.qeocore_fwdfactory_close_CallbackFunctionPointer(factory, Mock.qeocore_fwdfactory_close_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_fwdfactory_close' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_factory), (void*)(factory), sizeof(qeo_factory_t), cmock_line, "Function 'qeocore_fwdfactory_close' called with unexpected value for argument 'factory'.");
}

void CMockExpectParameters_qeocore_fwdfactory_close(CMOCK_qeocore_fwdfactory_close_CALL_INSTANCE* cmock_call_instance, qeo_factory_t* factory)
{
  cmock_call_instance->Expected_factory = factory;
}

void qeocore_fwdfactory_close_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  Mock.qeocore_fwdfactory_close_IgnoreBool = (int)1;
}

void qeocore_fwdfactory_close_CMockExpect(UNITY_LINE_TYPE cmock_line, qeo_factory_t* factory)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_fwdfactory_close_CALL_INSTANCE));
  CMOCK_qeocore_fwdfactory_close_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_fwdfactory_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_fwdfactory_close_CallInstance = CMock_Guts_MemChain(Mock.qeocore_fwdfactory_close_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_fwdfactory_close(cmock_call_instance, factory);
}

void qeocore_fwdfactory_close_StubWithCallback(CMOCK_qeocore_fwdfactory_close_CALLBACK Callback)
{
  Mock.qeocore_fwdfactory_close_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeocore_fwdfactory_set_public_locator(qeo_factory_t* factory, const char* ip_address, int port)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_fwdfactory_set_public_locator_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_fwdfactory_set_public_locator_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_fwdfactory_set_public_locator_CallInstance);
  Mock.qeocore_fwdfactory_set_public_locator_CallInstance = CMock_Guts_MemNext(Mock.qeocore_fwdfactory_set_public_locator_CallInstance);
  if (Mock.qeocore_fwdfactory_set_public_locator_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeocore_fwdfactory_set_public_locator_FinalReturn;
    memcpy(&Mock.qeocore_fwdfactory_set_public_locator_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeocore_fwdfactory_set_public_locator_CallbackFunctionPointer != NULL)
  {
    return Mock.qeocore_fwdfactory_set_public_locator_CallbackFunctionPointer(factory, ip_address, port, Mock.qeocore_fwdfactory_set_public_locator_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_fwdfactory_set_public_locator' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_factory), (void*)(factory), sizeof(qeo_factory_t), cmock_line, "Function 'qeocore_fwdfactory_set_public_locator' called with unexpected value for argument 'factory'.");
  UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_ip_address, ip_address, cmock_line, "Function 'qeocore_fwdfactory_set_public_locator' called with unexpected value for argument 'ip_address'.");
  UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_port, port, cmock_line, "Function 'qeocore_fwdfactory_set_public_locator' called with unexpected value for argument 'port'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeocore_fwdfactory_set_public_locator(CMOCK_qeocore_fwdfactory_set_public_locator_CALL_INSTANCE* cmock_call_instance, qeo_factory_t* factory, const char* ip_address, int port)
{
  cmock_call_instance->Expected_factory = factory;
  cmock_call_instance->Expected_ip_address = (char*)ip_address;
  cmock_call_instance->Expected_port = port;
}

void qeocore_fwdfactory_set_public_locator_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_fwdfactory_set_public_locator_CALL_INSTANCE));
  CMOCK_qeocore_fwdfactory_set_public_locator_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_fwdfactory_set_public_locator_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_fwdfactory_set_public_locator_CallInstance = CMock_Guts_MemChain(Mock.qeocore_fwdfactory_set_public_locator_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeocore_fwdfactory_set_public_locator_IgnoreBool = (int)1;
}

void qeocore_fwdfactory_set_public_locator_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_factory_t* factory, const char* ip_address, int port, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_fwdfactory_set_public_locator_CALL_INSTANCE));
  CMOCK_qeocore_fwdfactory_set_public_locator_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_fwdfactory_set_public_locator_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_fwdfactory_set_public_locator_CallInstance = CMock_Guts_MemChain(Mock.qeocore_fwdfactory_set_public_locator_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_fwdfactory_set_public_locator(cmock_call_instance, factory, ip_address, port);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeocore_fwdfactory_set_public_locator_StubWithCallback(CMOCK_qeocore_fwdfactory_set_public_locator_CALLBACK Callback)
{
  Mock.qeocore_fwdfactory_set_public_locator_CallbackFunctionPointer = Callback;
}

void qeocore_atexit(const qeocore_exit_cb cb)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeocore_atexit_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_atexit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeocore_atexit_CallInstance);
  Mock.qeocore_atexit_CallInstance = CMock_Guts_MemNext(Mock.qeocore_atexit_CallInstance);
  if (Mock.qeocore_atexit_IgnoreBool)
  {
    return;
  }
  if (Mock.qeocore_atexit_CallbackFunctionPointer != NULL)
  {
    Mock.qeocore_atexit_CallbackFunctionPointer(cb, Mock.qeocore_atexit_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeocore_atexit' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb), sizeof(qeocore_exit_cb), cmock_line, "Function 'qeocore_atexit' called with unexpected value for argument 'cb'.");
}

void CMockExpectParameters_qeocore_atexit(CMOCK_qeocore_atexit_CALL_INSTANCE* cmock_call_instance, const qeocore_exit_cb cb)
{
  memcpy(&cmock_call_instance->Expected_cb, &cb, sizeof(qeocore_exit_cb));
}

void qeocore_atexit_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  Mock.qeocore_atexit_IgnoreBool = (int)1;
}

void qeocore_atexit_CMockExpect(UNITY_LINE_TYPE cmock_line, const qeocore_exit_cb cb)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeocore_atexit_CALL_INSTANCE));
  CMOCK_qeocore_atexit_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeocore_atexit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeocore_atexit_CallInstance = CMock_Guts_MemChain(Mock.qeocore_atexit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeocore_atexit(cmock_call_instance, cb);
}

void qeocore_atexit_StubWithCallback(CMOCK_qeocore_atexit_CALLBACK Callback)
{
  Mock.qeocore_atexit_CallbackFunctionPointer = Callback;
}

