/*
 * Copyright (c) 2014 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#define NO_TEST_ASSERT_EQUAL_MEMORY_MESSAGE
#include "unity.h"
#include "cmock.h"
#include "Mocklist.h"

typedef struct _CMOCK_list_new_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  list_t* ReturnVal;

} CMOCK_list_new_CALL_INSTANCE;

typedef struct _CMOCK_list_free_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  list_t* Expected_list;

} CMOCK_list_free_CALL_INSTANCE;

typedef struct _CMOCK_list_length_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  list_t* Expected_list;

} CMOCK_list_length_CALL_INSTANCE;

typedef struct _CMOCK_list_add_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  list_t* Expected_list;
  void* Expected_data;

} CMOCK_list_add_CALL_INSTANCE;

typedef struct _CMOCK_list_remove_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  list_t* Expected_list;
  void* Expected_data;

} CMOCK_list_remove_CALL_INSTANCE;

typedef struct _CMOCK_list_foreach_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  list_t* Expected_list;
  list_iterate_callback Expected_cb;
  uintptr_t Expected_userdata;

} CMOCK_list_foreach_CALL_INSTANCE;

static struct MocklistInstance
{
  int list_new_IgnoreBool;
  list_t* list_new_FinalReturn;
  CMOCK_list_new_CALLBACK list_new_CallbackFunctionPointer;
  int list_new_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE list_new_CallInstance;
  int list_free_IgnoreBool;
  CMOCK_list_free_CALLBACK list_free_CallbackFunctionPointer;
  int list_free_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE list_free_CallInstance;
  int list_length_IgnoreBool;
  int list_length_FinalReturn;
  CMOCK_list_length_CALLBACK list_length_CallbackFunctionPointer;
  int list_length_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE list_length_CallInstance;
  int list_add_IgnoreBool;
  qeo_retcode_t list_add_FinalReturn;
  CMOCK_list_add_CALLBACK list_add_CallbackFunctionPointer;
  int list_add_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE list_add_CallInstance;
  int list_remove_IgnoreBool;
  qeo_retcode_t list_remove_FinalReturn;
  CMOCK_list_remove_CALLBACK list_remove_CallbackFunctionPointer;
  int list_remove_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE list_remove_CallInstance;
  int list_foreach_IgnoreBool;
  qeo_retcode_t list_foreach_FinalReturn;
  CMOCK_list_foreach_CALLBACK list_foreach_CallbackFunctionPointer;
  int list_foreach_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE list_foreach_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocklist_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.list_new_IgnoreBool)
    Mock.list_new_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.list_new_CallInstance, cmock_line, "Function 'list_new' called less times than expected.");
  if (Mock.list_new_CallbackFunctionPointer != NULL)
    Mock.list_new_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.list_free_IgnoreBool)
    Mock.list_free_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.list_free_CallInstance, cmock_line, "Function 'list_free' called less times than expected.");
  if (Mock.list_free_CallbackFunctionPointer != NULL)
    Mock.list_free_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.list_length_IgnoreBool)
    Mock.list_length_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.list_length_CallInstance, cmock_line, "Function 'list_length' called less times than expected.");
  if (Mock.list_length_CallbackFunctionPointer != NULL)
    Mock.list_length_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.list_add_IgnoreBool)
    Mock.list_add_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.list_add_CallInstance, cmock_line, "Function 'list_add' called less times than expected.");
  if (Mock.list_add_CallbackFunctionPointer != NULL)
    Mock.list_add_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.list_remove_IgnoreBool)
    Mock.list_remove_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.list_remove_CallInstance, cmock_line, "Function 'list_remove' called less times than expected.");
  if (Mock.list_remove_CallbackFunctionPointer != NULL)
    Mock.list_remove_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.list_foreach_IgnoreBool)
    Mock.list_foreach_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.list_foreach_CallInstance, cmock_line, "Function 'list_foreach' called less times than expected.");
  if (Mock.list_foreach_CallbackFunctionPointer != NULL)
    Mock.list_foreach_CallInstance = CMOCK_GUTS_NONE;
}

void Mocklist_Init(void)
{
  Mocklist_Destroy();
}

void Mocklist_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.list_new_CallbackFunctionPointer = NULL;
  Mock.list_new_CallbackCalls = 0;
  Mock.list_free_CallbackFunctionPointer = NULL;
  Mock.list_free_CallbackCalls = 0;
  Mock.list_length_CallbackFunctionPointer = NULL;
  Mock.list_length_CallbackCalls = 0;
  Mock.list_add_CallbackFunctionPointer = NULL;
  Mock.list_add_CallbackCalls = 0;
  Mock.list_remove_CallbackFunctionPointer = NULL;
  Mock.list_remove_CallbackCalls = 0;
  Mock.list_foreach_CallbackFunctionPointer = NULL;
  Mock.list_foreach_CallbackCalls = 0;
}

list_t* list_new(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_list_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_list_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.list_new_CallInstance);
  Mock.list_new_CallInstance = CMock_Guts_MemNext(Mock.list_new_CallInstance);
  if (Mock.list_new_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.list_new_FinalReturn;
    Mock.list_new_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.list_new_CallbackFunctionPointer != NULL)
  {
    return Mock.list_new_CallbackFunctionPointer(Mock.list_new_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'list_new' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void list_new_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, list_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_list_new_CALL_INSTANCE));
  CMOCK_list_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_list_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.list_new_CallInstance = CMock_Guts_MemChain(Mock.list_new_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.list_new_IgnoreBool = (int)1;
}

void list_new_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, list_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_list_new_CALL_INSTANCE));
  CMOCK_list_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_list_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.list_new_CallInstance = CMock_Guts_MemChain(Mock.list_new_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void list_new_StubWithCallback(CMOCK_list_new_CALLBACK Callback)
{
  Mock.list_new_CallbackFunctionPointer = Callback;
}

void list_free(list_t* list)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_list_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_list_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.list_free_CallInstance);
  Mock.list_free_CallInstance = CMock_Guts_MemNext(Mock.list_free_CallInstance);
  if (Mock.list_free_IgnoreBool)
  {
    return;
  }
  if (Mock.list_free_CallbackFunctionPointer != NULL)
  {
    Mock.list_free_CallbackFunctionPointer(list, Mock.list_free_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'list_free' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_list), (void*)(list), sizeof(list_t), cmock_line, "Function 'list_free' called with unexpected value for argument 'list'.");
}

void CMockExpectParameters_list_free(CMOCK_list_free_CALL_INSTANCE* cmock_call_instance, list_t* list)
{
  cmock_call_instance->Expected_list = list;
}

void list_free_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  Mock.list_free_IgnoreBool = (int)1;
}

void list_free_CMockExpect(UNITY_LINE_TYPE cmock_line, list_t* list)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_list_free_CALL_INSTANCE));
  CMOCK_list_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_list_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.list_free_CallInstance = CMock_Guts_MemChain(Mock.list_free_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_list_free(cmock_call_instance, list);
}

void list_free_StubWithCallback(CMOCK_list_free_CALLBACK Callback)
{
  Mock.list_free_CallbackFunctionPointer = Callback;
}

int list_length(const list_t* list)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_list_length_CALL_INSTANCE* cmock_call_instance = (CMOCK_list_length_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.list_length_CallInstance);
  Mock.list_length_CallInstance = CMock_Guts_MemNext(Mock.list_length_CallInstance);
  if (Mock.list_length_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.list_length_FinalReturn;
    Mock.list_length_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.list_length_CallbackFunctionPointer != NULL)
  {
    return Mock.list_length_CallbackFunctionPointer(list, Mock.list_length_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'list_length' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_list), (void*)(list), sizeof(list_t), cmock_line, "Function 'list_length' called with unexpected value for argument 'list'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_list_length(CMOCK_list_length_CALL_INSTANCE* cmock_call_instance, const list_t* list)
{
  cmock_call_instance->Expected_list = (list_t*)list;
}

void list_length_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_list_length_CALL_INSTANCE));
  CMOCK_list_length_CALL_INSTANCE* cmock_call_instance = (CMOCK_list_length_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.list_length_CallInstance = CMock_Guts_MemChain(Mock.list_length_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.list_length_IgnoreBool = (int)1;
}

void list_length_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const list_t* list, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_list_length_CALL_INSTANCE));
  CMOCK_list_length_CALL_INSTANCE* cmock_call_instance = (CMOCK_list_length_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.list_length_CallInstance = CMock_Guts_MemChain(Mock.list_length_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_list_length(cmock_call_instance, list);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void list_length_StubWithCallback(CMOCK_list_length_CALLBACK Callback)
{
  Mock.list_length_CallbackFunctionPointer = Callback;
}

qeo_retcode_t list_add(list_t* list, void* data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_list_add_CALL_INSTANCE* cmock_call_instance = (CMOCK_list_add_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.list_add_CallInstance);
  Mock.list_add_CallInstance = CMock_Guts_MemNext(Mock.list_add_CallInstance);
  if (Mock.list_add_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.list_add_FinalReturn;
    memcpy(&Mock.list_add_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.list_add_CallbackFunctionPointer != NULL)
  {
    return Mock.list_add_CallbackFunctionPointer(list, data, Mock.list_add_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'list_add' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_list), (void*)(list), sizeof(list_t), cmock_line, "Function 'list_add' called with unexpected value for argument 'list'.");
  UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_data, data, cmock_line, "Function 'list_add' called with unexpected value for argument 'data'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_list_add(CMOCK_list_add_CALL_INSTANCE* cmock_call_instance, list_t* list, void* data)
{
  cmock_call_instance->Expected_list = list;
  cmock_call_instance->Expected_data = data;
}

void list_add_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_list_add_CALL_INSTANCE));
  CMOCK_list_add_CALL_INSTANCE* cmock_call_instance = (CMOCK_list_add_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.list_add_CallInstance = CMock_Guts_MemChain(Mock.list_add_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.list_add_IgnoreBool = (int)1;
}

void list_add_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, list_t* list, void* data, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_list_add_CALL_INSTANCE));
  CMOCK_list_add_CALL_INSTANCE* cmock_call_instance = (CMOCK_list_add_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.list_add_CallInstance = CMock_Guts_MemChain(Mock.list_add_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_list_add(cmock_call_instance, list, data);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void list_add_StubWithCallback(CMOCK_list_add_CALLBACK Callback)
{
  Mock.list_add_CallbackFunctionPointer = Callback;
}

qeo_retcode_t list_remove(list_t* list, const void* data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_list_remove_CALL_INSTANCE* cmock_call_instance = (CMOCK_list_remove_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.list_remove_CallInstance);
  Mock.list_remove_CallInstance = CMock_Guts_MemNext(Mock.list_remove_CallInstance);
  if (Mock.list_remove_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.list_remove_FinalReturn;
    memcpy(&Mock.list_remove_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.list_remove_CallbackFunctionPointer != NULL)
  {
    return Mock.list_remove_CallbackFunctionPointer(list, data, Mock.list_remove_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'list_remove' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_list), (void*)(list), sizeof(list_t), cmock_line, "Function 'list_remove' called with unexpected value for argument 'list'.");
  UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_data, data, cmock_line, "Function 'list_remove' called with unexpected value for argument 'data'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_list_remove(CMOCK_list_remove_CALL_INSTANCE* cmock_call_instance, list_t* list, const void* data)
{
  cmock_call_instance->Expected_list = list;
  cmock_call_instance->Expected_data = (void*)data;
}

void list_remove_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_list_remove_CALL_INSTANCE));
  CMOCK_list_remove_CALL_INSTANCE* cmock_call_instance = (CMOCK_list_remove_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.list_remove_CallInstance = CMock_Guts_MemChain(Mock.list_remove_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.list_remove_IgnoreBool = (int)1;
}

void list_remove_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, list_t* list, const void* data, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_list_remove_CALL_INSTANCE));
  CMOCK_list_remove_CALL_INSTANCE* cmock_call_instance = (CMOCK_list_remove_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.list_remove_CallInstance = CMock_Guts_MemChain(Mock.list_remove_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_list_remove(cmock_call_instance, list, data);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void list_remove_StubWithCallback(CMOCK_list_remove_CALLBACK Callback)
{
  Mock.list_remove_CallbackFunctionPointer = Callback;
}

qeo_retcode_t list_foreach(list_t* list, list_iterate_callback cb, uintptr_t userdata)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_list_foreach_CALL_INSTANCE* cmock_call_instance = (CMOCK_list_foreach_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.list_foreach_CallInstance);
  Mock.list_foreach_CallInstance = CMock_Guts_MemNext(Mock.list_foreach_CallInstance);
  if (Mock.list_foreach_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.list_foreach_FinalReturn;
    memcpy(&Mock.list_foreach_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.list_foreach_CallbackFunctionPointer != NULL)
  {
    return Mock.list_foreach_CallbackFunctionPointer(list, cb, userdata, Mock.list_foreach_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'list_foreach' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_list), (void*)(list), sizeof(list_t), cmock_line, "Function 'list_foreach' called with unexpected value for argument 'list'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb), sizeof(list_iterate_callback), cmock_line, "Function 'list_foreach' called with unexpected value for argument 'cb'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_userdata), (void*)(&userdata), sizeof(uintptr_t), cmock_line, "Function 'list_foreach' called with unexpected value for argument 'userdata'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_list_foreach(CMOCK_list_foreach_CALL_INSTANCE* cmock_call_instance, list_t* list, list_iterate_callback cb, uintptr_t userdata)
{
  cmock_call_instance->Expected_list = list;
  memcpy(&cmock_call_instance->Expected_cb, &cb, sizeof(list_iterate_callback));
  memcpy(&cmock_call_instance->Expected_userdata, &userdata, sizeof(uintptr_t));
}

void list_foreach_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_list_foreach_CALL_INSTANCE));
  CMOCK_list_foreach_CALL_INSTANCE* cmock_call_instance = (CMOCK_list_foreach_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.list_foreach_CallInstance = CMock_Guts_MemChain(Mock.list_foreach_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.list_foreach_IgnoreBool = (int)1;
}

void list_foreach_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, list_t* list, list_iterate_callback cb, uintptr_t userdata, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_list_foreach_CALL_INSTANCE));
  CMOCK_list_foreach_CALL_INSTANCE* cmock_call_instance = (CMOCK_list_foreach_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.list_foreach_CallInstance = CMock_Guts_MemChain(Mock.list_foreach_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_list_foreach(cmock_call_instance, list, cb, userdata);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void list_foreach_StubWithCallback(CMOCK_list_foreach_CALLBACK Callback)
{
  Mock.list_foreach_CallbackFunctionPointer = Callback;
}

