/*
 * Copyright (c) 2014 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSECURITY_H
#define _MOCKSECURITY_H

#include "unity.h"
#include "security.h"

void Mocksecurity_Init(void);
void Mocksecurity_Destroy(void);
void Mocksecurity_Verify(void);




#define qeo_security_init_IgnoreAndReturn(cmock_retval) qeo_security_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void qeo_security_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return);
#define qeo_security_init_ExpectAndReturn(cmock_retval) qeo_security_init_CMockExpectAndReturn(__LINE__, cmock_retval)
void qeo_security_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return);
typedef qeo_retcode_t (* CMOCK_qeo_security_init_CALLBACK)(int cmock_num_calls);
void qeo_security_init_StubWithCallback(CMOCK_qeo_security_init_CALLBACK Callback);
#define qeo_security_destroy_IgnoreAndReturn(cmock_retval) qeo_security_destroy_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void qeo_security_destroy_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return);
#define qeo_security_destroy_ExpectAndReturn(cmock_retval) qeo_security_destroy_CMockExpectAndReturn(__LINE__, cmock_retval)
void qeo_security_destroy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return);
typedef qeo_retcode_t (* CMOCK_qeo_security_destroy_CALLBACK)(int cmock_num_calls);
void qeo_security_destroy_StubWithCallback(CMOCK_qeo_security_destroy_CALLBACK Callback);
#define qeo_security_construct_IgnoreAndReturn(cmock_retval) qeo_security_construct_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void qeo_security_construct_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return);
#define qeo_security_construct_ExpectAndReturn(cfg, qeoSec, cmock_retval) qeo_security_construct_CMockExpectAndReturn(__LINE__, cfg, qeoSec, cmock_retval)
void qeo_security_construct_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const qeo_security_config* cfg, qeo_security_hndl* qeoSec, qeo_retcode_t cmock_to_return);
typedef qeo_retcode_t (* CMOCK_qeo_security_construct_CALLBACK)(const qeo_security_config* cfg, qeo_security_hndl* qeoSec, int cmock_num_calls);
void qeo_security_construct_StubWithCallback(CMOCK_qeo_security_construct_CALLBACK Callback);
#define qeo_security_authenticate_IgnoreAndReturn(cmock_retval) qeo_security_authenticate_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void qeo_security_authenticate_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return);
#define qeo_security_authenticate_ExpectAndReturn(qeoSec, cmock_retval) qeo_security_authenticate_CMockExpectAndReturn(__LINE__, qeoSec, cmock_retval)
void qeo_security_authenticate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_security_hndl qeoSec, qeo_retcode_t cmock_to_return);
typedef qeo_retcode_t (* CMOCK_qeo_security_authenticate_CALLBACK)(qeo_security_hndl qeoSec, int cmock_num_calls);
void qeo_security_authenticate_StubWithCallback(CMOCK_qeo_security_authenticate_CALLBACK Callback);
#define qeo_security_destruct_IgnoreAndReturn(cmock_retval) qeo_security_destruct_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void qeo_security_destruct_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return);
#define qeo_security_destruct_ExpectAndReturn(qeoSec, cmock_retval) qeo_security_destruct_CMockExpectAndReturn(__LINE__, qeoSec, cmock_retval)
void qeo_security_destruct_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_security_hndl* qeoSec, qeo_retcode_t cmock_to_return);
typedef qeo_retcode_t (* CMOCK_qeo_security_destruct_CALLBACK)(qeo_security_hndl* qeoSec, int cmock_num_calls);
void qeo_security_destruct_StubWithCallback(CMOCK_qeo_security_destruct_CALLBACK Callback);
#define qeo_security_get_credentials_IgnoreAndReturn(cmock_retval) qeo_security_get_credentials_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void qeo_security_get_credentials_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return);
#define qeo_security_get_credentials_ExpectAndReturn(qeoSec, key, certs, cmock_retval) qeo_security_get_credentials_CMockExpectAndReturn(__LINE__, qeoSec, key, certs, cmock_retval)
void qeo_security_get_credentials_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_security_hndl qeoSec, EVP_PKEY** key, STACK_OF(X509)** certs, qeo_retcode_t cmock_to_return);
typedef qeo_retcode_t (* CMOCK_qeo_security_get_credentials_CALLBACK)(qeo_security_hndl qeoSec, EVP_PKEY** key, STACK_OF(X509)** certs, int cmock_num_calls);
void qeo_security_get_credentials_StubWithCallback(CMOCK_qeo_security_get_credentials_CALLBACK Callback);
#define qeo_security_get_identity_IgnoreAndReturn(cmock_retval) qeo_security_get_identity_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void qeo_security_get_identity_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return);
#define qeo_security_get_identity_ExpectAndReturn(qeoSec, id, cmock_retval) qeo_security_get_identity_CMockExpectAndReturn(__LINE__, qeoSec, id, cmock_retval)
void qeo_security_get_identity_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_security_hndl qeoSec, qeo_security_identity** id, qeo_retcode_t cmock_to_return);
typedef qeo_retcode_t (* CMOCK_qeo_security_get_identity_CALLBACK)(qeo_security_hndl qeoSec, qeo_security_identity** id, int cmock_num_calls);
void qeo_security_get_identity_StubWithCallback(CMOCK_qeo_security_get_identity_CALLBACK Callback);
#define qeo_security_free_identity_IgnoreAndReturn(cmock_retval) qeo_security_free_identity_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void qeo_security_free_identity_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return);
#define qeo_security_free_identity_ExpectAndReturn(id, cmock_retval) qeo_security_free_identity_CMockExpectAndReturn(__LINE__, id, cmock_retval)
void qeo_security_free_identity_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_security_identity** id, qeo_retcode_t cmock_to_return);
typedef qeo_retcode_t (* CMOCK_qeo_security_free_identity_CALLBACK)(qeo_security_identity** id, int cmock_num_calls);
void qeo_security_free_identity_StubWithCallback(CMOCK_qeo_security_free_identity_CALLBACK Callback);
#define qeo_security_get_realms_IgnoreAndReturn(cmock_retval) qeo_security_get_realms_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void qeo_security_get_realms_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return);
#define qeo_security_get_realms_ExpectAndReturn(id, length, cmock_retval) qeo_security_get_realms_CMockExpectAndReturn(__LINE__, id, length, cmock_retval)
void qeo_security_get_realms_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_security_identity** id, unsigned int* length, qeo_retcode_t cmock_to_return);
typedef qeo_retcode_t (* CMOCK_qeo_security_get_realms_CALLBACK)(qeo_security_identity** id, unsigned int* length, int cmock_num_calls);
void qeo_security_get_realms_StubWithCallback(CMOCK_qeo_security_get_realms_CALLBACK Callback);
#define qeo_security_free_realms_IgnoreAndReturn(cmock_retval) qeo_security_free_realms_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void qeo_security_free_realms_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return);
#define qeo_security_free_realms_ExpectAndReturn(id, length, cmock_retval) qeo_security_free_realms_CMockExpectAndReturn(__LINE__, id, length, cmock_retval)
void qeo_security_free_realms_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_security_identity** id, unsigned int length, qeo_retcode_t cmock_to_return);
typedef qeo_retcode_t (* CMOCK_qeo_security_free_realms_CALLBACK)(qeo_security_identity** id, unsigned int length, int cmock_num_calls);
void qeo_security_free_realms_StubWithCallback(CMOCK_qeo_security_free_realms_CALLBACK Callback);
#define qeo_security_get_user_data_IgnoreAndReturn(cmock_retval) qeo_security_get_user_data_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void qeo_security_get_user_data_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return);
#define qeo_security_get_user_data_ExpectAndReturn(qeoSec, user_data, cmock_retval) qeo_security_get_user_data_CMockExpectAndReturn(__LINE__, qeoSec, user_data, cmock_retval)
void qeo_security_get_user_data_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_security_hndl qeoSec, void* user_data, qeo_retcode_t cmock_to_return);
typedef qeo_retcode_t (* CMOCK_qeo_security_get_user_data_CALLBACK)(qeo_security_hndl qeoSec, void* user_data, int cmock_num_calls);
void qeo_security_get_user_data_StubWithCallback(CMOCK_qeo_security_get_user_data_CALLBACK Callback);
#define qeo_security_get_mgmt_client_ctx_IgnoreAndReturn(cmock_retval) qeo_security_get_mgmt_client_ctx_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void qeo_security_get_mgmt_client_ctx_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return);
#define qeo_security_get_mgmt_client_ctx_ExpectAndReturn(qeoSec, ctx, cmock_retval) qeo_security_get_mgmt_client_ctx_CMockExpectAndReturn(__LINE__, qeoSec, ctx, cmock_retval)
void qeo_security_get_mgmt_client_ctx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_security_hndl qeoSec, qeo_mgmt_client_ctx_t** ctx, qeo_retcode_t cmock_to_return);
typedef qeo_retcode_t (* CMOCK_qeo_security_get_mgmt_client_ctx_CALLBACK)(qeo_security_hndl qeoSec, qeo_mgmt_client_ctx_t** ctx, int cmock_num_calls);
void qeo_security_get_mgmt_client_ctx_StubWithCallback(CMOCK_qeo_security_get_mgmt_client_ctx_CALLBACK Callback);

#endif
