/*
 * Copyright (c) 2014 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKCRC32_H
#define _MOCKCRC32_H

#include "unity.h"
#include "crc32.h"

void Mockcrc32_Init(void);
void Mockcrc32_Destroy(void);
void Mockcrc32_Verify(void);




#define crc32_IgnoreAndReturn(cmock_retval) crc32_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void crc32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define crc32_ExpectAndReturn(crc, buf, size, cmock_retval) crc32_CMockExpectAndReturn(__LINE__, crc, buf, size, cmock_retval)
void crc32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t crc, const void* buf, size_t size, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_crc32_CALLBACK)(uint32_t crc, const void* buf, size_t size, int cmock_num_calls);
void crc32_StubWithCallback(CMOCK_crc32_CALLBACK Callback);

#endif
