/*
 * Copyright (c) 2014 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#define NO_TEST_ASSERT_EQUAL_MEMORY_MESSAGE
#include "unity.h"
#include "cmock.h"
#include "Mockmgmt_client.h"

typedef struct _CMOCK_qeo_mgmt_client_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_mgmt_client_ctx_t* ReturnVal;

} CMOCK_qeo_mgmt_client_init_CALL_INSTANCE;

typedef struct _CMOCK_qeo_mgmt_client_enroll_device_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_mgmt_client_retcode_t ReturnVal;
  qeo_mgmt_client_ctx_t* Expected_ctx;
  char* Expected_url;
  EVP_PKEY* Expected_pkey;
  char* Expected_otp;
  qeo_platform_device_info* Expected_info;
  qeo_mgmt_client_ssl_ctx_cb Expected_cb;
  void* Expected_cookie;
  STACK_OF(X509)* Expected_certs;

} CMOCK_qeo_mgmt_client_enroll_device_CALL_INSTANCE;

typedef struct _CMOCK_qeo_mgmt_client_get_policy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_mgmt_client_retcode_t ReturnVal;
  qeo_mgmt_client_ctx_t* Expected_ctx;
  char* Expected_url;
  qeo_mgmt_client_ssl_ctx_cb Expected_ssl_cb;
  qeo_mgmt_client_data_cb Expected_data_cb;
  void* Expected_cookie;

} CMOCK_qeo_mgmt_client_get_policy_CALL_INSTANCE;

typedef struct _CMOCK_qeo_mgmt_client_check_policy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_mgmt_client_retcode_t ReturnVal;
  qeo_mgmt_client_ctx_t* Expected_ctx;
  qeo_mgmt_client_ssl_ctx_cb Expected_ssl_cb;
  void* Expected_ssl_cookie;
  char* Expected_url;
  int64_t Expected_sequence_nr;
  int64_t Expected_realm_id;
  bool* Expected_result;

} CMOCK_qeo_mgmt_client_check_policy_CALL_INSTANCE;

typedef struct _CMOCK_qeo_mgmt_client_clean_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_mgmt_client_ctx_t* Expected_ctx;

} CMOCK_qeo_mgmt_client_clean_CALL_INSTANCE;

static struct Mockmgmt_clientInstance
{
  int qeo_mgmt_client_init_IgnoreBool;
  qeo_mgmt_client_ctx_t* qeo_mgmt_client_init_FinalReturn;
  CMOCK_qeo_mgmt_client_init_CALLBACK qeo_mgmt_client_init_CallbackFunctionPointer;
  int qeo_mgmt_client_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_mgmt_client_init_CallInstance;
  int qeo_mgmt_client_enroll_device_IgnoreBool;
  qeo_mgmt_client_retcode_t qeo_mgmt_client_enroll_device_FinalReturn;
  CMOCK_qeo_mgmt_client_enroll_device_CALLBACK qeo_mgmt_client_enroll_device_CallbackFunctionPointer;
  int qeo_mgmt_client_enroll_device_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_mgmt_client_enroll_device_CallInstance;
  int qeo_mgmt_client_get_policy_IgnoreBool;
  qeo_mgmt_client_retcode_t qeo_mgmt_client_get_policy_FinalReturn;
  CMOCK_qeo_mgmt_client_get_policy_CALLBACK qeo_mgmt_client_get_policy_CallbackFunctionPointer;
  int qeo_mgmt_client_get_policy_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_mgmt_client_get_policy_CallInstance;
  int qeo_mgmt_client_check_policy_IgnoreBool;
  qeo_mgmt_client_retcode_t qeo_mgmt_client_check_policy_FinalReturn;
  CMOCK_qeo_mgmt_client_check_policy_CALLBACK qeo_mgmt_client_check_policy_CallbackFunctionPointer;
  int qeo_mgmt_client_check_policy_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_mgmt_client_check_policy_CallInstance;
  int qeo_mgmt_client_clean_IgnoreBool;
  CMOCK_qeo_mgmt_client_clean_CALLBACK qeo_mgmt_client_clean_CallbackFunctionPointer;
  int qeo_mgmt_client_clean_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_mgmt_client_clean_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmgmt_client_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.qeo_mgmt_client_init_IgnoreBool)
    Mock.qeo_mgmt_client_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_mgmt_client_init_CallInstance, cmock_line, "Function 'qeo_mgmt_client_init' called less times than expected.");
  if (Mock.qeo_mgmt_client_init_CallbackFunctionPointer != NULL)
    Mock.qeo_mgmt_client_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_mgmt_client_enroll_device_IgnoreBool)
    Mock.qeo_mgmt_client_enroll_device_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_mgmt_client_enroll_device_CallInstance, cmock_line, "Function 'qeo_mgmt_client_enroll_device' called less times than expected.");
  if (Mock.qeo_mgmt_client_enroll_device_CallbackFunctionPointer != NULL)
    Mock.qeo_mgmt_client_enroll_device_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_mgmt_client_get_policy_IgnoreBool)
    Mock.qeo_mgmt_client_get_policy_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_mgmt_client_get_policy_CallInstance, cmock_line, "Function 'qeo_mgmt_client_get_policy' called less times than expected.");
  if (Mock.qeo_mgmt_client_get_policy_CallbackFunctionPointer != NULL)
    Mock.qeo_mgmt_client_get_policy_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_mgmt_client_check_policy_IgnoreBool)
    Mock.qeo_mgmt_client_check_policy_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_mgmt_client_check_policy_CallInstance, cmock_line, "Function 'qeo_mgmt_client_check_policy' called less times than expected.");
  if (Mock.qeo_mgmt_client_check_policy_CallbackFunctionPointer != NULL)
    Mock.qeo_mgmt_client_check_policy_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_mgmt_client_clean_IgnoreBool)
    Mock.qeo_mgmt_client_clean_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_mgmt_client_clean_CallInstance, cmock_line, "Function 'qeo_mgmt_client_clean' called less times than expected.");
  if (Mock.qeo_mgmt_client_clean_CallbackFunctionPointer != NULL)
    Mock.qeo_mgmt_client_clean_CallInstance = CMOCK_GUTS_NONE;
}

void Mockmgmt_client_Init(void)
{
  Mockmgmt_client_Destroy();
}

void Mockmgmt_client_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.qeo_mgmt_client_init_CallbackFunctionPointer = NULL;
  Mock.qeo_mgmt_client_init_CallbackCalls = 0;
  Mock.qeo_mgmt_client_enroll_device_CallbackFunctionPointer = NULL;
  Mock.qeo_mgmt_client_enroll_device_CallbackCalls = 0;
  Mock.qeo_mgmt_client_get_policy_CallbackFunctionPointer = NULL;
  Mock.qeo_mgmt_client_get_policy_CallbackCalls = 0;
  Mock.qeo_mgmt_client_check_policy_CallbackFunctionPointer = NULL;
  Mock.qeo_mgmt_client_check_policy_CallbackCalls = 0;
  Mock.qeo_mgmt_client_clean_CallbackFunctionPointer = NULL;
  Mock.qeo_mgmt_client_clean_CallbackCalls = 0;
}

qeo_mgmt_client_ctx_t* qeo_mgmt_client_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_mgmt_client_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_mgmt_client_init_CallInstance);
  Mock.qeo_mgmt_client_init_CallInstance = CMock_Guts_MemNext(Mock.qeo_mgmt_client_init_CallInstance);
  if (Mock.qeo_mgmt_client_init_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_mgmt_client_init_FinalReturn;
    Mock.qeo_mgmt_client_init_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_mgmt_client_init_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_mgmt_client_init_CallbackFunctionPointer(Mock.qeo_mgmt_client_init_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_mgmt_client_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void qeo_mgmt_client_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_mgmt_client_ctx_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_mgmt_client_init_CALL_INSTANCE));
  CMOCK_qeo_mgmt_client_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_mgmt_client_init_CallInstance = CMock_Guts_MemChain(Mock.qeo_mgmt_client_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_mgmt_client_init_IgnoreBool = (int)1;
}

void qeo_mgmt_client_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_mgmt_client_ctx_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_mgmt_client_init_CALL_INSTANCE));
  CMOCK_qeo_mgmt_client_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_mgmt_client_init_CallInstance = CMock_Guts_MemChain(Mock.qeo_mgmt_client_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void qeo_mgmt_client_init_StubWithCallback(CMOCK_qeo_mgmt_client_init_CALLBACK Callback)
{
  Mock.qeo_mgmt_client_init_CallbackFunctionPointer = Callback;
}

qeo_mgmt_client_retcode_t qeo_mgmt_client_enroll_device(qeo_mgmt_client_ctx_t* ctx, const char* url, const EVP_PKEY* pkey, const char* otp, const qeo_platform_device_info* info, qeo_mgmt_client_ssl_ctx_cb cb, void* cookie, STACK_OF(X509)* certs)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_mgmt_client_enroll_device_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_enroll_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_mgmt_client_enroll_device_CallInstance);
  Mock.qeo_mgmt_client_enroll_device_CallInstance = CMock_Guts_MemNext(Mock.qeo_mgmt_client_enroll_device_CallInstance);
  if (Mock.qeo_mgmt_client_enroll_device_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_mgmt_client_enroll_device_FinalReturn;
    memcpy(&Mock.qeo_mgmt_client_enroll_device_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_mgmt_client_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_mgmt_client_enroll_device_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_mgmt_client_enroll_device_CallbackFunctionPointer(ctx, url, pkey, otp, info, cb, cookie, certs, Mock.qeo_mgmt_client_enroll_device_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_mgmt_client_enroll_device' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ctx), (void*)(ctx), sizeof(qeo_mgmt_client_ctx_t), cmock_line, "Function 'qeo_mgmt_client_enroll_device' called with unexpected value for argument 'ctx'.");
  if (cmock_call_instance->Expected_url == NULL)
    { UNITY_TEST_ASSERT_NULL(url, cmock_line, "Expected NULL. Function 'qeo_mgmt_client_enroll_device' called with unexpected value for argument 'url'."); }
  else
    { UNITY_TEST_ASSERT_EQUAL_INT8_ARRAY(cmock_call_instance->Expected_url, url, 1, cmock_line, "Function 'qeo_mgmt_client_enroll_device' called with unexpected value for argument 'url'."); }
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pkey), (void*)(pkey), sizeof(EVP_PKEY), cmock_line, "Function 'qeo_mgmt_client_enroll_device' called with unexpected value for argument 'pkey'.");
  if (cmock_call_instance->Expected_otp == NULL)
    { UNITY_TEST_ASSERT_NULL(otp, cmock_line, "Expected NULL. Function 'qeo_mgmt_client_enroll_device' called with unexpected value for argument 'otp'."); }
  else
    { UNITY_TEST_ASSERT_EQUAL_INT8_ARRAY(cmock_call_instance->Expected_otp, otp, 1, cmock_line, "Function 'qeo_mgmt_client_enroll_device' called with unexpected value for argument 'otp'."); }
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_info), (void*)(info), sizeof(qeo_platform_device_info), cmock_line, "Function 'qeo_mgmt_client_enroll_device' called with unexpected value for argument 'info'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cb), (void*)(&cb), sizeof(qeo_mgmt_client_ssl_ctx_cb), cmock_line, "Function 'qeo_mgmt_client_enroll_device' called with unexpected value for argument 'cb'.");
  UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_cookie, cookie, cmock_line, "Function 'qeo_mgmt_client_enroll_device' called with unexpected value for argument 'cookie'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_certs), (void*)(certs), sizeof(STACK_OF(X509)), cmock_line, "Function 'qeo_mgmt_client_enroll_device' called with unexpected value for argument 'certs'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_mgmt_client_enroll_device(CMOCK_qeo_mgmt_client_enroll_device_CALL_INSTANCE* cmock_call_instance, qeo_mgmt_client_ctx_t* ctx, const char* url, const EVP_PKEY* pkey, const char* otp, const qeo_platform_device_info* info, qeo_mgmt_client_ssl_ctx_cb cb, void* cookie, STACK_OF(X509)* certs)
{
  cmock_call_instance->Expected_ctx = ctx;
  cmock_call_instance->Expected_url = (char*)url;
  cmock_call_instance->Expected_pkey = (EVP_PKEY*)pkey;
  cmock_call_instance->Expected_otp = (char*)otp;
  cmock_call_instance->Expected_info = (qeo_platform_device_info*)info;
  memcpy(&cmock_call_instance->Expected_cb, &cb, sizeof(qeo_mgmt_client_ssl_ctx_cb));
  cmock_call_instance->Expected_cookie = cookie;
  cmock_call_instance->Expected_certs = certs;
}

void qeo_mgmt_client_enroll_device_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_mgmt_client_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_mgmt_client_enroll_device_CALL_INSTANCE));
  CMOCK_qeo_mgmt_client_enroll_device_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_enroll_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_mgmt_client_enroll_device_CallInstance = CMock_Guts_MemChain(Mock.qeo_mgmt_client_enroll_device_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_mgmt_client_enroll_device_IgnoreBool = (int)1;
}

void qeo_mgmt_client_enroll_device_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_mgmt_client_ctx_t* ctx, const char* url, const EVP_PKEY* pkey, const char* otp, const qeo_platform_device_info* info, qeo_mgmt_client_ssl_ctx_cb cb, void* cookie, STACK_OF(X509)* certs, qeo_mgmt_client_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_mgmt_client_enroll_device_CALL_INSTANCE));
  CMOCK_qeo_mgmt_client_enroll_device_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_enroll_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_mgmt_client_enroll_device_CallInstance = CMock_Guts_MemChain(Mock.qeo_mgmt_client_enroll_device_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_mgmt_client_enroll_device(cmock_call_instance, ctx, url, pkey, otp, info, cb, cookie, certs);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_mgmt_client_retcode_t));
}

void qeo_mgmt_client_enroll_device_StubWithCallback(CMOCK_qeo_mgmt_client_enroll_device_CALLBACK Callback)
{
  Mock.qeo_mgmt_client_enroll_device_CallbackFunctionPointer = Callback;
}

qeo_mgmt_client_retcode_t qeo_mgmt_client_get_policy(qeo_mgmt_client_ctx_t* ctx, const char* url, qeo_mgmt_client_ssl_ctx_cb ssl_cb, qeo_mgmt_client_data_cb data_cb, void* cookie)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_mgmt_client_get_policy_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_get_policy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_mgmt_client_get_policy_CallInstance);
  Mock.qeo_mgmt_client_get_policy_CallInstance = CMock_Guts_MemNext(Mock.qeo_mgmt_client_get_policy_CallInstance);
  if (Mock.qeo_mgmt_client_get_policy_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_mgmt_client_get_policy_FinalReturn;
    memcpy(&Mock.qeo_mgmt_client_get_policy_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_mgmt_client_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_mgmt_client_get_policy_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_mgmt_client_get_policy_CallbackFunctionPointer(ctx, url, ssl_cb, data_cb, cookie, Mock.qeo_mgmt_client_get_policy_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_mgmt_client_get_policy' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ctx), (void*)(ctx), sizeof(qeo_mgmt_client_ctx_t), cmock_line, "Function 'qeo_mgmt_client_get_policy' called with unexpected value for argument 'ctx'.");
  if (cmock_call_instance->Expected_url == NULL)
    { UNITY_TEST_ASSERT_NULL(url, cmock_line, "Expected NULL. Function 'qeo_mgmt_client_get_policy' called with unexpected value for argument 'url'."); }
  else
    { UNITY_TEST_ASSERT_EQUAL_INT8_ARRAY(cmock_call_instance->Expected_url, url, 1, cmock_line, "Function 'qeo_mgmt_client_get_policy' called with unexpected value for argument 'url'."); }
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_ssl_cb), (void*)(&ssl_cb), sizeof(qeo_mgmt_client_ssl_ctx_cb), cmock_line, "Function 'qeo_mgmt_client_get_policy' called with unexpected value for argument 'ssl_cb'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_data_cb), (void*)(&data_cb), sizeof(qeo_mgmt_client_data_cb), cmock_line, "Function 'qeo_mgmt_client_get_policy' called with unexpected value for argument 'data_cb'.");
  UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_cookie, cookie, cmock_line, "Function 'qeo_mgmt_client_get_policy' called with unexpected value for argument 'cookie'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_mgmt_client_get_policy(CMOCK_qeo_mgmt_client_get_policy_CALL_INSTANCE* cmock_call_instance, qeo_mgmt_client_ctx_t* ctx, const char* url, qeo_mgmt_client_ssl_ctx_cb ssl_cb, qeo_mgmt_client_data_cb data_cb, void* cookie)
{
  cmock_call_instance->Expected_ctx = ctx;
  cmock_call_instance->Expected_url = (char*)url;
  memcpy(&cmock_call_instance->Expected_ssl_cb, &ssl_cb, sizeof(qeo_mgmt_client_ssl_ctx_cb));
  memcpy(&cmock_call_instance->Expected_data_cb, &data_cb, sizeof(qeo_mgmt_client_data_cb));
  cmock_call_instance->Expected_cookie = cookie;
}

void qeo_mgmt_client_get_policy_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_mgmt_client_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_mgmt_client_get_policy_CALL_INSTANCE));
  CMOCK_qeo_mgmt_client_get_policy_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_get_policy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_mgmt_client_get_policy_CallInstance = CMock_Guts_MemChain(Mock.qeo_mgmt_client_get_policy_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_mgmt_client_get_policy_IgnoreBool = (int)1;
}

void qeo_mgmt_client_get_policy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_mgmt_client_ctx_t* ctx, const char* url, qeo_mgmt_client_ssl_ctx_cb ssl_cb, qeo_mgmt_client_data_cb data_cb, void* cookie, qeo_mgmt_client_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_mgmt_client_get_policy_CALL_INSTANCE));
  CMOCK_qeo_mgmt_client_get_policy_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_get_policy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_mgmt_client_get_policy_CallInstance = CMock_Guts_MemChain(Mock.qeo_mgmt_client_get_policy_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_mgmt_client_get_policy(cmock_call_instance, ctx, url, ssl_cb, data_cb, cookie);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_mgmt_client_retcode_t));
}

void qeo_mgmt_client_get_policy_StubWithCallback(CMOCK_qeo_mgmt_client_get_policy_CALLBACK Callback)
{
  Mock.qeo_mgmt_client_get_policy_CallbackFunctionPointer = Callback;
}

qeo_mgmt_client_retcode_t qeo_mgmt_client_check_policy(qeo_mgmt_client_ctx_t* ctx, qeo_mgmt_client_ssl_ctx_cb ssl_cb, void* ssl_cookie, const char* url, int64_t sequence_nr, int64_t realm_id, bool* result)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_mgmt_client_check_policy_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_check_policy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_mgmt_client_check_policy_CallInstance);
  Mock.qeo_mgmt_client_check_policy_CallInstance = CMock_Guts_MemNext(Mock.qeo_mgmt_client_check_policy_CallInstance);
  if (Mock.qeo_mgmt_client_check_policy_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_mgmt_client_check_policy_FinalReturn;
    memcpy(&Mock.qeo_mgmt_client_check_policy_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_mgmt_client_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_mgmt_client_check_policy_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_mgmt_client_check_policy_CallbackFunctionPointer(ctx, ssl_cb, ssl_cookie, url, sequence_nr, realm_id, result, Mock.qeo_mgmt_client_check_policy_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_mgmt_client_check_policy' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ctx), (void*)(ctx), sizeof(qeo_mgmt_client_ctx_t), cmock_line, "Function 'qeo_mgmt_client_check_policy' called with unexpected value for argument 'ctx'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_ssl_cb), (void*)(&ssl_cb), sizeof(qeo_mgmt_client_ssl_ctx_cb), cmock_line, "Function 'qeo_mgmt_client_check_policy' called with unexpected value for argument 'ssl_cb'.");
  UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_ssl_cookie, ssl_cookie, cmock_line, "Function 'qeo_mgmt_client_check_policy' called with unexpected value for argument 'ssl_cookie'.");
  if (cmock_call_instance->Expected_url == NULL)
    { UNITY_TEST_ASSERT_NULL(url, cmock_line, "Expected NULL. Function 'qeo_mgmt_client_check_policy' called with unexpected value for argument 'url'."); }
  else
    { UNITY_TEST_ASSERT_EQUAL_INT8_ARRAY(cmock_call_instance->Expected_url, url, 1, cmock_line, "Function 'qeo_mgmt_client_check_policy' called with unexpected value for argument 'url'."); }
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_sequence_nr), (void*)(&sequence_nr), sizeof(int64_t), cmock_line, "Function 'qeo_mgmt_client_check_policy' called with unexpected value for argument 'sequence_nr'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_realm_id), (void*)(&realm_id), sizeof(int64_t), cmock_line, "Function 'qeo_mgmt_client_check_policy' called with unexpected value for argument 'realm_id'.");
  if (cmock_call_instance->Expected_result == NULL)
    { UNITY_TEST_ASSERT_NULL(result, cmock_line, "Expected NULL. Function 'qeo_mgmt_client_check_policy' called with unexpected value for argument 'result'."); }
  else
    { UNITY_TEST_ASSERT_EQUAL_INT_ARRAY(cmock_call_instance->Expected_result, result, 1, cmock_line, "Function 'qeo_mgmt_client_check_policy' called with unexpected value for argument 'result'."); }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_mgmt_client_check_policy(CMOCK_qeo_mgmt_client_check_policy_CALL_INSTANCE* cmock_call_instance, qeo_mgmt_client_ctx_t* ctx, qeo_mgmt_client_ssl_ctx_cb ssl_cb, void* ssl_cookie, const char* url, int64_t sequence_nr, int64_t realm_id, bool* result)
{
  cmock_call_instance->Expected_ctx = ctx;
  memcpy(&cmock_call_instance->Expected_ssl_cb, &ssl_cb, sizeof(qeo_mgmt_client_ssl_ctx_cb));
  cmock_call_instance->Expected_ssl_cookie = ssl_cookie;
  cmock_call_instance->Expected_url = (char*)url;
  memcpy(&cmock_call_instance->Expected_sequence_nr, &sequence_nr, sizeof(int64_t));
  memcpy(&cmock_call_instance->Expected_realm_id, &realm_id, sizeof(int64_t));
  cmock_call_instance->Expected_result = result;
}

void qeo_mgmt_client_check_policy_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_mgmt_client_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_mgmt_client_check_policy_CALL_INSTANCE));
  CMOCK_qeo_mgmt_client_check_policy_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_check_policy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_mgmt_client_check_policy_CallInstance = CMock_Guts_MemChain(Mock.qeo_mgmt_client_check_policy_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_mgmt_client_check_policy_IgnoreBool = (int)1;
}

void qeo_mgmt_client_check_policy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_mgmt_client_ctx_t* ctx, qeo_mgmt_client_ssl_ctx_cb ssl_cb, void* ssl_cookie, const char* url, int64_t sequence_nr, int64_t realm_id, bool* result, qeo_mgmt_client_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_mgmt_client_check_policy_CALL_INSTANCE));
  CMOCK_qeo_mgmt_client_check_policy_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_check_policy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_mgmt_client_check_policy_CallInstance = CMock_Guts_MemChain(Mock.qeo_mgmt_client_check_policy_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_mgmt_client_check_policy(cmock_call_instance, ctx, ssl_cb, ssl_cookie, url, sequence_nr, realm_id, result);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_mgmt_client_retcode_t));
}

void qeo_mgmt_client_check_policy_StubWithCallback(CMOCK_qeo_mgmt_client_check_policy_CALLBACK Callback)
{
  Mock.qeo_mgmt_client_check_policy_CallbackFunctionPointer = Callback;
}

void qeo_mgmt_client_clean(qeo_mgmt_client_ctx_t* ctx)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_mgmt_client_clean_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_clean_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_mgmt_client_clean_CallInstance);
  Mock.qeo_mgmt_client_clean_CallInstance = CMock_Guts_MemNext(Mock.qeo_mgmt_client_clean_CallInstance);
  if (Mock.qeo_mgmt_client_clean_IgnoreBool)
  {
    return;
  }
  if (Mock.qeo_mgmt_client_clean_CallbackFunctionPointer != NULL)
  {
    Mock.qeo_mgmt_client_clean_CallbackFunctionPointer(ctx, Mock.qeo_mgmt_client_clean_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_mgmt_client_clean' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ctx), (void*)(ctx), sizeof(qeo_mgmt_client_ctx_t), cmock_line, "Function 'qeo_mgmt_client_clean' called with unexpected value for argument 'ctx'.");
}

void CMockExpectParameters_qeo_mgmt_client_clean(CMOCK_qeo_mgmt_client_clean_CALL_INSTANCE* cmock_call_instance, qeo_mgmt_client_ctx_t* ctx)
{
  cmock_call_instance->Expected_ctx = ctx;
}

void qeo_mgmt_client_clean_CMockIgnore(UNITY_LINE_TYPE cmock_line)
{
  Mock.qeo_mgmt_client_clean_IgnoreBool = (int)1;
}

void qeo_mgmt_client_clean_CMockExpect(UNITY_LINE_TYPE cmock_line, qeo_mgmt_client_ctx_t* ctx)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_mgmt_client_clean_CALL_INSTANCE));
  CMOCK_qeo_mgmt_client_clean_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_mgmt_client_clean_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_mgmt_client_clean_CallInstance = CMock_Guts_MemChain(Mock.qeo_mgmt_client_clean_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_mgmt_client_clean(cmock_call_instance, ctx);
}

void qeo_mgmt_client_clean_StubWithCallback(CMOCK_qeo_mgmt_client_clean_CALLBACK Callback)
{
  Mock.qeo_mgmt_client_clean_CallbackFunctionPointer = Callback;
}

