/*
 * Copyright (c) 2014 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#define NO_TEST_ASSERT_EQUAL_MEMORY_MESSAGE
#include "unity.h"
#include "cmock.h"
#include "Mockcrc32.h"

typedef struct _CMOCK_crc32_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;
  uint32_t Expected_crc;
  void* Expected_buf;
  size_t Expected_size;

} CMOCK_crc32_CALL_INSTANCE;

static struct Mockcrc32Instance
{
  int crc32_IgnoreBool;
  uint32_t crc32_FinalReturn;
  CMOCK_crc32_CALLBACK crc32_CallbackFunctionPointer;
  int crc32_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE crc32_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockcrc32_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.crc32_IgnoreBool)
    Mock.crc32_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.crc32_CallInstance, cmock_line, "Function 'crc32' called less times than expected.");
  if (Mock.crc32_CallbackFunctionPointer != NULL)
    Mock.crc32_CallInstance = CMOCK_GUTS_NONE;
}

void Mockcrc32_Init(void)
{
  Mockcrc32_Destroy();
}

void Mockcrc32_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.crc32_CallbackFunctionPointer = NULL;
  Mock.crc32_CallbackCalls = 0;
}

uint32_t crc32(uint32_t crc, const void* buf, size_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_crc32_CALL_INSTANCE* cmock_call_instance = (CMOCK_crc32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.crc32_CallInstance);
  Mock.crc32_CallInstance = CMock_Guts_MemNext(Mock.crc32_CallInstance);
  if (Mock.crc32_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.crc32_FinalReturn;
    Mock.crc32_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.crc32_CallbackFunctionPointer != NULL)
  {
    return Mock.crc32_CallbackFunctionPointer(crc, buf, size, Mock.crc32_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'crc32' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_crc, crc, cmock_line, "Function 'crc32' called with unexpected value for argument 'crc'.");
  UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_buf, buf, cmock_line, "Function 'crc32' called with unexpected value for argument 'buf'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(size_t), cmock_line, "Function 'crc32' called with unexpected value for argument 'size'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_crc32(CMOCK_crc32_CALL_INSTANCE* cmock_call_instance, uint32_t crc, const void* buf, size_t size)
{
  cmock_call_instance->Expected_crc = crc;
  cmock_call_instance->Expected_buf = (void*)buf;
  memcpy(&cmock_call_instance->Expected_size, &size, sizeof(size_t));
}

void crc32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_crc32_CALL_INSTANCE));
  CMOCK_crc32_CALL_INSTANCE* cmock_call_instance = (CMOCK_crc32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.crc32_CallInstance = CMock_Guts_MemChain(Mock.crc32_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.crc32_IgnoreBool = (int)1;
}

void crc32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t crc, const void* buf, size_t size, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_crc32_CALL_INSTANCE));
  CMOCK_crc32_CALL_INSTANCE* cmock_call_instance = (CMOCK_crc32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.crc32_CallInstance = CMock_Guts_MemChain(Mock.crc32_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_crc32(cmock_call_instance, crc, buf, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void crc32_StubWithCallback(CMOCK_crc32_CALLBACK Callback)
{
  Mock.crc32_CallbackFunctionPointer = Callback;
}

