/*
 * Copyright (c) 2014 - Qeo LLC
 *
 * The source code form of this Qeo Open Source Project component is subject
 * to the terms of the Clear BSD license.
 *
 * You can redistribute it and/or modify it under the terms of the Clear BSD
 * License (http://directory.fsf.org/wiki/License:ClearBSD). See LICENSE file
 * for more details.
 *
 * The Qeo Open Source Project also includes third party Open Source Software.
 * See LICENSE file for more details.
 */

/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#define NO_TEST_ASSERT_EQUAL_MEMORY_MESSAGE
#include "unity.h"
#include "cmock.h"
#include "Mocksecurity.h"

typedef struct _CMOCK_qeo_security_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;

} CMOCK_qeo_security_init_CALL_INSTANCE;

typedef struct _CMOCK_qeo_security_destroy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;

} CMOCK_qeo_security_destroy_CALL_INSTANCE;

typedef struct _CMOCK_qeo_security_construct_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_security_config* Expected_cfg;
  qeo_security_hndl* Expected_qeoSec;

} CMOCK_qeo_security_construct_CALL_INSTANCE;

typedef struct _CMOCK_qeo_security_authenticate_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_security_hndl Expected_qeoSec;

} CMOCK_qeo_security_authenticate_CALL_INSTANCE;

typedef struct _CMOCK_qeo_security_destruct_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_security_hndl* Expected_qeoSec;

} CMOCK_qeo_security_destruct_CALL_INSTANCE;

typedef struct _CMOCK_qeo_security_get_credentials_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_security_hndl Expected_qeoSec;
  EVP_PKEY** Expected_key;
  STACK_OF(X509)** Expected_certs;

} CMOCK_qeo_security_get_credentials_CALL_INSTANCE;

typedef struct _CMOCK_qeo_security_get_identity_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_security_hndl Expected_qeoSec;
  qeo_security_identity** Expected_id;

} CMOCK_qeo_security_get_identity_CALL_INSTANCE;

typedef struct _CMOCK_qeo_security_free_identity_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_security_identity** Expected_id;

} CMOCK_qeo_security_free_identity_CALL_INSTANCE;

typedef struct _CMOCK_qeo_security_get_realms_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_security_identity** Expected_id;
  unsigned int* Expected_length;

} CMOCK_qeo_security_get_realms_CALL_INSTANCE;

typedef struct _CMOCK_qeo_security_free_realms_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_security_identity** Expected_id;
  unsigned int Expected_length;

} CMOCK_qeo_security_free_realms_CALL_INSTANCE;

typedef struct _CMOCK_qeo_security_get_user_data_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_security_hndl Expected_qeoSec;
  void* Expected_user_data;

} CMOCK_qeo_security_get_user_data_CALL_INSTANCE;

typedef struct _CMOCK_qeo_security_get_mgmt_client_ctx_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  qeo_retcode_t ReturnVal;
  qeo_security_hndl Expected_qeoSec;
  qeo_mgmt_client_ctx_t** Expected_ctx;

} CMOCK_qeo_security_get_mgmt_client_ctx_CALL_INSTANCE;

static struct MocksecurityInstance
{
  int qeo_security_init_IgnoreBool;
  qeo_retcode_t qeo_security_init_FinalReturn;
  CMOCK_qeo_security_init_CALLBACK qeo_security_init_CallbackFunctionPointer;
  int qeo_security_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_security_init_CallInstance;
  int qeo_security_destroy_IgnoreBool;
  qeo_retcode_t qeo_security_destroy_FinalReturn;
  CMOCK_qeo_security_destroy_CALLBACK qeo_security_destroy_CallbackFunctionPointer;
  int qeo_security_destroy_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_security_destroy_CallInstance;
  int qeo_security_construct_IgnoreBool;
  qeo_retcode_t qeo_security_construct_FinalReturn;
  CMOCK_qeo_security_construct_CALLBACK qeo_security_construct_CallbackFunctionPointer;
  int qeo_security_construct_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_security_construct_CallInstance;
  int qeo_security_authenticate_IgnoreBool;
  qeo_retcode_t qeo_security_authenticate_FinalReturn;
  CMOCK_qeo_security_authenticate_CALLBACK qeo_security_authenticate_CallbackFunctionPointer;
  int qeo_security_authenticate_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_security_authenticate_CallInstance;
  int qeo_security_destruct_IgnoreBool;
  qeo_retcode_t qeo_security_destruct_FinalReturn;
  CMOCK_qeo_security_destruct_CALLBACK qeo_security_destruct_CallbackFunctionPointer;
  int qeo_security_destruct_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_security_destruct_CallInstance;
  int qeo_security_get_credentials_IgnoreBool;
  qeo_retcode_t qeo_security_get_credentials_FinalReturn;
  CMOCK_qeo_security_get_credentials_CALLBACK qeo_security_get_credentials_CallbackFunctionPointer;
  int qeo_security_get_credentials_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_security_get_credentials_CallInstance;
  int qeo_security_get_identity_IgnoreBool;
  qeo_retcode_t qeo_security_get_identity_FinalReturn;
  CMOCK_qeo_security_get_identity_CALLBACK qeo_security_get_identity_CallbackFunctionPointer;
  int qeo_security_get_identity_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_security_get_identity_CallInstance;
  int qeo_security_free_identity_IgnoreBool;
  qeo_retcode_t qeo_security_free_identity_FinalReturn;
  CMOCK_qeo_security_free_identity_CALLBACK qeo_security_free_identity_CallbackFunctionPointer;
  int qeo_security_free_identity_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_security_free_identity_CallInstance;
  int qeo_security_get_realms_IgnoreBool;
  qeo_retcode_t qeo_security_get_realms_FinalReturn;
  CMOCK_qeo_security_get_realms_CALLBACK qeo_security_get_realms_CallbackFunctionPointer;
  int qeo_security_get_realms_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_security_get_realms_CallInstance;
  int qeo_security_free_realms_IgnoreBool;
  qeo_retcode_t qeo_security_free_realms_FinalReturn;
  CMOCK_qeo_security_free_realms_CALLBACK qeo_security_free_realms_CallbackFunctionPointer;
  int qeo_security_free_realms_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_security_free_realms_CallInstance;
  int qeo_security_get_user_data_IgnoreBool;
  qeo_retcode_t qeo_security_get_user_data_FinalReturn;
  CMOCK_qeo_security_get_user_data_CALLBACK qeo_security_get_user_data_CallbackFunctionPointer;
  int qeo_security_get_user_data_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_security_get_user_data_CallInstance;
  int qeo_security_get_mgmt_client_ctx_IgnoreBool;
  qeo_retcode_t qeo_security_get_mgmt_client_ctx_FinalReturn;
  CMOCK_qeo_security_get_mgmt_client_ctx_CALLBACK qeo_security_get_mgmt_client_ctx_CallbackFunctionPointer;
  int qeo_security_get_mgmt_client_ctx_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE qeo_security_get_mgmt_client_ctx_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocksecurity_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.qeo_security_init_IgnoreBool)
    Mock.qeo_security_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_security_init_CallInstance, cmock_line, "Function 'qeo_security_init' called less times than expected.");
  if (Mock.qeo_security_init_CallbackFunctionPointer != NULL)
    Mock.qeo_security_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_security_destroy_IgnoreBool)
    Mock.qeo_security_destroy_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_security_destroy_CallInstance, cmock_line, "Function 'qeo_security_destroy' called less times than expected.");
  if (Mock.qeo_security_destroy_CallbackFunctionPointer != NULL)
    Mock.qeo_security_destroy_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_security_construct_IgnoreBool)
    Mock.qeo_security_construct_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_security_construct_CallInstance, cmock_line, "Function 'qeo_security_construct' called less times than expected.");
  if (Mock.qeo_security_construct_CallbackFunctionPointer != NULL)
    Mock.qeo_security_construct_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_security_authenticate_IgnoreBool)
    Mock.qeo_security_authenticate_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_security_authenticate_CallInstance, cmock_line, "Function 'qeo_security_authenticate' called less times than expected.");
  if (Mock.qeo_security_authenticate_CallbackFunctionPointer != NULL)
    Mock.qeo_security_authenticate_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_security_destruct_IgnoreBool)
    Mock.qeo_security_destruct_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_security_destruct_CallInstance, cmock_line, "Function 'qeo_security_destruct' called less times than expected.");
  if (Mock.qeo_security_destruct_CallbackFunctionPointer != NULL)
    Mock.qeo_security_destruct_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_security_get_credentials_IgnoreBool)
    Mock.qeo_security_get_credentials_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_security_get_credentials_CallInstance, cmock_line, "Function 'qeo_security_get_credentials' called less times than expected.");
  if (Mock.qeo_security_get_credentials_CallbackFunctionPointer != NULL)
    Mock.qeo_security_get_credentials_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_security_get_identity_IgnoreBool)
    Mock.qeo_security_get_identity_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_security_get_identity_CallInstance, cmock_line, "Function 'qeo_security_get_identity' called less times than expected.");
  if (Mock.qeo_security_get_identity_CallbackFunctionPointer != NULL)
    Mock.qeo_security_get_identity_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_security_free_identity_IgnoreBool)
    Mock.qeo_security_free_identity_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_security_free_identity_CallInstance, cmock_line, "Function 'qeo_security_free_identity' called less times than expected.");
  if (Mock.qeo_security_free_identity_CallbackFunctionPointer != NULL)
    Mock.qeo_security_free_identity_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_security_get_realms_IgnoreBool)
    Mock.qeo_security_get_realms_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_security_get_realms_CallInstance, cmock_line, "Function 'qeo_security_get_realms' called less times than expected.");
  if (Mock.qeo_security_get_realms_CallbackFunctionPointer != NULL)
    Mock.qeo_security_get_realms_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_security_free_realms_IgnoreBool)
    Mock.qeo_security_free_realms_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_security_free_realms_CallInstance, cmock_line, "Function 'qeo_security_free_realms' called less times than expected.");
  if (Mock.qeo_security_free_realms_CallbackFunctionPointer != NULL)
    Mock.qeo_security_free_realms_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_security_get_user_data_IgnoreBool)
    Mock.qeo_security_get_user_data_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_security_get_user_data_CallInstance, cmock_line, "Function 'qeo_security_get_user_data' called less times than expected.");
  if (Mock.qeo_security_get_user_data_CallbackFunctionPointer != NULL)
    Mock.qeo_security_get_user_data_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.qeo_security_get_mgmt_client_ctx_IgnoreBool)
    Mock.qeo_security_get_mgmt_client_ctx_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.qeo_security_get_mgmt_client_ctx_CallInstance, cmock_line, "Function 'qeo_security_get_mgmt_client_ctx' called less times than expected.");
  if (Mock.qeo_security_get_mgmt_client_ctx_CallbackFunctionPointer != NULL)
    Mock.qeo_security_get_mgmt_client_ctx_CallInstance = CMOCK_GUTS_NONE;
}

void Mocksecurity_Init(void)
{
  Mocksecurity_Destroy();
}

void Mocksecurity_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.qeo_security_init_CallbackFunctionPointer = NULL;
  Mock.qeo_security_init_CallbackCalls = 0;
  Mock.qeo_security_destroy_CallbackFunctionPointer = NULL;
  Mock.qeo_security_destroy_CallbackCalls = 0;
  Mock.qeo_security_construct_CallbackFunctionPointer = NULL;
  Mock.qeo_security_construct_CallbackCalls = 0;
  Mock.qeo_security_authenticate_CallbackFunctionPointer = NULL;
  Mock.qeo_security_authenticate_CallbackCalls = 0;
  Mock.qeo_security_destruct_CallbackFunctionPointer = NULL;
  Mock.qeo_security_destruct_CallbackCalls = 0;
  Mock.qeo_security_get_credentials_CallbackFunctionPointer = NULL;
  Mock.qeo_security_get_credentials_CallbackCalls = 0;
  Mock.qeo_security_get_identity_CallbackFunctionPointer = NULL;
  Mock.qeo_security_get_identity_CallbackCalls = 0;
  Mock.qeo_security_free_identity_CallbackFunctionPointer = NULL;
  Mock.qeo_security_free_identity_CallbackCalls = 0;
  Mock.qeo_security_get_realms_CallbackFunctionPointer = NULL;
  Mock.qeo_security_get_realms_CallbackCalls = 0;
  Mock.qeo_security_free_realms_CallbackFunctionPointer = NULL;
  Mock.qeo_security_free_realms_CallbackCalls = 0;
  Mock.qeo_security_get_user_data_CallbackFunctionPointer = NULL;
  Mock.qeo_security_get_user_data_CallbackCalls = 0;
  Mock.qeo_security_get_mgmt_client_ctx_CallbackFunctionPointer = NULL;
  Mock.qeo_security_get_mgmt_client_ctx_CallbackCalls = 0;
}

qeo_retcode_t qeo_security_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_security_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_security_init_CallInstance);
  Mock.qeo_security_init_CallInstance = CMock_Guts_MemNext(Mock.qeo_security_init_CallInstance);
  if (Mock.qeo_security_init_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_security_init_FinalReturn;
    memcpy(&Mock.qeo_security_init_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_security_init_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_security_init_CallbackFunctionPointer(Mock.qeo_security_init_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_security_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void qeo_security_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_init_CALL_INSTANCE));
  CMOCK_qeo_security_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_init_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_security_init_IgnoreBool = (int)1;
}

void qeo_security_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_init_CALL_INSTANCE));
  CMOCK_qeo_security_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_init_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeo_security_init_StubWithCallback(CMOCK_qeo_security_init_CALLBACK Callback)
{
  Mock.qeo_security_init_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeo_security_destroy(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_security_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_security_destroy_CallInstance);
  Mock.qeo_security_destroy_CallInstance = CMock_Guts_MemNext(Mock.qeo_security_destroy_CallInstance);
  if (Mock.qeo_security_destroy_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_security_destroy_FinalReturn;
    memcpy(&Mock.qeo_security_destroy_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_security_destroy_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_security_destroy_CallbackFunctionPointer(Mock.qeo_security_destroy_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_security_destroy' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void qeo_security_destroy_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_destroy_CALL_INSTANCE));
  CMOCK_qeo_security_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_destroy_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_destroy_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_security_destroy_IgnoreBool = (int)1;
}

void qeo_security_destroy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_destroy_CALL_INSTANCE));
  CMOCK_qeo_security_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_destroy_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_destroy_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeo_security_destroy_StubWithCallback(CMOCK_qeo_security_destroy_CALLBACK Callback)
{
  Mock.qeo_security_destroy_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeo_security_construct(const qeo_security_config* cfg, qeo_security_hndl* qeoSec)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_security_construct_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_construct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_security_construct_CallInstance);
  Mock.qeo_security_construct_CallInstance = CMock_Guts_MemNext(Mock.qeo_security_construct_CallInstance);
  if (Mock.qeo_security_construct_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_security_construct_FinalReturn;
    memcpy(&Mock.qeo_security_construct_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_security_construct_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_security_construct_CallbackFunctionPointer(cfg, qeoSec, Mock.qeo_security_construct_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_security_construct' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cfg), (void*)(cfg), sizeof(qeo_security_config), cmock_line, "Function 'qeo_security_construct' called with unexpected value for argument 'cfg'.");
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_qeoSec), (void*)(qeoSec), sizeof(qeo_security_hndl), cmock_line, "Function 'qeo_security_construct' called with unexpected value for argument 'qeoSec'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_security_construct(CMOCK_qeo_security_construct_CALL_INSTANCE* cmock_call_instance, const qeo_security_config* cfg, qeo_security_hndl* qeoSec)
{
  cmock_call_instance->Expected_cfg = (qeo_security_config*)cfg;
  cmock_call_instance->Expected_qeoSec = qeoSec;
}

void qeo_security_construct_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_construct_CALL_INSTANCE));
  CMOCK_qeo_security_construct_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_construct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_construct_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_construct_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_security_construct_IgnoreBool = (int)1;
}

void qeo_security_construct_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const qeo_security_config* cfg, qeo_security_hndl* qeoSec, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_construct_CALL_INSTANCE));
  CMOCK_qeo_security_construct_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_construct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_construct_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_construct_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_security_construct(cmock_call_instance, cfg, qeoSec);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeo_security_construct_StubWithCallback(CMOCK_qeo_security_construct_CALLBACK Callback)
{
  Mock.qeo_security_construct_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeo_security_authenticate(qeo_security_hndl qeoSec)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_security_authenticate_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_authenticate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_security_authenticate_CallInstance);
  Mock.qeo_security_authenticate_CallInstance = CMock_Guts_MemNext(Mock.qeo_security_authenticate_CallInstance);
  if (Mock.qeo_security_authenticate_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_security_authenticate_FinalReturn;
    memcpy(&Mock.qeo_security_authenticate_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_security_authenticate_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_security_authenticate_CallbackFunctionPointer(qeoSec, Mock.qeo_security_authenticate_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_security_authenticate' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_qeoSec), (void*)(&qeoSec), sizeof(qeo_security_hndl), cmock_line, "Function 'qeo_security_authenticate' called with unexpected value for argument 'qeoSec'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_security_authenticate(CMOCK_qeo_security_authenticate_CALL_INSTANCE* cmock_call_instance, qeo_security_hndl qeoSec)
{
  memcpy(&cmock_call_instance->Expected_qeoSec, &qeoSec, sizeof(qeo_security_hndl));
}

void qeo_security_authenticate_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_authenticate_CALL_INSTANCE));
  CMOCK_qeo_security_authenticate_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_authenticate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_authenticate_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_authenticate_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_security_authenticate_IgnoreBool = (int)1;
}

void qeo_security_authenticate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_security_hndl qeoSec, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_authenticate_CALL_INSTANCE));
  CMOCK_qeo_security_authenticate_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_authenticate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_authenticate_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_authenticate_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_security_authenticate(cmock_call_instance, qeoSec);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeo_security_authenticate_StubWithCallback(CMOCK_qeo_security_authenticate_CALLBACK Callback)
{
  Mock.qeo_security_authenticate_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeo_security_destruct(qeo_security_hndl* qeoSec)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_security_destruct_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_destruct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_security_destruct_CallInstance);
  Mock.qeo_security_destruct_CallInstance = CMock_Guts_MemNext(Mock.qeo_security_destruct_CallInstance);
  if (Mock.qeo_security_destruct_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_security_destruct_FinalReturn;
    memcpy(&Mock.qeo_security_destruct_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_security_destruct_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_security_destruct_CallbackFunctionPointer(qeoSec, Mock.qeo_security_destruct_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_security_destruct' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_qeoSec), (void*)(qeoSec), sizeof(qeo_security_hndl), cmock_line, "Function 'qeo_security_destruct' called with unexpected value for argument 'qeoSec'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_security_destruct(CMOCK_qeo_security_destruct_CALL_INSTANCE* cmock_call_instance, qeo_security_hndl* qeoSec)
{
  cmock_call_instance->Expected_qeoSec = qeoSec;
}

void qeo_security_destruct_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_destruct_CALL_INSTANCE));
  CMOCK_qeo_security_destruct_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_destruct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_destruct_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_destruct_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_security_destruct_IgnoreBool = (int)1;
}

void qeo_security_destruct_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_security_hndl* qeoSec, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_destruct_CALL_INSTANCE));
  CMOCK_qeo_security_destruct_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_destruct_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_destruct_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_destruct_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_security_destruct(cmock_call_instance, qeoSec);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeo_security_destruct_StubWithCallback(CMOCK_qeo_security_destruct_CALLBACK Callback)
{
  Mock.qeo_security_destruct_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeo_security_get_credentials(qeo_security_hndl qeoSec, EVP_PKEY** key, STACK_OF(X509)** certs)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_security_get_credentials_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_get_credentials_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_security_get_credentials_CallInstance);
  Mock.qeo_security_get_credentials_CallInstance = CMock_Guts_MemNext(Mock.qeo_security_get_credentials_CallInstance);
  if (Mock.qeo_security_get_credentials_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_security_get_credentials_FinalReturn;
    memcpy(&Mock.qeo_security_get_credentials_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_security_get_credentials_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_security_get_credentials_CallbackFunctionPointer(qeoSec, key, certs, Mock.qeo_security_get_credentials_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_security_get_credentials' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_qeoSec), (void*)(&qeoSec), sizeof(qeo_security_hndl), cmock_line, "Function 'qeo_security_get_credentials' called with unexpected value for argument 'qeoSec'.");
  UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_key, key, cmock_line, "Function 'qeo_security_get_credentials' called with unexpected value for argument 'key'.");
  UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_certs, certs, cmock_line, "Function 'qeo_security_get_credentials' called with unexpected value for argument 'certs'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_security_get_credentials(CMOCK_qeo_security_get_credentials_CALL_INSTANCE* cmock_call_instance, qeo_security_hndl qeoSec, EVP_PKEY** key, STACK_OF(X509)** certs)
{
  memcpy(&cmock_call_instance->Expected_qeoSec, &qeoSec, sizeof(qeo_security_hndl));
  cmock_call_instance->Expected_key = key;
  cmock_call_instance->Expected_certs = certs;
}

void qeo_security_get_credentials_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_get_credentials_CALL_INSTANCE));
  CMOCK_qeo_security_get_credentials_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_get_credentials_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_get_credentials_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_get_credentials_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_security_get_credentials_IgnoreBool = (int)1;
}

void qeo_security_get_credentials_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_security_hndl qeoSec, EVP_PKEY** key, STACK_OF(X509)** certs, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_get_credentials_CALL_INSTANCE));
  CMOCK_qeo_security_get_credentials_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_get_credentials_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_get_credentials_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_get_credentials_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_security_get_credentials(cmock_call_instance, qeoSec, key, certs);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeo_security_get_credentials_StubWithCallback(CMOCK_qeo_security_get_credentials_CALLBACK Callback)
{
  Mock.qeo_security_get_credentials_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeo_security_get_identity(qeo_security_hndl qeoSec, qeo_security_identity** id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_security_get_identity_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_get_identity_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_security_get_identity_CallInstance);
  Mock.qeo_security_get_identity_CallInstance = CMock_Guts_MemNext(Mock.qeo_security_get_identity_CallInstance);
  if (Mock.qeo_security_get_identity_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_security_get_identity_FinalReturn;
    memcpy(&Mock.qeo_security_get_identity_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_security_get_identity_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_security_get_identity_CallbackFunctionPointer(qeoSec, id, Mock.qeo_security_get_identity_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_security_get_identity' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_qeoSec), (void*)(&qeoSec), sizeof(qeo_security_hndl), cmock_line, "Function 'qeo_security_get_identity' called with unexpected value for argument 'qeoSec'.");
  UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_id, id, cmock_line, "Function 'qeo_security_get_identity' called with unexpected value for argument 'id'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_security_get_identity(CMOCK_qeo_security_get_identity_CALL_INSTANCE* cmock_call_instance, qeo_security_hndl qeoSec, qeo_security_identity** id)
{
  memcpy(&cmock_call_instance->Expected_qeoSec, &qeoSec, sizeof(qeo_security_hndl));
  cmock_call_instance->Expected_id = id;
}

void qeo_security_get_identity_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_get_identity_CALL_INSTANCE));
  CMOCK_qeo_security_get_identity_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_get_identity_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_get_identity_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_get_identity_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_security_get_identity_IgnoreBool = (int)1;
}

void qeo_security_get_identity_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_security_hndl qeoSec, qeo_security_identity** id, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_get_identity_CALL_INSTANCE));
  CMOCK_qeo_security_get_identity_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_get_identity_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_get_identity_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_get_identity_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_security_get_identity(cmock_call_instance, qeoSec, id);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeo_security_get_identity_StubWithCallback(CMOCK_qeo_security_get_identity_CALLBACK Callback)
{
  Mock.qeo_security_get_identity_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeo_security_free_identity(qeo_security_identity** id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_security_free_identity_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_free_identity_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_security_free_identity_CallInstance);
  Mock.qeo_security_free_identity_CallInstance = CMock_Guts_MemNext(Mock.qeo_security_free_identity_CallInstance);
  if (Mock.qeo_security_free_identity_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_security_free_identity_FinalReturn;
    memcpy(&Mock.qeo_security_free_identity_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_security_free_identity_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_security_free_identity_CallbackFunctionPointer(id, Mock.qeo_security_free_identity_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_security_free_identity' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_id, id, cmock_line, "Function 'qeo_security_free_identity' called with unexpected value for argument 'id'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_security_free_identity(CMOCK_qeo_security_free_identity_CALL_INSTANCE* cmock_call_instance, qeo_security_identity** id)
{
  cmock_call_instance->Expected_id = id;
}

void qeo_security_free_identity_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_free_identity_CALL_INSTANCE));
  CMOCK_qeo_security_free_identity_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_free_identity_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_free_identity_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_free_identity_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_security_free_identity_IgnoreBool = (int)1;
}

void qeo_security_free_identity_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_security_identity** id, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_free_identity_CALL_INSTANCE));
  CMOCK_qeo_security_free_identity_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_free_identity_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_free_identity_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_free_identity_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_security_free_identity(cmock_call_instance, id);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeo_security_free_identity_StubWithCallback(CMOCK_qeo_security_free_identity_CALLBACK Callback)
{
  Mock.qeo_security_free_identity_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeo_security_get_realms(qeo_security_identity** id, unsigned int* length)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_security_get_realms_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_get_realms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_security_get_realms_CallInstance);
  Mock.qeo_security_get_realms_CallInstance = CMock_Guts_MemNext(Mock.qeo_security_get_realms_CallInstance);
  if (Mock.qeo_security_get_realms_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_security_get_realms_FinalReturn;
    memcpy(&Mock.qeo_security_get_realms_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_security_get_realms_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_security_get_realms_CallbackFunctionPointer(id, length, Mock.qeo_security_get_realms_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_security_get_realms' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_id, id, cmock_line, "Function 'qeo_security_get_realms' called with unexpected value for argument 'id'.");
  if (cmock_call_instance->Expected_length == NULL)
    { UNITY_TEST_ASSERT_NULL(length, cmock_line, "Expected NULL. Function 'qeo_security_get_realms' called with unexpected value for argument 'length'."); }
  else
    { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_length, length, 1, cmock_line, "Function 'qeo_security_get_realms' called with unexpected value for argument 'length'."); }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_security_get_realms(CMOCK_qeo_security_get_realms_CALL_INSTANCE* cmock_call_instance, qeo_security_identity** id, unsigned int* length)
{
  cmock_call_instance->Expected_id = id;
  cmock_call_instance->Expected_length = length;
}

void qeo_security_get_realms_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_get_realms_CALL_INSTANCE));
  CMOCK_qeo_security_get_realms_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_get_realms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_get_realms_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_get_realms_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_security_get_realms_IgnoreBool = (int)1;
}

void qeo_security_get_realms_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_security_identity** id, unsigned int* length, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_get_realms_CALL_INSTANCE));
  CMOCK_qeo_security_get_realms_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_get_realms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_get_realms_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_get_realms_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_security_get_realms(cmock_call_instance, id, length);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeo_security_get_realms_StubWithCallback(CMOCK_qeo_security_get_realms_CALLBACK Callback)
{
  Mock.qeo_security_get_realms_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeo_security_free_realms(qeo_security_identity** id, unsigned int length)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_security_free_realms_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_free_realms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_security_free_realms_CallInstance);
  Mock.qeo_security_free_realms_CallInstance = CMock_Guts_MemNext(Mock.qeo_security_free_realms_CallInstance);
  if (Mock.qeo_security_free_realms_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_security_free_realms_FinalReturn;
    memcpy(&Mock.qeo_security_free_realms_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_security_free_realms_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_security_free_realms_CallbackFunctionPointer(id, length, Mock.qeo_security_free_realms_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_security_free_realms' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_id, id, cmock_line, "Function 'qeo_security_free_realms' called with unexpected value for argument 'id'.");
  UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_length, length, cmock_line, "Function 'qeo_security_free_realms' called with unexpected value for argument 'length'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_security_free_realms(CMOCK_qeo_security_free_realms_CALL_INSTANCE* cmock_call_instance, qeo_security_identity** id, unsigned int length)
{
  cmock_call_instance->Expected_id = id;
  cmock_call_instance->Expected_length = length;
}

void qeo_security_free_realms_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_free_realms_CALL_INSTANCE));
  CMOCK_qeo_security_free_realms_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_free_realms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_free_realms_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_free_realms_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_security_free_realms_IgnoreBool = (int)1;
}

void qeo_security_free_realms_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_security_identity** id, unsigned int length, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_free_realms_CALL_INSTANCE));
  CMOCK_qeo_security_free_realms_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_free_realms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_free_realms_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_free_realms_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_security_free_realms(cmock_call_instance, id, length);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeo_security_free_realms_StubWithCallback(CMOCK_qeo_security_free_realms_CALLBACK Callback)
{
  Mock.qeo_security_free_realms_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeo_security_get_user_data(qeo_security_hndl qeoSec, void* user_data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_security_get_user_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_get_user_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_security_get_user_data_CallInstance);
  Mock.qeo_security_get_user_data_CallInstance = CMock_Guts_MemNext(Mock.qeo_security_get_user_data_CallInstance);
  if (Mock.qeo_security_get_user_data_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_security_get_user_data_FinalReturn;
    memcpy(&Mock.qeo_security_get_user_data_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_security_get_user_data_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_security_get_user_data_CallbackFunctionPointer(qeoSec, user_data, Mock.qeo_security_get_user_data_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_security_get_user_data' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_qeoSec), (void*)(&qeoSec), sizeof(qeo_security_hndl), cmock_line, "Function 'qeo_security_get_user_data' called with unexpected value for argument 'qeoSec'.");
  UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_user_data, user_data, cmock_line, "Function 'qeo_security_get_user_data' called with unexpected value for argument 'user_data'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_security_get_user_data(CMOCK_qeo_security_get_user_data_CALL_INSTANCE* cmock_call_instance, qeo_security_hndl qeoSec, void* user_data)
{
  memcpy(&cmock_call_instance->Expected_qeoSec, &qeoSec, sizeof(qeo_security_hndl));
  cmock_call_instance->Expected_user_data = user_data;
}

void qeo_security_get_user_data_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_get_user_data_CALL_INSTANCE));
  CMOCK_qeo_security_get_user_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_get_user_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_get_user_data_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_get_user_data_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_security_get_user_data_IgnoreBool = (int)1;
}

void qeo_security_get_user_data_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_security_hndl qeoSec, void* user_data, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_get_user_data_CALL_INSTANCE));
  CMOCK_qeo_security_get_user_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_get_user_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_get_user_data_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_get_user_data_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_security_get_user_data(cmock_call_instance, qeoSec, user_data);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeo_security_get_user_data_StubWithCallback(CMOCK_qeo_security_get_user_data_CALLBACK Callback)
{
  Mock.qeo_security_get_user_data_CallbackFunctionPointer = Callback;
}

qeo_retcode_t qeo_security_get_mgmt_client_ctx(qeo_security_hndl qeoSec, qeo_mgmt_client_ctx_t** ctx)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_qeo_security_get_mgmt_client_ctx_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_get_mgmt_client_ctx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.qeo_security_get_mgmt_client_ctx_CallInstance);
  Mock.qeo_security_get_mgmt_client_ctx_CallInstance = CMock_Guts_MemNext(Mock.qeo_security_get_mgmt_client_ctx_CallInstance);
  if (Mock.qeo_security_get_mgmt_client_ctx_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.qeo_security_get_mgmt_client_ctx_FinalReturn;
    memcpy(&Mock.qeo_security_get_mgmt_client_ctx_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(qeo_retcode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.qeo_security_get_mgmt_client_ctx_CallbackFunctionPointer != NULL)
  {
    return Mock.qeo_security_get_mgmt_client_ctx_CallbackFunctionPointer(qeoSec, ctx, Mock.qeo_security_get_mgmt_client_ctx_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'qeo_security_get_mgmt_client_ctx' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_qeoSec), (void*)(&qeoSec), sizeof(qeo_security_hndl), cmock_line, "Function 'qeo_security_get_mgmt_client_ctx' called with unexpected value for argument 'qeoSec'.");
  UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_ctx, ctx, cmock_line, "Function 'qeo_security_get_mgmt_client_ctx' called with unexpected value for argument 'ctx'.");
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_qeo_security_get_mgmt_client_ctx(CMOCK_qeo_security_get_mgmt_client_ctx_CALL_INSTANCE* cmock_call_instance, qeo_security_hndl qeoSec, qeo_mgmt_client_ctx_t** ctx)
{
  memcpy(&cmock_call_instance->Expected_qeoSec, &qeoSec, sizeof(qeo_security_hndl));
  cmock_call_instance->Expected_ctx = ctx;
}

void qeo_security_get_mgmt_client_ctx_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_get_mgmt_client_ctx_CALL_INSTANCE));
  CMOCK_qeo_security_get_mgmt_client_ctx_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_get_mgmt_client_ctx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_get_mgmt_client_ctx_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_get_mgmt_client_ctx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.qeo_security_get_mgmt_client_ctx_IgnoreBool = (int)1;
}

void qeo_security_get_mgmt_client_ctx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, qeo_security_hndl qeoSec, qeo_mgmt_client_ctx_t** ctx, qeo_retcode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_qeo_security_get_mgmt_client_ctx_CALL_INSTANCE));
  CMOCK_qeo_security_get_mgmt_client_ctx_CALL_INSTANCE* cmock_call_instance = (CMOCK_qeo_security_get_mgmt_client_ctx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.qeo_security_get_mgmt_client_ctx_CallInstance = CMock_Guts_MemChain(Mock.qeo_security_get_mgmt_client_ctx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_qeo_security_get_mgmt_client_ctx(cmock_call_instance, qeoSec, ctx);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(qeo_retcode_t));
}

void qeo_security_get_mgmt_client_ctx_StubWithCallback(CMOCK_qeo_security_get_mgmt_client_ctx_CALLBACK Callback)
{
  Mock.qeo_security_get_mgmt_client_ctx_CallbackFunctionPointer = Callback;
}

